Gemfile
Gemfile.lock
circle.yml
test/controllers/cases_controller_test.rb
test/factories/user.rb
test/fixtures/users.yml
test/integration/everything_ok_alarm_test.rb
test/test_helper.rb

Sets up Minitest and circleCI continuous integration, so we can add tests painlessly going forward, and protect ourselves from introducing breaking changes. 
Full breakout of what this adds: 
* Minitest related reporting gems
* circle.yml file, to set a ruby version in test without forcing one in the gemfile
* Add and set up Factory Girl for fixtures
* Creates an integration test to make sure the main page loads

Add testing and continuous integration

---

app/models/user.rb

This limits mongo's name fields to just `name`, rather than first and last name. (Sorry @kevin-wei and @NerdyGirl537 and @adinneen and @drownedout , I know we just changed this at the last meeting). 
My reasoning for wanting to change it back is as follows:
a) A couple things (the signup page, most notably) require specifically whitelisting non-devise attributes in the User model. So this is a slightly more involved change than just changing some Mongo attributes. (We'll also need to change the devise `sign_up` view, and add any permitted fields to a hash in `ApplicationController`.)
b) There's also a privacy issue with firstname and lastname of CMs; this would be, I think, pretty unique among DCAF docs on the internet in that it would have firstname and lastname. Our Excel doc just does …

roll firstname lastname back to just name for User model

---

app/controllers/calls_controller.rb
app/views/calls/_new_call.html.erb
test/controllers/calls_controller_test.rb

Resolves a params hash issue on the call log forms. 
PS to @ajohnson052: tl;dr you were right about strong params behavior. My mistake, sorry! It looks like the common testing strategy is to just make sure that other parameters get filtered out.

Call params

---

LICENSE.txt
README.md
civic.json

Adds an MIT license and makes edits in the readme and the civic.json. 
@stvnrlly for yr review. 
Fixes #58

Add MIT license

---

app/views/pregnancies/_table_content.html.erb

The modal identifier in the new call link wasn't lining up with the modals so the link didn't do anything. Now it brings up a new call corresponding with the patient!

Hotfix - Call modal

---

app/views/pregnancies/_abortion_information.html.erb
app/views/pregnancies/_menu.html.erb
app/views/pregnancies/_patient_information.html.erb
app/views/pregnancies/edit.html.erb

Adds some classes to set up proper layout matching invision, and allow tabbing between sections.
This buries a couple of bodies that are not feature-critical, that I think are best left for someone who knows what they're doing with CSS. But the core part of this (tabbing between sections! ooh! aah) is in this PR. 
Fixes #96

Partials arrangement

---

app/controllers/users_controller.rb
config/routes.rb
test/controllers/users_controller_test.rb

Adds a few bells and whistles to the routes, a rescue_from block to the users controller in case a pregnancy or id isn't found, and some controller behavior tests for call list building methods. 
Thanks to @ajohnson052 for making these methods super easy to write tests for !
Fixes #125

Add controller test for users#add_pregnancy and users#remove_pregnancy

---

app/controllers/calls_controller.rb
app/models/call.rb
app/models/user.rb
test/controllers/calls_controller_test.rb
test/factories/call.rb
test/models/call_test.rb

What started as tying calls to user became so much more. Adds a slew of controller and model tests for call, 
* Requires that a call be tied to a user
* Adjusts controller to fit that behavior
* Adds tests on the model and controller levels to confirm most of the call controller and object behaviors
* Adds a user method to get a call's creator
* Other assorted tidying
Fixes #155

Add call creation

---

db/seeds.rb

Spent some time troubleshooting a case when calls weren't saving -- apparently the issue was that calls without user ids were being considered invalid and preventing the entire document from saving. This is now a mongo behavior I know about. 
Anyway, here's an incremental improvement that came out of this -- adding a user to the seedfile!

Add user to seedfile

---

app/controllers/calls_controller.rb
app/views/calls/_new_call.html.erb
config/routes.rb
test/controllers/calls_controller_test.rb

In our routes, we had resources for calls and notes in a `member` block, which was rendering our routes as follows:
```
calls POST   /pregnancies/:id/calls(.:format)               calls#create
notes POST   /pregnancies/:id/notes(.:format)               notes#create
note PATCH  /pregnancies/:id/notes/:id(.:format)           notes#update
PUT    /pregnancies/:id/notes/:id(.:format)           notes#update
```
Which in turn was making it impossible to build the update route for `notes`, since there were two `params[:id]`s. 
This takes that out, which makes the routing behave as follows: 
```
pregnancy_calls POST   /pregnancies/:pregnancy_id/calls(.:format)     calls#create
pregnancy_notes POST   /pregnancies/:pregnancy_id/notes(.:format)     notes#create
pregnancy_note PATCH …
```

Alter routes

---

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE

Adds a standard form that will populate on initializing pull requests and issues, to encourage more fully fleshed out decisions. Future us will thank us. 
@mebates @adinneen let me know if you have any feedback! Can probably wait until the next full meeting. 
Fixes #206

Add standard templates for pull requests and bug logging

---

README.md

* Adds issue labels and what they mean to the readme
* Fixes #3

Add issue structure to readme

---

README.md

* Adds the 'beginners welcome' category to the list of issue categories in the readme
* Adds a clarifying comment to how we use issues on this project
* Fixes #234

add beginners welcome label to the readme

---

app/models/patient.rb

* add length validations(12 characters) to the patient.rb primary and secondary phone fields
* Fixes #225

Restrict phone fields to a single number #225

---

README.md

* "headahce" => "headache"
* Adds a link to the [Docker install page](https://docs.docker.com/engine/installation/)
* Not applicable to a specific issue, but Code For DC Project Co-Leads are doing a Readme Audit of projects Readme's to ensure install instructions allow newcomers to get a local development environment of our applications spun up quickly. Was able to get the app working with the Docker instructions and figured adding a link to install Docker would help newcomers a tad more 😃 .

Fixes spelling error and adds a link to the Docker install page.

---

app/helpers/pregnancies_helper.rb
test/helpers/last_menstrual_period_helper.rb
test/helpers/last_menstrual_period_helper_test.rb
test/helpers/pregnancies_helper_test.rb
test/models/pregnancy_test.rb

Adds test files for helper methods, rather than doing everything in the model. Gotta bump that code coverage up!
* Moves LMP Helper methods into their own test, and removes them from the pregnancy model test
* Adds tests for the display helper methods in `pregnancies_helper`
* Fixes #297

Add separate tests for helpers

---

config/mongoid.yml

Fix a small stupid config bug that was making the test suite eat mud when you tried to run it from within `docker-compose`.

adjust so that docker-compose run web rake test works

---

test/integration/logging_calls_test.rb

Turns out the call logging integration test, which is the first real JS-capybara test I've written, is a REAL bear about not making DB calls. I have no idea why they were causing failures, but they were, so I threw out the db calls and replaced with tests that didn't involve db hits. 
This should fix the random CI failures we've been experiencing. 
* Adjusts some tests to not make DB calls, and instead just looks at the call log directly
No associated issues.

Fix logging call test by removing DB object retrieval

---

README.md

Minimal readme change, just adds a note about `deploy` issues to the readme. 
No related issues.

add deploy tag to readme

---

app/assets/stylesheets/pregnancies.scss
app/views/pregnancies/_new_pregnancy.html.erb

Fixed grid for now so that it will all stay on the same line. HOWEVER I had to change "First and Last Name" back to "Name" to save space, and "Phone Number" to "number". Will need to return back to this to potentially move some form elements to another row.

fixed problem with grid on new pregnancies partial

---

app/controllers/dashboards_controller.rb
app/views/pregnancies/_new_pregnancy.html.erb

Picks up @Nico-ehs work in #288 , and edits a variable name for readability.
* Renames a date variable to `@today`
* Sets a default date in new patient creation form
* Fixes #288 
Thanks for your work on this @Nico-ehs !

Finish currentdate in patient creation form

---

README.md

* Adds remote upstream instructions (thanks @rekhers )
* Demotes cloud9 in the readme order because of whoever screwed up the alias for the `mongod` command a few weeks ago
* Fixes #338

Readme update: add upstream instructions; move cloud9 down in the pecking order

---

Gemfile

`quality` gem needs to be in non-just dev groups so it doesn't break the CircleCI post deploy hook :(, so implementing this hotfix of moving a gem out of `group :development, :test`.

move quality to all groups

---

app/views/pregnancies/_patient_dashboard.html.erb
test/integration/audit_trail_logging_test.rb
test/integration/show_pregnancy_information_test.rb
test/integration/update_patient_info_test.rb

* Adds an integration test for switching between sections in the pregnancy edit view
* Fixes a few scrub fields in integration tests that were failing
* Fixes #101

Add integration test for pregnancy edit view section clicking

---

config/environments/production.rb

* force ssl in production
* Deals with #327  Rails side
see notes http://www.eq8.eu/blogs/14-config-force_ssl-is-different-than-controller-force_ssl
(can be done controller side if not needed for whole site)

force ssl in config

---

Gemfile
Gemfile.lock
README.md
test/test_helper.rb

18F guide recommends having at least 90% test coverage, and also I want to brag to other projects about how well tested this project is, so I'm adding a codecov badge and configs.
* Adds `codecov` gem
* Adds codecov badge to readme, for showing off

Add Codecov and test coverage badge

---

app/views/pregnancies/_notes.html.erb
test/integration/dashboard_link_test.rb
test/integration/logging_calls_test.rb
test/integration/note_creation_test.rb
test/integration/show_pregnancy_information_test.rb
test/integration/update_patient_info_test.rb

Turns out minitest is faster than the webdriver, so tests are randomly failing once in awhile.
Here is a blog post about the general principle about why they're failing - https://nulogy.com/who-we-are/company-blog/articles/sleep-is-for-the-weak/
* Fixes integration tests to wait for elements instead of just pushing ahead, always pushing ahead
* Bumps #375

Fix most CI false flag failures

---

app/models/audit_trail.rb
app/views/pregnancies/_call_log.html.erb
app/views/pregnancies/_change_log.html.erb
app/views/pregnancies/_notes.html.erb
config/initializers/time.rb
test/integration/logging_calls_test.rb

Extends our `Time` class by adding convenience display methods to it.
* Adds `#display_date`, which displays a date in the form of 'YYYY-MM-DD'
* Adds `#display_time`, which displays a time in the form of 'HH:MM pm`
* Adds `#display_timestamp`, which displays the date and time using both those methods
* Changes our existing view code to use these methods
* Fixes #177

Add display_date, display_time, and display_timestamp to time object

---

app/controllers/pregnancies_controller.rb
app/helpers/pregnancies_helper.rb
app/models/pregnancy.rb
app/views/pregnancies/_patient_information.html.erb
codecov.yml
test/helpers/pregnancies_helper_test.rb
test/integration/update_patient_info_test.rb

Creates a slew of view helpers for structured pregnancy information using patterns established by @charleshuang80 .
Keeping them as strings on the model for now for reasons of portability. If we decide we'd rather have as model enums, should be easy enough to switch over. 
* Alters (attribute)_options methods and works them into the patient_information view
* Adjusts tests to match
* Fixes #200

Add dropdowns

---

config/environments/production.rb

Small fix to prevent header screwin' with.
* some production config edits
* adding an env var
* Fixes #414
* Bumps #387 (makes the config change; doesn't fix the heroku-side settings)

Prevent host header injection

---

Dockerfile
Gemfile
circle.yml

SpooooOOOOOOooooky
**Note: To not futz with Docker builds and ruby version issues too badly, we're going to bump the ruby version to the latest secure version, 2.3.1.**
* Bumps ruby to 2.3.1
* Haunts Dockerfile
* Adjusts a few other files to reflect new ruby version
* Fixes #312

bump Ruby version / Haunt Dockerfile with PhantomJS

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.css.scss
app/assets/stylesheets/dashboards.scss
app/views/pregnancies/_new_pregnancy.html.erb
app/views/pregnancies/_patient_information.html.erb

@sco-bo I took yr PR and ran with a little bit. Couldn't quite get it to work on the pregnancy edit view (might be a bootstrap_forms gem issue?) so I stubbed it for the time being. Thanks for getting this going, my dude! Want to take a look at this and confirm that it makes sense and stuff?
* Finishes off adding pretty toggle switch to new pregnancy form
* Adds plain old boring checkbox to pregnancy edit view
* Half-fixes #365

Add bootstrap-toggle to new pregnancy partial

---

app/views/pregnancies/_patient_information.html.erb
test/integration/update_patient_info_test.rb

Turns the `special_circumstances` select into a text field, so we can stub before the test run.
* does what it says on the label
* deploy-bumps #434

Change special circumstances to a text field for now

---

config/initializers/devise.rb
test/integration/password_reset_test.rb

Turns on devise's `paranoid_mode` to prevent enumeration sketchiness with the password reset form.
cc @mccabe615
* literally just uncomments a line in the devise initializer
* Fixes #418 
* Fixes #380

Turn on devise paranoid mode

---

app/models/user.rb

Turn off rememberable module and fields in user.rb
* Turn off rememberable module and fields in user.rb
* Left the rememberable settings in devise.rb untouched 
* Turn off 'Remember me' option on sign in #388

Turn off 'Remember me' option on sign in #388

---

app/models/user.rb
config/initializers/devise.rb
test/integration/call_list_test.rb

Configure Devise timeoutable.
* add timeoutable module to user.rb
* set timeout to 2 hours in devise.rb
* Turn on Devise::Timeoutable #379

Turn on Devise::Timeoutable #379

---

app/assets/javascripts/pregnancies.coffee
app/controllers/notes_controller.rb
app/controllers/pregnancies_controller.rb
app/models/pregnancy.rb
app/views/notes/_notes_table.html.erb
app/views/notes/create.js.erb
app/views/pregnancies/_abortion_information.html.erb
app/views/pregnancies/_menu.html.erb
app/views/pregnancies/_notes.html.erb
app/views/pregnancies/_patient_dashboard.html.erb
app/views/pregnancies/_patient_information.html.erb
app/views/pregnancies/edit.html.erb
test/controllers/notes_controller_test.rb
test/controllers/pregnancies_controller_test.rb
test/integration/audit_trail_logging_test.rb
test/integration/note_creation_test.rb
test/integration/update_patient_info_test.rb

What started as just changing a controller to respond to js turned into an overhaul of the pregnancy edit form structure. 
TK: Fixing tests. But I wanted to get the PR in early so team ux knew this was coming down the pike, and so nobody else burned time on those issues.
Also TK: Adjusting `notes/create.js.erb` to append or reload the partial.
* Makes every pregnancy partial have its own form, to avoid form crosstalk
* Makes those forms submit on change
* Moves those forms and controller to be ajaxy
* Adjusts notes form and controller to be ajaxy too
* Fixes #308 
* Fixes #404

Ajaxify pregnancy edit view and note creation

---

Gemfile
Gemfile.lock
config/initializers/session_store.rb

Does what it says on the label.
* Installs a mongo gem that moves sessions to db
* Adjusts configs
* Fixes #385

move session store to a mongoid table

---

app/assets/stylesheets/application.css.scss
vendor/assets/stylesheets/googleapis_source_sans_pro.scss

Puts the nail in the coffin on getting our assets into the asset pipeline by moving the google fonts api call into its own stylesheet.
* Removes import in `application.scss`
* Creates vendor stylesheet
* Fixes #134

move googleapis import to vendor stylesheet

---

app/helpers/pregnancies_helper.rb
app/models/clinic.rb
app/views/pregnancies/_abortion_information.html.erb
test/controllers/pregnancies_controller_test.rb
test/integration/show_pregnancy_information_test.rb

This removes clinic address info, to reduce data entry pain, and changes it to a dropdown instead.
* Adds a helper to populate clinics field
* Creates a place to pop in `ENV['CLINICS']`
* Comments out clinic address from form. (Keeping the structure in the HTML just in case we want to turn it into helper text.)
Leaving this open until we have the clinics implemented in prod. 
* Fixes #447

switch clinics to an env var, remove clinic infor

---

app/controllers/dashboards_controller.rb
app/controllers/pregnancies_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/dashboards/search.js.erb
app/views/pregnancies/_new_pregnancy.html.erb
app/views/pregnancies/_notes.html.erb
test/integration/new_patient_creation_test.rb
test/integration/record_lookup_test.rb
test/models/user_test.rb

This PR adds a few case manager conveniences that are really, really, really annoying. Specifically, the new pregnancy form autopopulates the search params, and after you create a patient they get added to the call list.
* Moves `add_pregnancy` and `remove_pregnancy` to be model methods
* Tweaks dashboards controller to pass along name or phone
* Calls `User.add_pregnancy` within `PregnanciesController#create`
* Adds tests! Glorious tests
* Fixes #397 
* Fixes #398

Add new patients to call list after creation, populate search result with info

---

config/initializers/filter_parameter_logging.rb

I included params to filter on inside /config/initializers/filter_parameter_logging.rb, anything thought could be sensitive.  In issue 382, Colin mentioned filtering on the pregnancy and patient model, but I also thought the addresses from the clinic model might be good to add here too, as well as the full_text attribute from the notes model in case people add names and other info inside their notes. 
* Fixes #382

adds parameters to be filtered from loggin

---

app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/shared/_links.html.erb
app/views/layouts/_navigation_links.html.erb
config/routes.rb
test/integration/sign_up_test.rb

Had to yakshave this a bit but got it going. 
**Until we figure out an appropriate way to handle in release 2 (probably administrator invitation), we'll need to create new users from the rails console.**
* Removes non-password-editing routes from devise
* Turns off frontend user signup
* Fixes tests
* Fixes #497

Turn off registration but keep edit

---

config/application.rb
config/initializers/time.rb

Brute-forced this a little bit. This changes the app config to use EST (The best time zone) so that timestamps show up right.
* Adjusts app config to hardset EST
* Fixes #485

Set timezone to UTC

---

app/controllers/pregnancies_controller.rb
app/models/patient.rb
app/models/pregnancy.rb
app/views/pregnancies/_abortion_information.html.erb
app/views/pregnancies/_patient_information.html.erb
app/views/pregnancies/_pledge.html.erb
test/integration/record_lookup_test.rb
test/integration/show_pregnancy_information_test.rb
test/integration/update_patient_info_test.rb
test/models/audit_trail_test.rb
test/models/patient_test.rb
test/models/pregnancy_test.rb

Picks up @dfelsent 's work to add financial / pledge portion, and shoehorn in secondary person information. Additional work is mostly just testing.
TODO still: Make sure that search works with secondary  people, both in the model and in the integration tests
* Adds $ to abortion information view
* Adds secondary contact info to view
* Makes appropriate model and controller changes
* Testin'
* Fixes #480 
* Bumps #450

Add funding information to view; add secondary relationship field

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/pregnancies.scss

- load custom css after bootstrap
* custom css was being overridden by bootstrap css because bootstrap was being loaded afterward
* this changes the css load order to move custom css later on
* allows `!important` to be removed
* Fixes #496

Css load order

---

app/controllers/pregnancies_controller.rb
app/models/pregnancy.rb
app/views/pregnancies/_abortion_information.html.erb
app/views/pregnancies/_patient_dashboard.html.erb
test/integration/update_patient_info_test.rb
test/models/pregnancy_test.rb

Adds @ashlynnpai 's resolved without assistance from dcaf work to the views; alters integration tests appropriately as well.
I didn't have a better place to put it, so I tossed it as a checkbox under the `Abortion information` section. 
Screenshot: 
* Fixes #528

Add mark as resolved to views

---

test/models/user_test.rb

Adds a quick unit test to ensure a pregnancy can be on multiple call lists.
* Does what it says on the label
* Fixes #275

Add unit test for user-pregnancies relationship

---

test/integration/logging_calls_test.rb
test/integration/update_patient_info_test.rb

Rehab work on the integration tests to use more matchers, so that the call logging integration tests don't randomly fail for no goddamned good reason.
If I can get this to pass five times in a row I'm going to call it good. 
* Fixes #375

WIP - Fix integration test from hell

---

app/assets/stylesheets/application.css.scss
app/views/pregnancies/_notes.html.erb

Hi! This reduces the size of the textarea for the notes entry box so the notes log is visible without scrolling. The size of the textarea was half the issue; the notes area also had a `margin-bottom` class which pushed the notes log down by 100px, great for other areas but too much for this one. I changed the class to a new `margin-bottom-sm` and defined it so it only pushes it down by 50px. 
* reduced the size of the textarea in the markup for app/views/pregnancies/_notes.html.erb;
* changes the class of the notes area from `margin-bottom` to `margin-bottom-sm`;
* defines `margin-bottom-sm` as having a margin-bottom of 50px. 
* Fixes #525

Smallnotes

---

app/assets/javascripts/application.js

This adds some jQuery to dismiss the popups you see when you click a note in Dashboard view. Now when you click anywhere that is not in the active popup the popup is dismissed. This also prevents there from being more than one popup open at a time. 
* jQuery added to app/assets/javascripts/application.js
* It works but I'm too noobie to write a test for it
* Fixes #530

adds jQuery to close popups

---

app/models/pregnancy.rb
app/views/pregnancies/_pledge.html.erb
test/integration/update_patient_info_test.rb
test/models/pregnancy_test.rb

Pushes @MiroFurtado 's great work in #483 over the line. Thanks bud!
* Adds internal DCAF pledge identifier to pledge form
* Fixes #459

Add patient identifier to pledge form

---

app/assets/stylesheets/pregnancies.scss
app/views/pregnancies/_pledge.html.erb

I think this had to do with Bootstrap. When you clicked the "modal" class it would close by default.
So I added another div that covered the "modal" div - blocking the user from clicking it.
Fixes #506

Modal fix issue 506

---

app/controllers/pregnancies_controller.rb
app/models/pregnancy.rb
app/views/pregnancies/_patient_information.html.erb
test/factories/pregnancy.rb

This adds a `Spanish Only` checkbox to the patient information area.
* Changes the `language` field in the Pregnancy model to `spanish` and makes the field a boolean;
* adds `spanish` to the strong params in the pregnancies_controller
* adds a checkbox to app/views/pregnancies/_patient_information.html.erb
* Fixes #455

Spanishcheckbox

---

Gemfile
Gemfile.lock
app/controllers/pregnancies_controller.rb
app/helpers/dashboards_helper.rb
app/models/pregnancy.rb
app/views/calls/_new_call.html.erb
app/views/pregnancies/_new_pregnancy.html.erb
app/views/pregnancies/_patient_information.html.erb
test/helpers/dashboards_helper_test.rb
test/integration/update_patient_info_test.rb
test/integration/voicemail_preference_in_call_modal_test.rb

This remixes voicemail preferences to be one of three instead of yes/no, and adjusts the call modal to have different text based on the setting. (And also adds tests.)
* Changes boolean `voicemail_ok` to enum `voicemail_preference` (default of not_specified)
* Changes the new call modal to display different text (and possibly take away voicemail link) based on `voicemail_preference`
* Adds integration test for new call modal text, since it's kind of important to not screw that up
@mebates @lwaldsc @NerdyGirl537 can you review the text I wrote (below in the pictures) and stamp approved?
Pictures of the new call modals with each setting:
Picture of the voicemail …

Remix voicemail preferences

---

app/controllers/pregnancies_controller.rb
app/models/pregnancy.rb
app/views/pregnancies/_patient_information.html.erb
test/integration/update_patient_info_test.rb

Splits household size into children and adults, and adjusts tests.
* Does what it says on the label
* Fixes #224

Split household size into children and adults

---

app/models/user.rb
db/seeds.rb
test/factories/user.rb
test/integration/update_user_info_test.rb
test/models/user_test.rb

Picks up the clutch work done by @mccabe615 in #478 -- mostly just making test adjustments to his work.
This pull request makes the following changes: 
* Adds validation to require complex password (8 char min, cap letter, letter, no word 'password' or 'dcaf')
* Adjusts everything downwind of that, such as tests, seeds, etc
* Fixes #389

Finish complex password requirement

---

circle.yml

As part of the build succeeding, this precompiles assets and then pushes that. Should solve the problem of bootstrap-sass using absolute urls when compiling assets, thus leading to cross site requests to the staging environment in production, thus...
* Precompiles assets on job success, then pushes to heroku staging
* Fixes #508 (I hope)

add assets precompile to circle build deployment

---

test/integration/logging_calls_test.rb
test/integration/update_patient_info_test.rb
test/test_helper.rb

Finally googled the magic words - adds a method to wait for ajax calls to complete before moving on.
* Adds a `wait_for_ajax` method to the test helper
* Some edits to integration tests that screw up all the time
* Fixes #446

Wait for ajax in integration tests

---

Rakefile
app/models/call.rb
app/models/pregnancy.rb
app/models/user.rb
test/integration/submit_pledge_test.rb
test/models/pregnancy_test.rb
test/models/user_test.rb

* create a clear_call_list method on User
* create a clear_call_lists rake task
* create a STATUSES hash on Pregnancy
It relates to the following issue #s:
* Bumps #118
Worth noting: right now recent calls are those made within the last 8 hours. If we want to run this task at 4am, we may want to make some adjustments

rake task for clearing call list

---

app/models/pregnancy.rb
test/models/pregnancy_test.rb

Turns line into an enum. In effect, this hardcodes everyone into the DC line for the time being.
* does what it says on the label
* Fixes #578

Makes Pregnancy#line an enum

---

app/controllers/dashboards_controller.rb
app/models/patient.rb
db/seeds.rb
test/models/pregnancy_test.rb

TLDR: Patient-has-many-pregnancies as a way of keeping track of patients who come back is much more of a huge pain than it's worth, so this punts on a whole class of validation and data storage problems in favor of simplicity. We can fix any reporting duplication with group bys, like god intended.
We should take advantage of this in a few other ways, like changing the has to an embed and fixing the routing, in a separate PR. 
BIG s/o to my dog integration tests for confirming that everything still works after this change!
* Converts `Patient has many pregnancies` into a `patient has one pregnancy` 
* Fixes tests and seedfile
* …

Single pregnancy

---

app/controllers/patients_controller.rb
app/models/patient.rb
app/views/patients/_abortion_information.html.erb

Jenn identified an issue where when updating clinic names, the patient name would be set to the name of the clinic but the clinic won't update
Problem is that on the second submit and submits thereafter, clinic id is getting passed into the primary payload which is in turn making rails think it needs to set other stuff. I think. 
Whipping up a WIP to keep notes in

WIP fix name params for clinic

---

app/views/calls/_new_call.html.erb
app/views/pregnancies/_call_log.html.erb

This adds notes to the call modal. It also adds the call modal to the Call Log partial BUT the notes are not rendering here. They ARE rendering when you access the call modal from the Dashboard. 
* Relates to #526

Call log notes

---

app/mailers/user_mailer.rb
config/initializers/devise.rb
test/mailers/user_mailer_test.rb

change defaults "from"
* devise.rb
* user_mailer.rb
* Fixes #607

change default mail from addresses

---

app/controllers/patients_controller.rb

As suggested by @Kevin-Wei:
“update the flash msg to use the .errors hash in the create action on the patient's controller”
* Fixes #605

Include .errors hash in flash msg

---

app/models/patient.rb
db/seeds.rb

Fixes an issue that was causing `Patient.trim_urgent_patients` (and thus the rake `nightly_cleanup` task) to choke. 
* Strips a `find_each` from `Patient.trim_urgent_patients`
* Adds an example case of someone who's getting removed from the call list with the rake task to seedfile
* Fixes #609

prevent cleanup task from choking on find each

---

app/models/patient.rb
test/models/patient_test.rb

First time looking at this awesome project. Please let me know if there is anything I should do differently!
No longer considers a patient urgent is they are marked as resolved without dcaf or if a pledge is sent. 
* In `Patient#still_urgent?` method, returns false if `Pregnancy#resolved_without_dcaf` or `Pregnancy#pledge_sent` is true
* Added tests for the patient model to test the `still_urgent?` method. 
* fixes #655

Mark Patient Not Urgent if Resolved or Pledge Sent

---

app/models/patient.rb

Investigate MongoDB indexing #645
* add indices to patient
* run rake db:mongoid:create_indexes
Fixes #645

add db indices to patient model

---

app/assets/stylesheets/application.css.scss
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/models/user.rb
app/views/layouts/_navigation_links.html.erb
app/views/users/new.html.erb
config/routes.rb
test/controllers/users_controller_test.rb
test/integration/create_user_test.rb

Allows admins to create new users.
* Changes the `User#role` to `enum`. I don't know if the current `role` is being utilized at all so I wasn't sure if creating a data migration task was necessary to populate the enum value. 
* Added a 'Created User' link to the Navigation Links only visible to admins
* Created a new user form. It was suggested to do it with Devise. After some research it seems like to me Devise doesn't handle this well since it is designed for people to create their own accounts.
* It was also suggested to use Pundit to ensure only admins can create users. It seemed simpler and just as effective to simply check if the `current_user` is an admin in …

Admin Create New Users

---

lib/tasks/user.rake

I created a rake task for updating User role data from String to Integer. In order to change the role field totally you just need to run the rake task first which is `rake user:update_role` then after that change the field role type to Integer.
* User model role field data
* Fixes #533

Create a rake task for updating user role data from string to integer

---

app/views/dashboards/_table_content.html.erb
test/integration/dashboard_test.rb

* Add appointment date information to dashboard: call list, completed calls and urgent cases.
(with integration test)
* #629

Add PT's appointment date in the dashboard information

---

app/models/user.rb
test/models/user_test.rb

Clears user's call list if they don't sign in for _2 weeks_
* Adds constant `TIME_BEFORE_INACTIVE` to `User` model
* Inside `User#clear_call_list` clears patient list if `User#last_sign_in_at` is 2 weeks or longer
* Test new code in the user model test file
* Fixes #666

Clear Call List After No Login

---

app/controllers/application_controller.rb

Piggybacks off @mccabe615 's work in #672 -- pretty much identical except for adding a DCAF-specific reporting URI. 
Env var additions are reflected in heroku. See #672 for a deeper explanation.

Turn content security policy reporting uri into an env var

---

app/controllers/application_controller.rb

This PR adds content security policy (CSP). CSP is a powerful standard that limits what content will be allowed in the browser by a policy sent in a HTTP header. The purpose is to prevent content injection such as cross-site scripting. CSP will prevent execution of injection content. The current policy is in report only mode which will not block content but report it to a collector.
You can read more here: https://content-security-policy.com/
Breakdown of the policy:
"default-src 'self';  - **set the default policy as self only. allows content/media from hosting domain**
script-src 'self' www.google-analytics.com 'sha256-1kYydMhZjhS1eCkHYjBthAOfULylJjbss3YE6S2CGLc=' 'unsafe-eval'; - **allows javascript from …

Add Content Security Policy

---

app/controllers/users_controller.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/views/user_mailer/account_created.html.erb
app/views/user_mailer/account_created.text.erb
app/views/users/new.html.erb
test/integration/create_user_test.rb

Triggers an email on account create, adds some very dry and very stock templates, and programmatically generates a scrambled password so we aren't emailing around passwords.
No issues or significant view changes.

Email on user create; no password entry in form

---

app/controllers/dashboards_controller.rb
app/views/dashboards/lineselect.html.erb
config/routes.rb
test/controllers/dashboards_controller_test.rb

Added a rough line select view, route & associated test as spelled out in issue #683. It probably needs a pass from an actual frontend developer. :smile_cat: 
* adds the line select view & route
* adds a test for that route
* Bumps #683

Line Select View Draft

---

app/views/dashboards/search.js.erb
app/views/patients/_new_patient.html.erb
test/integration/record_lookup_test.rb

New patient partial should display as the result of a search regardless of whether it returns results
* changes in `dashboard/search.js.erb` to display partial regardless to search results
* added test case to this change in `integration/record_lookup_test.rb`
* changes of search results page text in `_new_patient_html.erb`
It relates to the following issue #s: bumps #675 
Fixes #702

enabled patient partial regaradless to search results

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/helpers/calls_helper.rb
app/views/calls/_new_call.html.erb
app/views/calls/create.js.erb
app/views/patients/_call_log.html.erb
app/views/users/refresh_patients.js.erb
test/integration/record_call_test.rb

Added ajax partial rendering for call lists. I think it would be nice for CMs to have instant feedback on their calling actions. It works for ALL calling actions other than "I reached the patient." Reaching the patient triggers a redirect.
Also fixes a bug where urgent patients list is completely wiped when one REMOVES a call.
You can test it on edit patient page > call log > record a call
And removing calls/calling actions on home page.
I will add functional tests in the future, but I am not familiar with minitests so it will take some time.
- AJAX partial rendering
- Fixes urgent patients bug on CALL REMOVE
fixes #704

Add Dynamic Call Lists

---

.dockerignore
Dockerfile
Gemfile
Gemfile.lock

* Adds `tzinfo-data` gem to make `docker-compose run web` not choke on a timezone error
* Includes everything in #724 
@DarthHater @mchelen can you all take a look and confirm this is cool? This seemed like the least painful solution to the problem (other stuff involves stackoverflow or docker repo arguments over what wild workaround is the least unobtrusive).

Add tzdata-info to run rails server in docker

---

.dockerignore
Dockerfile

Sooooo this switches the Dockerfile from rails (deprecated) to ruby, also switches to using alpine from debian, and trims down ruby quite a bit. End result is the image is half the previous size, should run faster, etc... This PR would supercede #720 #722 and #723  
Testing looked ok to me, someone with much more knowledge of the ecosystem should definitely examine since it's an OS change, etc...
* Switches to ruby:3.2.1-alpine for base image
* Rejumbling of packages installed
* Switches to using a dcaf user ( consistent with #722 )
* Adds an expose for port 3000
* Adds dockerignore file 
* Fixes #721

Migrate from rails to ruby Dockerfile

---

README.md
docker-compose.yml

- use docker hub automated build 
- create an automated build on docker hub
- point the `docker-compose.yml` file to use the built container
- update readme to deprecate `build` step
- Fixes #491
You still need to create an automated build that points to this repo `colinxfleming/dcaf_case_management` so any updates will be automatically included in the built container: https://www.brianchristner.io/how-to-automate-docker-builds-end-to-end/ (just the first part "Create an Automated Build Docker Repository")
Then change the container name in `docker-compose.yml` and voila!

use automated build container image

---

app/assets/javascripts/patients.coffee
app/assets/stylesheets/patients.scss
app/helpers/patients_helper.rb
app/views/patients/_abortion_information.html.erb

This changes the `_abortion_info.html.erb` partial to look like the changes recommended in #747
changes the view to look like the one #747 by reposissioning the input fields and adding a button to add other pledge sources
clicking on the add other button after selecting a field will add another input field with the name corresponding to the selection 
Issues:
* The user can continuously add input fields even the same ones over and over. There are no checks to see which input fields have been generated thus far
*  The html looks correct but it needs to be properly wired to the back end so that the values are being routed to the correct controllers, methods, params …

[WIP] change the view to accept multiple pledges #747

---

app/helpers/lines_helper.rb
app/models/clinic.rb
app/models/patient.rb
app/views/layouts/_navigation.html.erb
app/views/layouts/application.html.erb
test/helpers/lines_helper_test.rb
test/integration/routing_test.rb
test/integration/select_line_test.rb

* Changes the app name and title to DARIA, per CM corps consensus
* Makes a note that we haven't implemented the clinic model
* Edits the call line display to clarify 'your current call line' rather than just 'line', which didn't specify a user's session or the patient they were looking at
* Indexes Patient on line
* Fixes #719 
* Fixes #2 
* nudges #766

Retitle to DARIA; cleaner line display, note about unimplemented clinic model

---

README.md

I rule and have completed some work on Case Manager that's ready for review! Now the readme will take people interested in joining Slack directly to the page where they can do that.
* `README.md` links directly to the the page on codefordc.org where people can join Slack.

link directly to the /joinslack page

---

civic.json

Bumps the `civic.json` to reflect that we're in prod now. 
* Fixes ##782

update civic json to reflect prod status

---

app/views/patients/_fulfillment.html.erb
app/views/patients/_menu.html.erb
app/views/patients/_pledge_fulfillment.html.erb
app/views/patients/edit.html.erb
test/integration/pledge_fulfillment_test.rb

* render fulfillment partial if admin and pledge has been sent
* show link if admin and make link clickable after pledge has been sent
* create fulfillment form hooked up to model
* create integration test to verify when link shows and when it becomes clickable
Issues
* check weeks along field: is it showing the correct data?
* abortion care $ field: they need to enter an integer, not a string with "$", is this clear?
* boolean checkbox label: this is supposed to be bold by default 
* the disabled link is not lining up with the other links
* currently using date_field because datepicker wasn't working. I'm not sure how to override the defaults and it might be easier to get datepicker working, if you want it exactly like in the mockup. …

ACCOUNTANT: Add Fulfillment section to Patient edit view #731

---

db/seeds.rb

* Makes `test@test.com` an admin user
* Makes it so you can't accidentally run `rake db:seed` in the production, livefire db (I didn't do this, but live in constant fear that I might accidentally someday)
Have tested and it works to my satisfaction. I'll leave this hanging for today in case anyone has any thoughts.

Seedfile improvements - admin user, safety check

---

README.md
config/initializers/devise.rb

Small tweaks to change the ENV variables from #796 and #802 to be namespaced
* Updates env variables in devise.rb
* Updates README.md to new variable names

Quick tweaks to namespace the ENV variables

---

Dockerfile

Simply stated, the ENV variables in the Dockerfile can benefit from being build time ARG instead. No reason to persist them as the application does not need them post build. Also allows someone to override them (if need be) via the docker build command. 
* Switches ENV to ARG in Dockerfile, single lines them (no multiline for ARG it appears)

Small change from ENV to ARG since these values are all build time

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/calls.scss
app/views/patients/_call_log.html.erb

Three simple fixes:
1. Additional padding on section header.
2. Adding classes to "Record new call" link to pull it right, ensure font height.
3. Removing call glyphicon.  
The view should now look like this:
fixes #667

Issue 667-Pulling Record New Call link right

---

Gemfile
Gemfile.lock

A gem we have, `quality`, is making setup of everything a royal pain in the behind because of a bunch of extra style things it has built into it (for stuff like scala, markdown, python, etc.) This PR gets it to chill out so that people installing from scratch don't have to go on a goose chase.
Also bumps the rake version in the gemfile since THAT is being rude too.
* Hardsets quality to version 20.1.0
* Bumps the rake version since that's crying when you try to run `rake` anything
Note to self not to merge until after the current outstanding set of PRs gets all resolved.

Tell quality gem to chill out

---

.dockerignore
README.md
docs/GOOGLE_SIGN_ON_SETUP.md
docs/README.md
docs/SETUP.md

per the wise advice of @stvnrlly and @DarthHater  and @Kevin-Wei and @lomky , this starts the process of breaking the readme out into a docs directory where we can start sticking some of the director's cut stuff.
* Extracts advanced setup
* Some general readme grooming and updating
* Fixes #813

Breaks out detailed readme stuff into docs directory

---

README.md
civic.json

Due to changes in #829 we've got a new sandbox URL with a LetsEncrypt SSL certificate. Those changes are deployed in staging; this makes associated changes to the readme and civic to reflect the new domain of the sandbox env.

change sandbox url

---

app/assets/stylesheets/application.css.scss

Jumps off @AlexandraCasser 's great CSS work in #843 -- mostly just removing some global styles and setting a darker shade of blue.
This pull request makes the following changes, all implemented by @AlexandraCasser :
* Underline links on hover
* Navy blue after visited
* Fixes #783

Adjust visited links color

---

app/views/patients/_patient_information.html.erb

* Adds helper text underneath income field on patient edit form 
* Fixes #460

Added helper text to income field on patient edit form

---

app/views/devise/shared/_links.html.erb

Just removes the redundant link for signing in with Google.
* Comment out loop in app/views/devise/shared/_links.html.erb. Left in code in case more options are added in the future and it becomes useful for some reason.
* Fixes #819

Remove second Login with Google link

---

app/models/user.rb
app/views/patients/_menu.html.erb
app/views/patients/edit.html.erb
test/integration/create_user_test.rb
test/integration/pledge_fulfillment_test.rb

This allows for data volunteer users to be created. 
* Thus far all implementation details are in #855 minus a typo (added enum to users not patients)
* Fixes #855

Initial changes to support data volunteers

---

Gemfile
Gemfile.lock
config/environments/production.rb

This is the start of changes to hopefully use lets-encrypt for FrEe SsL!!111!
* Adds gem (github reference, YIKES) for heroku API
* Adds lets-encrypt heroku gem
* Middleware mods for production
What's left to be done?
* Lots of environment variables, I think based on the documentation. Best to try this all out on staging with a dry run of the code. https://github.com/pixielabs/letsencrypt-rails-heroku/blob/master/README.md#configuring
* Heroku configuration: https://github.com/pixielabs/letsencrypt-rails-heroku/blob/master/README.md#creating-a-heroku-token
* First time use: https://github.com/pixielabs/letsencrypt-rails-heroku/blob/master/README.md#using-for-the-first …

Initial prop up of lets-encrypt changes

---

db/seeds.rb

When poking around at Date formats, I noticed my `rake db:seed` was failing to find a patient after their name was updated, implying the update failed silently. Upon examining the `db/seeds.rb` file, I found the `create` and `update` methods are often called without a following `!`. When running in `rake db:seed`, you need to call `create!` or `update!` for any failure to happen loudly,
* `db/seeds.rb` all `create` calls are now `create!`
* `db/seeds.rb` all `update` calls are now `update!`
* `db/seeds.rb` test `Add example of patient with a pledge submitted` now functional
* `Patient`s are required to have a `clinic_name` and `appointment_date` prior to pledge …

Fix db/seeds.rb to fail loudly on DB errors

---

Dockerfile

Adds git as a build dependency so that bundler can install packages on git repositories 
* Minor tweaks to Dockerfile, adds dependencies
* Fixes #861

Fix Docker build by adding git

---

test/integration/table_content_test.rb

When running the test suite, I noticed that it started flaking after 4:00 p.m. PST. It appears to be how the display_date method was called in the test suite - it converted it out of UTC time. I changed it to use .strftime, so it should work correctly at any time now.
I didn't see an issue for this, just noticed it while running the test suite.

Test fluke after 4:00 Pacific time - fixed date display

---

app/views/dashboards/_table_content.html.erb

Break plus sign icon for notes expander into its own column to fix alignment issue
e know what to look for!)
* https://github.com/colinxfleming/dcaf_case_management/issues/448

Issue #448 - move notes expander to own column for alignment

---

app/views/patients/_patient_information.html.erb

Removes Undocumented as an option from app
* Removes option from frontend in `app/views/patients/_patient_information.html.erb`
To remove references to "Undocumented":
* `rails console`
- `Patient.all.pull(special_circumstances: "Undocumented")`
* Fixes #834

Remove Undocumented from view

---

.github/ISSUE_TEMPLATE
README.md
docs/GOOGLE_SIGN_ON_SETUP.md
docs/SETUP.md

Two improvements here:
* Per suggestion from the very wise @lomky , changes the 'should' to 'could' in the issue template
* Per suggestion from the very wise @ashlynnpai , moves all the setup instructions to one place
* Fixes #875

Tidy issue template, shift setup instructions into one place

---

app/helpers/notes_helper.rb
app/helpers/pledges_helper.rb
app/helpers/welcome_message_helper.rb
app/views/devise/sessions/new.html.erb
app/views/patients/_menu.html.erb
test/helpers/pledges_helper_test.rb

Moves a bunch of stuff we were generating with HTML safe into content tags.
* Does what it says on the label
* Removes the cat picture from the welcome messages, since placekitten is busted
* Fixes #885

Remove HTML safes

---

Gemfile
Gemfile.lock
app/models/patient.rb
test/integration/call_list_test.rb
test/models/patient_test.rb

This adds a limit to the number of patient search results being returned.
-> adds a limit and ability to sort the search results coming back.
* Fixes #845 
Notes:
I didn't know how to deal with the fact updated_at can't be accessed directly in mongo, so if you've got a better way to test the sorting, please let me know!
Staring at the current search functionality, I opted to not try and figure out how to make it AREL-y, since the two different main functions at play find_name_matches and find_phone_matches, aren't either.

[#845] limit patient results returned

---

CODE_OF_CONDUCT.md

As we discussed in Slack, we don't have a Code of Conduct in our project and think it's a darn nice idea to have one!
- created the template of the Contributor Covenant
- inserted Colin's email as PoC
To be done before merge:
- chat about any extensions needed for our specific cause
- establish how we should respond to any reports, as the [source advises](http://contributor-covenant.org/#enforcement)
No issue.
@colinxfleming I'm not sure who all to tag in for a conversation, but I trust you do :smile:

Integrate a Code of Conduct

---

app/views/patients/_fulfillment.html.erb
app/views/patients/_patient_dashboard.html.erb
app/views/patients/data_entry.html.erb

I removed the calendar icon from all date picker fields, even though the issue only mentioned the appointment date field. I couldn't figure out where the data_entry template is used (maybe it's not used anymore?), but it should work.
* Fixes #660

Remove calendar icon from datepicker fields

---

app/controllers/patients_controller.rb
app/models/pregnancy.rb
app/views/patients/_abortion_information.html.erb
test/integration/update_patient_info_test.rb

This PR adds referred_to_clinic field to track referrals :white_check_mark:
* Adds `referred_to_clinic` boolean to Pregnancy model & strong params on PatientsController
* Adds a "Referred to clinic" checkbox to the Clinic Details section of Abortion Information
* Tests that the checkbox works! Also fixes the test for the "Resolved without assistance from DCAF" checkbox, which was incorrectly passing.
Here's what it looks like:
* Fixes #897

Add referred_to_clinic field to track referrals

---

app/views/patients/_fulfillment.html.erb
test/integration/pledge_fulfillment_test.rb

* Adds clinic name & DCAF soft pledge to the pledge fulfillment form for less short-term memory exhaustion when processing pledge fulfillment forms. :thinking: 
Here's what it looks like:
* Fixes #905

Add clinic & DCAF pledge amount to Pledge Fulfillment page

---

app/assets/javascripts/patients.coffee
app/views/external_pledges/_edit.html.erb
app/views/external_pledges/_new.html.erb
app/views/patients/_abortion_information.html.erb

* Calculation functions for the Abortion Information - Cost Details page
* Shows outstanding balance calculating the difference between abortion cost and patient contribution + organizational pledges
* Updated field types in Cost Details section to number (prevents letters and typos!)
* Only displays outstanding balance section if Abortion Cost is entered
* Outstanding is updated in the same way database updates happen (on focus out or enter)
* Aims to recalculate outstanding balance if a new source is added
* Fixes #632

Calculate outstanding balances for abortion costs

---

app/controllers/calls_controller.rb
app/views/calls/destroy.js.erb
app/views/patients/_call_log.html.erb
config/routes.rb
test/controllers/calls_controller_test.rb

Add a destroy endpoint to calls controller. 
Add delete button to calls in call log that's created recently by the current user.
* Fixes https://github.com/colinxfleming/dcaf_case_management/issues/524
@colinxfleming sending this your way while I write some tests and hopefully find a way to get the tests running locally.

Allow a user to remove their own calls

---

app/views/patients/_fulfillment.html.erb

The fulfillment form has fields in a certain order that weren't matched
on the web site. This updates the web site to match the fulfillment form
order.
Fixes issue #907.
* Reorder fields as I understand they should be

Reorder fields to match form

---

app/assets/javascripts/clinics.coffee
app/assets/stylesheets/application.css.scss
app/controllers/clinics_controller.rb
app/models/clinic.rb
app/views/clinics/index.html.erb
app/views/clinics/new.html.erb

* Expand Clinic model to prepare for integration with Clinic Finder gem
Includes new fields:
- Phone
- Accepts Naf
- Gestation Limit
- Costs 9wks - 30wks
* New fields reflected when adding a new clinic
* Details reflected in the list of clinics
* Added collapsible details to existing clinic list
Add new clinic view updated:
Clinic Lists with Details Collapsed:
Clinic Lists with Details Expanded:
* Fixes #146

Expand Clinic model fields

---

db/seeds.rb
test/controllers/clinics_controller_test.rb
test/factories/clinic.rb
test/models/clinic_test.rb

It looks like `Clinic#address` is `Clinic#street_address` as of 73339ad6, so this updates the database seeds to match.

Fix Clinic db seeds following 73339ad6

---

app/assets/stylesheets/pregnancies.scss
app/helpers/pledges_helper.rb
app/views/patients/_menu.html.erb
app/views/patients/_pledge.html.erb

Previously you could 'cancel' a pledge by re-performing the 'submit
pledge' flow and unchecking the box. This PR updates the button text and
modal dialog text to make it more clear how to perform this process.
Fixes #457.
* Replace 'submit pledge' button with 'cancel pledge' when a pledge has been sent
* When 'cancel pledge' is clicked, show modal that allows cancelling pledge
Modal page 1:
Modal page 2:

Improve cancel pledge flow

---

test/test_helper.rb

Resetting Capybara sessions before every integration test fixes this flakey failure for me:
```
Capybara::ElementNotFound:         Capybara::ElementNotFound: Unable to find field "Email"
test/test_helper.rb:50:in `log_in'
test/test_helper.rb:44:in `log_in_as'
test/integration/pledge_fulfillment_test.rb:22:in `block (2 levels) in <class:PledgeFulfillmentTest>'
```

Reset session before each integration test

---

app/helpers/welcome_message_helper.rb

Another welcome message!
Part of #884

Another welcome message!

---

README.md
docs/TECH_STACK_INTRO.md

This PR adds documentation about the tech stack and resources about it, and more links to existing resources about DCAF itself.
* Fixes #815
(It also secretly removes the "4" from Rails 4 on the readme, since one of these days we'll upgrade to 5 and now it won't be a lie.)

Add tech stack / domain intro & link to it from the README

---

README.md
docs/YOUR_FIRST_CONTRIBUTION.md

I feel like we've gotten a lot of benefits out of asking people to leave our CMs nice notes per #884, so this PR makes a few changes to flag it as a part of the getting started process. 
* Suggests that new people's first contributions be making a PR against #884 
* Updates the Baltimore rollout date to June
* Fixes #946

Add instructions for making a first contribution

---

app/assets/javascripts/patients.coffee
app/assets/stylesheets/patients.scss
app/helpers/patients_helper.rb
app/views/patients/_abortion_information.html.erb

* Added support for tooltip help thingys next to form field labels
* Added a tooltip next to the DCAF Pledge field that shows recommended pledge limits
* Fixes #793

Add tooltip support next to form field labels

---

docs/SETUP.md

Added fetch-only setup direction!
* Setup doc line
No issue.

Adding fetch-only upstream instruction

---

Gemfile
Gemfile.lock

Turbolinks is the devil.
* Reverts turbolinks to 2.5.3 to get all our js to work again
* Fixes #968

turbolinks is the devil

---

app/models/clinic.rb
app/views/clinics/_clinic_form.html
test/models/clinic_test.rb

Hotfixes an issue that was allowing duplicate clinics. Also adds fax number.
* Require uniqueness on name for clinics
* Add fax
No issue #

Enforce uniqueness on Clinic#name

---

app/helpers/status_helper.rb
test/helpers/status_helper_test.rb

There's an edge case where a PT calls in and leaves a voicemail
indicating they have an appointment date. If we then set the appointment
date in the system, the status would have been 'Fundraising' but in
reality we would prefer it to say 'No Contact Made'.
This fix adjusts the priority of the statuses slightly that No Contact
Made will come up if we haven't talked to a user yet, regardless of
their appointment status.
Fixes issue #676.
* Adjust status helper as above
* Adjust tests to test new behavior
* Fixes #676

Adjust status helper for rare scenario

---

docs/PRESS.md

Started a doc to track positive coverage of our project in the press!
* created `docs/PRESS.md` with entries for the coverage following the hackathon
No issue.

Highlight Project Press Coverage

---

app/assets/stylesheets/application.css.scss
app/views/layouts/_navigation_links.html.erb

Changed the styling on the navbar navigation "Your line:" item to reflect that it is not a link.
* Change navbar list item in app/views/layouts/_navigation_links.html.erb from a blank link to static text
* Change navbar list item class in _navigation_links to navbar-text to reflect the previous change
* Change app/assets/stylesheets/application.css.scss. Change .navbar-inverse .navbar-text style to fit existing navbar item styling.
Before:
After:
* Fixes "Your current line: DC" shouldn't be a link. Fixes #980

Remove link styling on non-link navbar item

---

Gemfile
Gemfile.lock
circle.yml
test/controllers/notes_controller_test.rb

Remove parallelization until we get that sorted out in #992 , remove `rails-controller-testing` gem
* Fixes #991

unparallelize, remove controller testing gem

---

app/controllers/patients_controller.rb
app/helpers/patients_helper.rb
app/models/clinic.rb
app/models/patient.rb
app/models/pregnancy.rb
app/views/patients/_abortion_information.html.erb
app/views/patients/_fulfillment.html.erb
app/views/patients/data_entry.html.erb
db/seeds.rb
test/controllers/patients_controller_test.rb
test/factories/clinic.rb
test/integration/data_entry_test.rb
test/integration/display_pledge_info_errors_test.rb
test/integration/pledge_fulfillment_test.rb
test/integration/submit_pledge_test.rb
test/integration/update_patient_info_test.rb
test/lib/reporting/patient_test.rb
test/models/pregnancy_test.rb

This takes remaining steps to move us away from clinics as defined by environment variables into clinics as defined by a model.
Turns out there are a lot of moving parts in those env vars.
<strike>TODO: null out clinic, fix tests</strike> (donezo!)
* Depreciates patient#clinic_name
* bumps seedfile
* establishes `clinic has_many patients` / `patient belongs_to clinic` relations
* adjusts a ton of stuff in support of that
No view changes, I hope!
* Fixes #973 
(s/o to past us for writing good tests)

Move clinics away from env vars to model

---

app/assets/javascripts/application.js
app/controllers/application_controller.rb
vendor/assets/javascripts/google_analytics.js

I rule and have completed some work on Google Analytics that's ready for review!
Removed Google analytics from the the Assets, vendor assets and the CSRF
* /app/assets/javascripts/application.js (removes require google_analytics)
* removes the 'script src' line from the CSRF
* removes vendor/assets/javascripts/google_analytics
* Fixes Remove google analytics #997

Remove Google Analytics from vendor, CRSF and assets

---

app/models/concerns/attribute_displayable.rb
app/models/concerns/callable.rb
app/models/concerns/history_trackable.rb
app/models/concerns/notetakeable.rb
app/models/concerns/searchable.rb
app/models/concerns/urgency.rb
app/models/patient.rb

The patient object was getting a little massive. 300 line models is no way to live.
This begins the process in #948 by moving relevant sets of methods into their own concerns.
* Breaks patient object into a core, plus Urgency, Callable, Notetakeable, Searchable, and AttributeDisplayable concerns
@lomky seeking your thoughts on the patterns here -- does dividing things up this way and the names I picked make sense to you? Anything else I should extract?

Move patient methods to concerns

---

README.md
civic.json
docs/SETUP.md
docs/TECH_STACK_INTRO.md
docs/YOUR_FIRST_CONTRIBUTION.md

This updates our GH references to DCAFEngineering instead of colinxfleming where it makes current sense.
* Lots of doc changes
* Fixes #1006

Update cxf to DCAFEngineering as many places as makes current sense

---

config/initializers/new_framework_defaults.rb

This makes the configuration changes described in #989.
The basic manual functional tests described in the #989 continue to work fine, and all automated tests pass except a few Capybara ones which I think are related to #903. 
* Enable `per_form_csrf_tokens`
* Enable `forgery_protection_origin_check`
* Implements #989

Enable enhanced CSRF protections provided by Rails 5

---

Gemfile
Gemfile.lock

Removes 12factor, no longer needed in Rails 5.
* Removes 12 factor gem
Testing for this needs to mainly be on Heroku, since it relies on ENV variables that Heroku provides. Code changes are minimal. 12 Monkeys is a good Terry Gilliam movie.
* Fixes #988

Removed 12factor, no longer needed

---

Gemfile.lock

An upstream lib of nokogiri has a vulnerability, and they've patched to fix it as a part of 1.7.2
https://github.com/sparklemotion/nokogiri/issues/1634
* Bundle update nokogiri (puts us at 1.7.2)

Update nokogiri to 1.7.2

---

app/models/patient.rb
app/views/patients/_patient_information.html.erb
test/integration/update_patient_info_test.rb

Fixes issue #1053 remove zip code field
* Remove the field from the model in `app/models/patient.rb!`
* Fixes #1053

Fixes issue #1053 remove zip code field

---

app/views/patients/_fulfillment.html.erb

* Change form fields in patients/_fulfillment partial to not autocomplete
* Fixes #838

change patients fulfillment partial to not autocomplete any forms

---

app/controllers/users_controller.rb
app/helpers/users_helper.rb
app/views/users/new.html.erb
test/helpers/users_helper_test.rb

Long overdue, this adds the ability to set another user as an admin.
* Allows an admin to set another user's role on create
Nice and simple:
No issue.
@lomky and/or @DarthHater would appreciate a review, since this has a security implication!

Enable setting user role on account creation

---

app/views/layouts/_navigation_links.html.erb
test/integration/navbar_links_test.rb

* Adds a link to the patient CSV exoprt
* Splits the admin dropdown into two blocks, `admin` and `data_volunteer`, and gives data volunteers access to reports/accounting/csv export
* adds some integration tests
* Bumps #965

Add Link to export, add data entry admin tools

---

app/models/patient.rb
config/initializers/env_var_constants.rb

It turns out that `LINES` is a reserved env var in heroku, so this moves the line setter to `DARIA_LINES`, which is thankfully NOT a reserved env var.
Requires a heroku env var change after merge.
* Changes `LINES` variable to draw from the env var `DARIA_LINES`
* Alters patient model to use `LINES` instead of hardset option
Bumps #999

Correct line handler in patients to take a correct env var

---

app/mailers/application_mailer.rb
app/mailers/user_mailer.rb
app/views/user_mailer/account_created.html.erb
app/views/user_mailer/account_created.text.erb
app/views/user_mailer/password_changed.html.erb
app/views/user_mailer/password_changed.text.erb
config/initializers/env_var_constants.rb
test/integration/update_user_info_test.rb
test/mailers/user_mailer_test.rb

Removes a couple DCAF specific mentions (domain of email from, SL of emails) in favor of either the fund in particular or DARIA, whichever is more appropriate.
* Adds an app constant, `FUND_DOMAIN`
* Changes 'DCAF' to 'DARIA' in mailer subject lines
@tingaloo can you review? 
* Bumps #999

Abstract DCAF out of the mailers

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/pregnancies.scss
app/assets/stylesheets/reports.scss

In keeping with getting dcaf-specific references out of the app as much as possible, this renames the stock color code from `dcaf-color` to `daria-color`.
* renames `dcaf-color` to `daria-color` in a few scss files
@ashlynnpai can you review and approve these changes? Want to get another set of eyes on it to confirm I didn't accidentally misspell anything or do anything goofy by accident. Thank you!
* Bumps #999

dcaf-color -> daria-color in scss

---

Gemfile.lock

Bumps rubocop to 0.49 to address a gemnasium flag.
* that thing I said
No issue #.

Bump rubocop to address gemnasium warning

---

Gemfile
Gemfile.lock
config/skylight.yml

Adds the skylight gem and config file, so we have more rails specific monitoring! I think this will help us identify where the pain points are, where loads are slow, and what keeps triggering logentries alerts.
I also added the appropriate api keys to the prod environment(s). This is free up until 100,000 requests so it's rolled out to just dcaf and baf, but not the sandbox env.
* Sets up skylight for accessible monitoring
@DarthHater I added you (and @lwaldsc and @lomky) as a collaborator to this. Can you approve these changes? I don't plan on rolling them out until this Sunday during out deployment window either way. 
* Fixes …

Add skylight monitoring

---

app/assets/javascripts/external_pledges.coffee
test/integration/submit_pledge_test.rb
test/test_helper.rb

Fix submit pledge modal, this was pushed before the turbolinks merge so that'd explain the failure of modal steps populating.
* Added turbolinks loader
* Fixes #1089

fix modal load

---

test/integration/submit_pledge_test.rb
test/test_helper.rb

This adds a failing test to address the behavior in #1089 that we can write code against. Feel free to either push code straight to this PR or branch off it.
* Adds failing test
* Makes `wait_for_ajax` a bit beefire using thoughtbot code
:|
* Fixes #1089

Add test for failing pledge modal load

---

app/helpers/calls_helper.rb

Sub in `FUND` for DCAF in the voicemail preference part of the calls helper.
* What it says on the label
@KatSDC could I get you to approve these changes?
* Bumps #999

Sub in Fund env var for DCAF in calls helper

---

app/controllers/patients_controller.rb

Patient is no longer added to call list in data entry mode.
* removed line in PatientsController#data_entry_create that automatically added patient to current user's 
call list.
* Fixes #1076

Patient no longer added to call list in data entry mode

---

app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb
test/controllers/users_controller_test.rb
test/integration/call_list_test.rb
test/integration/update_user_info_test.rb

Adapts @AlexandraCasser 's great work in #1050 , and works out an additional kink or two (the reset password link doesn't work if you are already logged in, whoops, sorry @AlexandraCasser !).
* email no longer an editable field (woo security)
* Fixes #951

User edit panel remix

---

app/views/devise/registrations/edit.html.erb

I've updated the user edit page to make the following changes: 
Email is no longer an editable field
Removed 'enter password to confirm'
Included link to `new_user_password_path'
[Issue #951](https://github.com/DCAFEngineering/dcaf_case_management/issues/951)

Email is no longer an edited field; added link to new_user_password_path

---

app/controllers/application_controller.rb
app/controllers/patients_controller.rb
app/models/user.rb
app/views/patients/_change_log.html.erb
app/views/patients/_patient_dashboard.html.erb
app/views/patients/pledge.js.erb
app/views/patients/update.js.erb
test/controllers/patients_controller_test.rb
test/integration/submit_pledge_test.rb
test/integration/update_patient_info_test.rb
test/models/user_test.rb

@tingaloo has solved a long running problem of this app in #1064 , which is that the patient edit page is not particularly responsive. I've added a little bit of business logic surrounding this. This now makes the following fields bump on a patient edit:
* status
* current LMP
* approx gestation at appt
* the change log
* cancel pledge / submit pledge button status
* whether or not the fulfillment partial shows up
There's a thing that my js skills are a little weak that I'd like to sort out -- refreshing the page makes you lose focus, so if you're tabbing from field to field on the dashboard, you lose whatever you're editing. @tingaloo do you know of a good way to stop that from happening? (Maybe by just …

Pledge reload ajax

---

app/controllers/users_controller.rb
test/integration/user_management_test.rb

Temporarily turns off role changing until we can build some precise rules around it; adjusts the user mgmt integration test so that #1106 will fly.
* Removes `_role` from `user_params`
* Makes some precision adjustments to the user management integration tests
No view changes
* No issue, but is here so we can get #1106 to fly

Slight test adjustment, no more role editing for now

---

Gemfile
Gemfile.lock
config/environments/production.rb

This allows for moving to just using Heroku's SSL stuff now that it is released
* Removes platform api dependency
* Removes letsencrypt middleware (not needed)
* Fixes #957

Back out Lets Encrypt stuffz

---

app/controllers/patients_controller.rb
app/models/concerns/exportable.rb

We're regularly getting timeout errors when trying to export files. I think this might help -- it invokes `Patient.all` once instead of twice when hitting the CSV export endpoint now.
@lomky for review please!
* just one multi thousand record query please
No issues.

only one patient retriever

---

.github/CONTRIBUTING
docs/SECURITY_INTRO.md
docs/SETUP.md

Created an intro security document for new contributors to read.
* Creates docs/SECURITY_INTRO.md
* Adds links to the security document in .github/CONTRIBUTING and docs/SETUP.md
* Fixes #994

Change intro markdown to link to security practices

---

app/assets/stylesheets/application.css.scss
app/views/patients/_abortion_information.html.erb

In the **Abortion InformationI** section, I managed to move the checkboxes to the same lines as their labels.
* label checkboxes instead of form groups
* alter the formatting for the `naf_filter` checkbox to match the other two
* add a css rule to keep the checkbox label fonts bold
* Fixes #1135

move checkboxes to same line as label

---

config/initializers/csp.rb

This adds standard shas for our common JS, a popover and the cruft the gon gem dumps in, into our CSP script-src whitelist. The main effect is that the javascript console will now not dump errors all the time.
* Adds shas for popover and gon to the CSP whitelist
* Loosely relates to #1144 #1140 
@tingaloo for approval please!

add shas for gon and popover

---

app/views/lines/new.html.erb
app/views/reports/index.html.erb
civic.json

Incremental bump toward abstracting DCAF out of the business part of the app -- removes DCAF from a few headers in favor of the `FUND` variable.
* changes a few DCAFs to `FUND`s
* completes a sentence in civic.json
* Bump to #999 
@ashlynnpai  for sign off please!

Remove DCAF references from a few places

---

test/factories/patient.rb

Super small cleanup, removes language from the patient test factory.
* Removes language from the patient test factory, since nil == english
No view changes. 
No issues.

Remove language from patient factory

---

Gemfile
Gemfile.lock

Looks like this particular gem upgrade, despite being a point release, contains a breaking change of some sort.

downgrade omniauth-google-oauth2

---

app/assets/stylesheets/application.css.scss
app/views/devise/sessions/new.html.erb
test/integration/google_sso_test.rb
test/test_helper.rb

Some very slight adjustments to @rudietuesdays excellent and thoughtful work in #1149 to point people more toward google sign in.
* favor inline bootstrap classes over css
* some adjustments for my own neuroses
* follow 'one primary button per page' rule that @mebates has instilled unto me
@mebates does this look okay? We're trying to push people toward google sign in, primarily. The main diff is that `Sign in with Google` is now the button primary, and sign in with password is just a blank white button.
* Fixes #811

More prominent Google SSO link ctd

---

app/assets/stylesheets/application.css.scss
app/views/devise/sessions/new.html.erb

* update Google SSO login link to make it more prominent and visible on the page
Screenshot:
* Fixes #811

updated Google SSO login link to be more prominent

---

app/helpers/welcome_message_helper.rb

Cool things:
Last item in list can have a comma
Rails updates automajically on save
Add another welcome message (really just copied)
* Bumps #884

Added Welcome message

---

Dockerfile

Switches the Docker image back to using root. We don't have plans to use Docker in production, switching user is kinda cool but causing too much pain at the moment.
* DOCKERRRRRRR

Switch back to ROOOOOT (beer)

---

app/views/reports/_patient_report.html.erb

facepalm.gif. SORRY EVERYONE this massive dumb odyssey is my screwup.
* Adds a nonce to the js
* Literally nothing else
It works in sandbox!
Tagging in @tingaloo and @lapolonio for approval.
* Fixes #1009

Add nonce to js to display reports... for real

---

app/models/user.rb
app/views/dashboards/_table_content.html.erb

Jumps off @tingaloo 's sharp work in #1081 to eliminate an n+1 query.
Turns out we were both wrong! This wound up being a check in the view, which was way, way under. It was not my first, third, or fifth inclination, but I eventually traced it down to that, and it turns out that single check using the full `patients` set instead of `patient_ids` was causing our n+1 by re-getting `patients` over and over and over, instead of just checking the reference numbers.
looking back, could have probably guessed this -- this is the same thing that @rivers (hi! hope all is well back west 👋 ) fixed in #914 on a different model. But this was nested a little deeper, unfortunately, so it was pretty difficult to dig up. 
The more …

Fix dashboard n+1 queries

---

config/puma.rb

Reducing puma workers to 2 to see what effect it has on heroku R14 errors we're getting. See #998 
* Reduces puma workers from 3 to 2
* Bumps #998

decrease puma workers to see if it fixes those r14 errors

---

app/assets/stylesheets/application.css.scss
app/views/layouts/_messages.html.erb

Notifications no longer bump form up and down yeah? Also added opacity effect when hovered.
* Notifications boop
* Fixes #1210

Plop Notifications as Absolute

---

app/controllers/patients_controller.rb
app/models/audit_trail.rb
app/models/concerns/attribute_displayable.rb
app/models/concerns/history_trackable.rb
app/models/patient.rb
app/views/dashboards/_table_content.html.erb
app/views/patients/_fulfillment.html.erb
app/views/patients/_patient_dashboard.html.erb
app/views/patients/_pledge.html.erb
app/views/patients/data_entry.html.erb
config/initializers/time.rb
db/seeds.rb
test/controllers/patients_controller_test.rb
test/integration/data_entry_test.rb
test/integration/filter_medicaid_clinics_test.rb
test/integration/table_content_test.rb
test/integration/update_patient_info_test.rb
test/models/audit_trail_test.rb

Test adjustments for the world's worst integration test failures. Poltergeist's driver has an interesting interpretation of `input type="date"` it seems. We'll probably need to fix when we move to a diff driver in #1216 / #1191 .
* Punts on some truly awful test problems with the integration test driver
* Everything in #1088 
Stems from #1088 , where all the good stuff is.
Tagging in @tingaloo for final thumbs up. Going to merge after the scheduled deploy today. 
* Fixes #860

Date format testing adjustments

---

test/integration/update_patient_info_test.rb

Tests shoulda caught the bug fix in #1206 so I'm adding a test.
* Adds a test for #1206 
* Fixes #1199 ... FOREVER
@tingaloo can you review? I'll hold on merging this until the MM/DD/YYYY PR is in so as to not making that even more of a moving target.

Add a test for date of check

---

app/views/patients/_abortion_information.html.erb
app/views/patients/_call_log.html.erb
app/views/patients/_change_log.html.erb
app/views/patients/_fulfillment.html.erb
app/views/patients/_notes.html.erb
app/views/patients/_patient_dashboard.html.erb
app/views/patients/_patient_information.html.erb
app/views/patients/edit.html.erb

Patient update was emptying out divs with particular ids and then repopulating, causing all sorts of mess to happen. This fixes that.
* patient partials now populate inner content instead of emptying out the div and then putting in another div with the same id
No real changes to the view, just some rearranging ids. 
@tingaloo for review
* Bumps #1141 ... kinda.

View dupe bug

---

test/integration/change_log_test.rb
test/integration/create_new_external_pledge_test.rb
test/integration/create_user_test.rb
test/integration/filter_naf_clinics_test.rb
test/integration/new_patient_creation_test.rb
test/integration/pledge_fulfillment_test.rb
test/integration/update_patient_info_test.rb
test/test_helper.rb

Rails 5.1 may be a real mess of a conversion but I'm not going to let it be a complete bust. Here are some improvements to the integration tests to make them more integration test-y.
* Makes integration tests marginally better
* Bumps #1167 , in a sense

Make integration tests more integration test-y

---

app/controllers/patients_controller.rb
app/models/concerns/exportable.rb

Turns CSV generation into streaming request to avoid timeouts.
* Changes `to_csv` return enumerable (it only seemed to be called in one place)
* Turns patient csv generation into stream. Heroku won't time out on streaming requests unless it goes 55 seconds or more between packets, so this should allow for arbitrarily long CSVs (https://devcenter.heroku.com/articles/request-timeout)
* Fixes #1224

Changes to_csv to enumerable, streams CSV generation

---

app/assets/javascripts/events.coffee
app/assets/stylesheets/events.scss
app/controllers/events_controller.rb
app/helpers/events_helper.rb
app/models/call.rb
app/models/concerns/event_loggable.rb
app/models/event.rb
app/models/patient.rb
app/views/dashboards/_activity_feed.html.erb
app/views/dashboards/_activity_log.html.erb
app/views/dashboards/index.html.erb
app/views/events/_events.html.erb
app/views/events/index.js.erb
config/routes.rb
lib/tasks/nightly_cleanup.rake
test/controllers/events_controller_test.rb
test/factories/event.rb
test/integration/activity_log_test.rb
test/models/event_test.rb

Jumps off the structural work in #1136 to add a clean render stream for events as follows:
* Single serve events endpoint that renders a partial of events for that line
* Renders the activity feed async
* Refines some frontend stuff around #1136 
Screenshots coming when I get it to blend right
* Fixes #654

Shape frontend for events stream

---

app/views/dashboards/_activity_log.html.erb
app/views/layouts/application.html.erb

Turbolinks does not love inline javascript, so we had to add a tag to the JS.
And, for some dumb reason, put `render_async` in the head. Why that is is totally lost on me. I probably owe the render_async folks a readme PR after this.
* Make the activity log load when following links in the app
No issue, I think.
Going to invoke admin priv and merge so we can get this out today.

Get turbolinks working with the activity log

---

app/assets/stylesheets/lines.scss
app/views/lines/new.html.erb
test/integration/select_line_test.rb
test/test_helper.rb

* Change 'Select line for this session' to 'Start'
* Increase size of radio buttons
* Add margin between radio button and text description
Before
After:
* Fixes #779

Frontend improvements for call line selections

---

Dockerfile
Gemfile
Gemfile.lock
circle.yml
docs/SETUP.md

Bumps nokogiri and ruby for security patches.
* Nokogiri to 1.8.1 to path a libxml vulnerability
* Ruby to 2.4.2 to patch whatever the latest round of small security fixes is
No view changes, no issues. 
@lomky  or @KatSDC can you sign off on these changes when you get a sec?

Bump ruby to 2.4.2, nokogiri to 1.8.1

---

app/helpers/events_helper.rb

I did some formatting cleanup in this helper and otherwise just uncommented the previous link code.
* Re-enables add to call list link
* Fixes #1237

1237 - Reenabled add to call list link

---

app/controllers/patients_controller.rb

Adds a timestamp to the success notice in patients_controller update method.
* Modifies patients_controller #update to give a timestamp in the flash notice.
* Fixes #1179

modify flash notice in patients contoller #update to give timestamp

---

app/views/patients/_abortion_information.html.erb

On the abortion information form there are two sets of checkboxes. The set under the input field is wrapped in a checkbox class div whereas the second set to the right were wrapped in a checkbox class div within a form-group div. The margins on the nesting of those two divs was causing the inconsistency. My quick fix is to remove the encompassing form-group as the checkbox class provides better styling for the checkboxes.
* Removes two encompassing form-group divs from the `app/views/patients/_abortion_information.html.erb`
* Fixes #1248

remove an encompassing form-group that caused inconsistent spacing

---

app/services/pledge_form_generator.rb
app/views/layouts/_footer.html.erb
config/initializers/env_var_constants.rb

Per #1214 this makes it possible to set a DARIA_FUND_PHONE
* Uses an env var `DARIA_FUND_PHONE` to set a fund's phone number (defaulting to DCAF's #)
* Switches out the hardset DCAF to`DARIA_FUND_FULL` in the footer
* Bumps #1214 
@lomky for review please!

Allow fund information from env vars in footer

---

app/views/layouts/_footer.html.erb
config/initializers/env_var_constants.rb

BRAAF requested the ability to set their own fax service URL in the footer, so hooking that up for them. 
* Adds a constant `FUND_FAX_SERVICE` for use in places, defaulting to the DCAF option
* plugs it into the footer
* also makes clicking that link open in a new tab
* Bumps #1214 
@colinmcglynn  for review please!

Make fax service in the footer settable by env var

---

app/controllers/lines_controller.rb
test/integration/select_line_test.rb

Automatically selects and redirects to line if only 1 line count. Not sure how to test but it should be working.
Redirects to line if only 1 line.
* Fixes #1151

Autoselect when 1 line

---

config/environments/development.rb

related to #1266, doesn't fix it yet
It fixes email link sent in development environment to have correct port
http://localhost/... --> http://localhost:3000/...

Add port in development to fix password reset link sent to email

---

app/views/layouts/_footer.html.erb
app/views/patients/_pledge.html.erb

Was working on something unrelated and and discovered that `target='_blank'` in links is a minor security flaw. It's not really a problem for us since I don't think we're pulling in anything external, but, you know.
* Adds `rel='noreferrer nofollow'` to a pair of links
* Missed a spot on changing online faxes to an env var, fixes that as long as I'm wrenching around
No issue.
@valeriecodes could I get a review at your leisure, if you'd be so kind?

Add noopener nofollow to new tab links

---

Gemfile
Gemfile.lock
lib/tasks/factory_girl.rake
test/factories/call.rb
test/factories/clinic.rb
test/factories/config.rb
test/factories/event.rb
test/factories/external_pledge.rb
test/factories/fulfillment.rb
test/factories/note.rb
test/factories/patient.rb
test/factories/user.rb
test/test_helper.rb

I changed the `FactoryGirl` gem to `FactoryBot`, and changed all references to it.
* Change FactoryGirl to FactoryBot
* Fixes #1285

Migrating from FactoryGirl to FactoryBot

---

app/assets/javascripts/table_sorting.coffee
app/views/shared/_activate_stupidtable.js.erb
app/views/users/search.js.erb

Fix sorting by date after searching for a user.
A not so neat hack by calling the entire autosort function after a search completes. There might be a better way calling a javascript function elsewhere but I forget how to do so.
* Call autosorting table after search.js.erb dispatches
* Fixes #1099 
* Bumps #Y

Fix Tablesort after Search Bug

---

app/helpers/patients_helper.rb
test/helpers/patients_helper_test.rb
test/integration/filter_medicaid_clinics_test.rb
test/integration/filter_naf_clinics_test.rb

Some EOY reporting has made it clear that removing clinics from the roll entirely if we aren't working with them isn't a great option. So that people can still select them, this moves them to a bottom portion and marks them as inactive -- this way people doing reconciliation or fulfillments can still add them.
* Adds inactive clinics to the clinics helper
* Adds a test for said helper
Looks like so 
cc @alisonnjones @NerdyGirl537  -- can I get an approval of this strategy from you all?
* Fixes #1305

Show inactive clinics in clinic dropdown

---

app/controllers/users_controller.rb
test/system/change_log_test.rb
test/system/create_new_external_pledge_test.rb
test/system/create_user_test.rb

Moves over integration tests starting with the letter C.
* Moves over integration tests starting with the letter C.
* Bumps #1318

Port over integration tests whose names start with C

---

test/system/select_line_test.rb
test/system/submit_pledge_test.rb
test/system/table_content_test.rb

Port over integration tests beginning with S and T
* That thing I said
No view changes
* Bumps #1318

Port over integration tests beginning with the letter S and T

---

test/system/updating_configs_test.rb
test/system/urgent_cases_test.rb
test/system/user_management_test.rb
test/system/voicemail_preference_in_call_modal_test.rb

Port over system tests starting with U and V. After this, we'll remove some of the old integration test artifacts like poltergeist, phantom, etc., and rerack knapsack.
* Does what it says on the label
No view changes
* Bumps #1318

Port system tests starting with U and V

---

Rakefile
app/controllers/users_controller.rb
app/models/user.rb
app/views/dashboards/_table_content.html.erb
config/routes.rb
test/controllers/users_controller_test.rb
test/models/user_test.rb
test/system/call_list_test.rb

A couple additional things from @tingaloo 's work in #1274 --
* renames existing `clear_call_list` method to be clearer about intent, and adds a `clear_call_list` method that does what this is supposed to
* removes need for associated user id in params, running off current user... OR DOES IT??? (test failure)
UserControllerTest is currently choking, so that sucks. Not sure why and am not in a mind to fix it tonight. 
* Adds remove all patients from your call list btn
* some other assorted cleanup
TK integration test, model test.
* Fixes #1202

Remove all btn

---

Dockerfile
Gemfile
Gemfile.lock
circle.yml
docs/SETUP.md

We've got us a ruby vuln. Not an emergency since we don't do ftp though.
* Bumps ruby to ~2.5.0~ 2.4.3
No view changes. 
No issues.

ruby 2.4.2 becomes ruby 2.4.3

---

app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/helpers/users_helper.rb
app/models/concerns/user_searchable.rb
app/views/users/_users_table.html.erb
app/views/users/edit.html.erb
app/views/users/search.js.erb
config/routes.rb
test/controllers/users_controller_test.rb
test/system/call_list_test.rb
test/system/change_user_roles_test.rb
test/system/user_management_test.rb
test/system/user_searches_test.rb

Continues #1272 - Made a quick change to allow roles to be permitted on update.
* Whitelists user role so an admin can change it
* Adds a safety so admins cannot demote themselves
* Overhauls the users controller test
* Fixes #1271

Allow admins to change roles ctd

---

app/views/patients/_pledge.html.erb
app/views/patients/pledge.js.erb
test/system/submit_pledge_test.rb
test/system/update_patient_info_test.rb

Picks up changes in #1227 and resolves test failures/merge conflicts, pretty much. 
This pull request makes the following changes (copied from @SamuelLangenfeld 's):
* removes checkbox from the cancel pledge modal
* changes _pledge.html.erb to only call views/shared/multi-modal for submitting a pledge, not cancelling. Cancelling a pledge is only one step.
Fixes #1046

Cancel checkbox 2

---

app/views/patients/_pledge.html.erb
app/views/patients/pledge.js.erb

* removes checkbox from the cancel pledge modal
* changes _pledge.html.erb to only call views/shared/multi-modal for submitting a pledge, not cancelling. Cancelling a pledge is only one step.
Cancel pledge modal before:
Cancel pledge modal after:
* Fixes #1046

Cancel pledge checkbox

---

README.md
docs/SECURITY.md

It's readme bump season!
* Issue types is no longer really serving a good enough use to slap it on the front page. Takes it out
* Adds a note to security.md about defense against common internetty attack vectors
* bumps jenn to be DARIA manager
* flags that the next milestone is people using it
* Fixes #1348

Bump readme

---

Rakefile
lib/tasks/nightly_cleanup.rake

BRAF brought this to my attention in an email. This is definitely not intended behavior -- should only clear out after a two weeks have passed. SORRY EVERYONE.
* undo accidentally clearing out literally everyone's call list literally every night. sorry.
No issues.

Undo global call list nuking every night

---

app/views/layouts/_navigation.html.erb
db/seeds.rb
lib/tasks/seed_training.rake
test/integration_helper.rb

We don't set `FUND` in app.json, so we should depreciate it. This takes out all refs to it in favor of either `DARIA_FUND` or `DARIA_FUND_FULL` env vars. This should prevent us from accidentally blowing something up by accident.
* FUND -> DARIA_FUND
* Fixes #1259

Use DARIA_FUND env var instead of FUND

---

app/views/clinics/index.html.erb
test/system/clinic_management_test.rb

Clinics view used a dropdown row to show/hide additional info about a
given clinic. This UI was buggy. The dropdown row was implemented
through Bootstrap toggle and defined on a `<tr>` tag.
Bootstrap's toggle does not play well with the HTML `<table>` tag. A
workaround is possible but difficult. Instead, this commit takes the
three extra fields from the dropdown row and adds them as additional
columns within the table.
Before this commit, there were 5 columns of data and a chevron toggle
that would reveal 3 more columns of data in a dropdown row. Now
there is no chevron toggle, and the table displays 8 columns of data at
all times.
Old screen:
New screen: 
* Fixes #1353

Remove dropdown row UI

---

test/integration_helper.rb
test/test_helper.rb

Cleans up our test helper to squelch some redundancies and get the CI specific stuff in one place, instead of a few diff places.
Also, we aren't using poltergeist anymore!
* no codecov reports if not in ci
* gets all the CI stuff in one place
* removes dead reference to poltergeist
No issues.
ps:
```
$ rails test
Run options: --seed 36133
.............................................................................................................................................................................................................................................................................................................................. …
```

Organize test_helper better, remove dead ref to poltergeist

---

.rubocop.yml
Gemfile

Been meaning to do this for a little while -- this reorgs our gemfile so that for the less common libraries, it's clear what's doing what.
I'm going to see if we can take out some of the stuff in `????` sections before I merge, but keeping these here for now.
* reorganizes gemfile, adds mad comments
No issues.

Reorganize gemfile

---

app/helpers/patients_helper.rb
app/views/patients/_pledge.html.erb

BRAAF asked for two good sense tweaks as follows in #1200 
* Changes the language around the pledge flow so it doesn't tell 
* `Not currently working with DCAF` => `Not currently working with FUND` in the clinic dropdown
No real view changes.
* Bumps #1200 (want to confirm with @NerdyGirl537 before closing the issue)

Requested tweaks by BRAAF - Clinic dropdown 'not currently working with', and language around pledge flow

---

Gemfile.lock

Bumps a pair of dev dependencies (byebug and capybara), with a couple of secondary gem updates along the way.
* `bundle update byebug`
* `bundle update capybara`
No issues.

Update nokogiri, byebug, and capybara

---

config/environments/development.rb

Quick fix in development config that will let links in password reset emails work. Not production facing, so good to merge after we confirm tests all pass.
* Sets the default URL to localhost and port to 3000 when running in development mode
No views.
No issues.

Set actionmailer settings in dev

---

app/views/patients/_fulfillment.html.erb
app/views/patients/_patient_information.html.erb
app/views/patients/data_entry.html.erb

Makes text forms for age and any $ amount (eg procedure cost) use number_field instead of text_field
* Fixes #1249

use number_field instead of text_field to improve usability

---

Gemfile
Gemfile.lock

There's a security vuln in libxml2 expressed in the loofah gem etc etc. This bumps the lib to a patched version.
* gem loofah >= 2.2.1 && bundle update
No issues or view changes.

bump loofah to 2.2.1 to get a security warning to shush

---

test/integration_helper.rb
test/system/update_patient_info_test.rb

The patient update system test is causing us all sorts of consternation because it keeps failing to save phone number -- lately it's been failing about 9/10 times. This hopefully fixes it.
* adjusts the click body to click nav
* doesn't try to get too fancy with saving
No view changes, no issues.

Fix flaky patient update system test, hopefully

---

Gemfile
Gemfile.lock

`bundle update rails-html-sanitizer`
* that thing
No changes to views.
See #1397

Bump rails html sanitizer to squelch vulnerability warning

---

app/models/concerns/exportable.rb

The field for Procedure cost (what DCAF paid) was incorrectly exporting procedure_cost from the patient model instead of procedure_cost from the fulfillment model. This fixes that.
@colinxfleming is it okay if we expedite this fix since it's so low risk and will be really useful for the Data Team? I'll help address #1402 at a later time.
Fixes #1401

Export correct fund fulfillment expenditure column

---

app/views/patients/_delete_duplicate_patient_button.html.erb
app/views/patients/_patient_dashboard.html.erb

Changed from button to link_to
* Fixed delete duplication patient to not fire on update.
* Fixes #1407

Fixed delete duplicate user button

---

test/system/call_list_test.rb
test/system/navbar_links_test.rb

"Fixing" some tests that are going to soak up more time than they're worth. Know when you're beaten, etc.
* Remove call list time travel test
* Remove navbar test that requires subbing out env vars, which we can't do in puma
* Fixes #1312 
* Fixes #1313 
* Bumps #Y

Delete flaky tests we are never going to fix

---

app/models/patient.rb
db/seeds.rb
test/models/patient_test.rb
test/system/data_entry_test.rb

Resolves: #825 
This change resolves a frustration point for CMs. Whenever they try to
register a patient whose phone number already exists in the system, they
will receive an error message stating the number is a duplicate. This
should not be a problem since CMs search for the number in the database
before creation. However, the search functionality is limited to the
CM's existing line, while the uniqueness check works across the entire
database.
For example, if the number 123-123-1231 exists on the DC line and the CM
is logged into the VA line, then they will receive no results when
searching for 123-123-1231. This implies a new patient. Then when the CM
creates a new patient with 123-123-1231, they will get an error saying
the number already exists.
To address this issue, I added a …

Handle search across lines

---

app/controllers/users/omniauth_callbacks_controller.rb
app/models/user.rb
lib/tasks/nightly_cleanup.rake
test/models/user_test.rb

We talked about avoiding having too many inactive but usable accounts by locking after 6 months. This sets up disabling them after 9 months, to allow a little bit of wiggle room and to reduce threat vectors for funds with a lot of CMs.
TK is writing tests, and I also noticed that logging in from oauth doesn't update the `last_sign_in_at` field on User, so we'll want to make an adjustment to the `from_omniauth` method to handle that.
* Add a command to the nightly cleanup task
* Add a user command to get and lock/disabled_by_fund user accounts
* Fixes #713

Lock inactive users after 9 months of inactivity

---

Gemfile
Gemfile.lock
app/models/user.rb
config/initializers/devise.rb

The oauth library ecosystem has resolved its weird hangups, so we can unpin a couple of our oauth libraries. And keeping oauth libraries up to date is important, because ~ authentication~ !
* bump `devise`
* bump `omniauth-google-oauth2`
I could get this to work locally but we should be sure to hammer on it on sandbox too.
* Fixes #1171

Upgrade oauth gems

---

app/models/concerns/history_trackable.rb

I was looking for this in an unrelated spot and found it on the plane. This should significantly improve load time of the patient view for patients with a lot of edits, and also improve reload after updates.
* slap an includes on the query to join in user data
No view changes, no issues.

Squash n+1 query on changelog

---

app.json
app/helpers/navbar_helper.rb
app/models/config.rb
app/views/configs/_config.html.erb
app/views/layouts/_navigation_links.html.erb
db/seeds.rb
test/helpers/navbar_helper_test.rb
test/models/config_test.rb

Adds a config for CM Resources link in the top navbar, and does some wiring to get the env var out of the way.
* New config value, plus the option to override it
* Tweak the view to pull from the config instead of the value
Shows up like so:
* Fixes #1268

Make CM Resources a config

---

Gemfile
Gemfile.lock
test/models/patient_test.rb
test/system/logging_calls_test.rb

I am deeply annoyed by our flaky tests, which seem to fail one out of every five times or so. So I'm throwing in a retry gem.
* Add `minitest-optional_retry` as recommended by the minitest dude
* palm slap it into `logging_calls_test` and `patient_test`
* Fixes #1326

Install minitest optional-retry and cover our flaky tests with it

---

app/models/concerns/exportable.rb

We're putting `city` in export, per request of a fund. This does that thing.
This is already porting over in archived patient, so we should be good to go after this.
* one-line change to add city to the export file. SWEET
* Fixes #1449

Add city to export file

---

app/views/dashboards/_budget_bar.html.erb

I think at first it will be more trouble than it's worth to set this up, until we have a config that does it, so commenting it out for now.
* Comment out the remaining div in budget bar

Budget bar tweak for deploy: comment out the Remaining figure

---

app/controllers/users_controller.rb

Changes: After using the create users form, we now redirect to users_path instead of the session referrer. This will produce the same behavior as before of going back to the main users list, but is more secure.
* Fixes #1457

remove session referer to mitigate potential security problems #1457

---

app/controllers/accountants_controller.rb
app/controllers/application_controller.rb
app/controllers/patients_controller.rb
app/controllers/reports_controller.rb
app/controllers/users_controller.rb
test/controllers/accountants_controller_test.rb
test/controllers/reports_controller_test.rb
test/controllers/users_controller_test.rb
test/system/accountant_workflow_test.rb

Want to emphasize that none of these are huge holes, none of them involve db writes, and they're only accessible if you have a valid CM account already, and know some key stuff about our system. That's no excuse to not patch though.
This explicitly sets some data access permissioning on accountants and reports controller endpts, and makes user edit admin-only. Users should be able to edit their own data still via their own devise panel. 
* only data vols can access reporting and accounting endpoints now
* only admins can access user panels
* unit tests!
* Fixes #1456 
* Fixes #1455 
Tagging in one of @tingaloo @mdworken or …

Fix permissioning for user edit, accountants controller, and 

---

.circleci/config.yml
Gemfile.lock

rubyzip is failing builds due to an open CVE, but we don't use it in production, so I am politely telling bundler-audit to hush on that CVE until they have a fix in.
* update selenium-webdriver to see if it fixes the prob (it doesn't)
* ignore that CVE in builds
no issues

Shut off bundle-audit CVE check until rubyzip gets fixed

---

app/models/patient.rb
test/models/archived_patient_test.rb

People were getting archived early because the timestamp library worked differently than we thought it did (web forms don't update). This changes the archiving rules to reflect reality.
* use patient updated timestamp for archiving instead of fulfillment updated timestamp
* Fixes #1474

Use patient timestamp for archiving rules

---

app/models/concerns/call_listable.rb
test/models/user_test.rb

See #1476 for an explanation, but in a nutshell current sign in at gets populated slightly differently than we thought it did.
* take the max of current sign in at and last sign in at when deciding whehter or not to clear a call list
* Fixes #1476

Clear call lists based on actual last sign in instead of second to last sign in

---

app/views/patients/_patient_information.html.erb

* Changed the label as per the issue #1499 
* Fixes #1499

Changed the label of the 'Referred by' dropdown #fixes-1499

---

app/models/concerns/patient_searchable.rb

I was looking through the test coverage and noticed that these two methods were never being called.  They are user search methods in the patient searchable module and probably dont belong.
* Remove unused private search methods that are not used.
* Fixes #1516 
* Bumps #Y

remove user searches from patient searchable

---

app/assets/javascripts/patients.coffee
app/controllers/patients_controller.rb
app/helpers/tooltips_helper.rb
app/models/patient.rb
app/views/patients/_abortion_information.html.erb
test/system/update_patient_info_test.rb

This pull request relates to #1497 
- New field `completed_ultrasound` added to patient, as well as the checkbox view and helper text
- updated existing system test case
**Changes in views**  
Now there is a new checkbox for the ultrasound info available. How to see it: 
- click on a patient
- click on Abortion Information tab

New checkbox field for ultrasound info

---

Gemfile.lock
app/controllers/patients_controller.rb
lib/tasks/update_clinic_coordinates.rake
test/system/update_patient_info_test.rb

A few small fixes in advance of deployment for corners that got cut during hacktoberfest sprinting.
* Adds a systemtest for textable
* Controller whitelists textable
* Actually save coordinates after getting them

Fixer upper on textable and clinic coordinate setting

---

app/controllers/accountants_controller.rb
app/helpers/footer_helper.rb
app/views/layouts/_footer.html.erb
test/helpers/footer_helper_test.rb

* squelches an n+1 join in the accountants controller
* `fax_service` was making three queries, so we're getting ahead of it here by just setting the var in the helper, and moving the html generation out of the view into the helper
* Fixes #1551

squelch the accountants n+1 join and a duplicate fax query

---

app/models/clinic.rb
app/services/clinic_finder/locator.rb
config/initializers/geokit_config.rb
test/models/clinic_test.rb

As pointed out by @dismantl in #1337 , the way we're handling google geo api keys is a little weird and not super railsy. We addressed the initial problem of not having the key anywhere in the codebase when we brought in the clinic finder code, but there's still some awkwardness and redundancy in how we're handling the key; this addresses most of it.
* set up geokit initializer
* move env var hits to the initializer
* Fixes #1337

move api key to an initializer, simplify clinicfinder code

---

app/helpers/tooltips_helper.rb
app/views/dashboards/_overview.html.erb
test/helpers/tooltips_helper_test.rb

Adding the tooltip for budget bar, where should it go?
EDIT: moved tooltip.
* Add tooltip
* Fixes #1532

add tooltip to budget bar

---

app/views/layouts/_footer.html.erb
config/locales/en.yml
config/locales/es.yml

Adds il8n keys for the footer like so:
In that example, the DC Abortion Fund is set from an env var and so an in-place spanish translation would be a not-easy basket. but the stuff around it is hardset so let's il8n that.
* Translates the footer content
@DarthHater for review on the ruby, @montanezp for review on the spanish
* Bumps #1382

Translate the footer to Spanish

---

.circleci/config.yml

```
#!/bin/bash -eo pipefail
gem install --no-rdoc brakeman
ERROR:  While executing gem ... (OptionParser::InvalidOption)
invalid option: --no-rdoc
Exited with code 1
```
FROM: https://circleci.com/gh/DCAFEngineering/dcaf_case_management/4460?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
One of my PR's was failing as a result of `gem install` removing `--no-rdoc` as an option. I've replaced it with `--no-document` as mentioned here: https://github.com/bundler/heroku-buildpack-bundler2/pull/1#issuecomment-451654992
* Small change to `.circleci/config.yml`

Remove --no-rdoc in favor of --no-document (fixes builds)

---

app/lib/exceptions.rb
app/models/clinic.rb
lib/tasks/nightly_cleanup.rake
lib/tasks/update_clinic_coordinates.rake
test/models/clinic_test.rb

We have some ruby that updates coordinates; this pulls it out of a rake task and into an object method, and does some testing around it to confirm it's working properly. 
* pulls `update_all_coordinates` 
* adds it to `nightly_cleanup` task
* Fixes #1525

add coordinates refresh method to Clinic and port it into nightly_cleanup

---

docs/ADOPTING_DARIA.md

Other funds are interested in DARIA. This PR will make a short one-pager addressing FAQs from interested funds.
Let's fill in with one paragraph summaries as much as possible. Err on the side of brevity and happy path stuff, rather than extreme depth and edge cases.
* adds doc
* Fixes #1545

Add Adopting DARIA document for interested funds

---

app/helpers/change_log_helper.rb
app/models/audit_trail.rb
app/views/patients/_change_log.html.erb
app/views/patients/_change_log_entry.html.erb
test/helpers/change_log_helper_test.rb
test/models/audit_trail_test.rb
test/system/change_log_test.rb

a quick NITE PR -- I think this should resolve the problem described in #1338 . Screenshots in the morning. I'm getting old.
* `blank` changelog entries now show up as `(empty)`
* remix the view so breaks between individual field changes are always clear
* tests for same
* Fixes #1338

Make entries line up by being clearer about what nil is

---

app/views/dashboards/_activity_log.html.erb
app/views/dashboards/_overview.html.erb
app/views/dashboards/_search_form.html.erb
app/views/dashboards/_table_content.html.erb
config/locales/en.yml
config/locales/es.yml

Tackles some of the translation on dashboards, specifically strings contained in partials. Strings that are inferred or produced from helper methods are tk.
It felt weird to pull single simple words into their own nested namespaces, so this PR also stands up the top level namespace `common`, which I stuck a bunch of one word things into like Add, Phone, etc.
This doesn't touch the slightly more complex stuff (in helpers, for example). But I am committing to doing that here.
* translate strings defined in the dashboard partials
* a little bit of view cleanup while I'm rooting around in there
cc @montanezp can you pop in here and review the translations?
It relates to …

Translate string constants in dashboards

---

app/controllers/clinicfinders_controller.rb
app/models/clinic.rb
app/services/clinic_finder/locator.rb
test/services/clinic_finder/clinic_finder_test.rb

While working thru #1595 it kinda became apparent that we were just reimplementing activerecord filters in the clinic finder code. This strips out those filters in favor of activerecord. I separated this change out because it's sort of independent of the larger work of setting up gestation limit filtering.
* deletes filter methods from clinicfinder
* moves it all to the controller (for now)
* Bumps #1365

Remove filters from ClinicFinder in favor of Mongoid/ActiveRecord#where

---

app/controllers/application_controller.rb
app/helpers/navbar_helper.rb
app/views/layouts/_navigation_links.html.erb

I borked #1527 so here's a new cleaner PR
This adds a link to switch from Spanish and English for the app, as well as enables default url options to include the locale.
* Tiny changes to the application controller
* A helper for outputting the spanish/english link
* Adding the helper into the navbar view

Switch to Spanish Link

---

app/helpers/events_helper.rb
app/models/event.rb
config/locales/en.yml
config/locales/es.yml
test/helpers/events_helper_test.rb
test/models/event_test.rb

This translates the view-facing strings in the Event model and moves them over to the `events_helper`. This was the least intrusive way I could come up with to do this that didn't break the existing Event model.
* adds spanish translations for the event log
* moves the user-facing text out of the model
Note that we can't see the event view because this partial loads async, which can't set locale.
* Fixes #1578  ~(not done, because we need to move to session)~

Translate Spanish event strings (and move them out of the model) 

---

app/helpers/tooltips_helper.rb
config/locales/en.yml
config/locales/es.yml

This PR adds i18n to the tooltips in tooltips_helper. These are spread out over a few views but were all trivial to port.
* Ports tooltips_helper to use i18n
* Fixes #1575 (I think!)

Translate tooltip helper text

---

app/controllers/clinicfinders_controller.rb
app/helpers/clinicfinders_helper.rb
app/models/clinic.rb
app/models/concerns/last_menstrual_period_measureable.rb
app/views/clinicfinders/_search_form.html.erb
app/views/clinicfinders/search.js.erb
app/views/patients/_abortion_information.html.erb
test/helpers/clinicfinders_helper_test.rb
test/models/clinic_test.rb

Adds gestation filter as a parameter you can filter down in clinic finder. If, for example, you are a CM working with someone who's 18w, clinics that don't go that far are unhelpful at best and misdirecting at worst. This pops those out early via some filtering in the controller.
Tests TK
* Adds gestation filter as a thing you can filter clinics by in clinic finder
* Adds gestation filter to the clinic finder results table
* includes #1596 
Getting a little cramped, but it works!
* Fixes #1365

Add clinic finder gestation filter

---

app/controllers/application_controller.rb
app/controllers/dashboards_controller.rb
app/helpers/budget_bar_helper.rb
app/views/dashboards/_budget_bar.html.erb
app/views/dashboards/_search_form.html.erb
config/locales/en.yml
config/locales/es.yml

Translates the budget bar courtesy of some great work by @DarthHater in #1597 . Also translates the `render_async` stuff in the budget bar.
This leaves the tooltips alone, as they are a LOT of spanish. But that's the remaining part.
* Translates search results partial and budget bar
* Bumps #1575

Port ajax-produced strings on dashboards

---

app/views/patients/update.js.erb

We missed a spot in the patient edit view when updating fields. This adds the i18n keys to the translations.
* Use i18n instead of hardset strings in app/views/patients/update.js.erb
* Bumps #1633

Spanish view refres

---

app/helpers/notes_helper.rb
app/views/dashboards/_table_content.html.erb
config/locales/en.yml
config/locales/es.yml

Missed a spot on the dashboard.
* Translates Most Recent Note, an i18n key I missed on the dashboard
* Bumps #1633

Most recent note translate

---

app/views/patients/_call_log.html.erb
config/locales/en.yml
config/locales/es.yml

Translate the i18n key for call delete.
* Translate the sneaky i18n key for call delete
* Bumps #1633

Translate remove call alert

---

config/locales/devise.es.yml

We were getting some unauthenticated issues from devise. This papers over any devise related spots we missed generally by just copying over the full translation set from https://github.com/tigrish/devise-i18n/blob/master/rails/locales/es.yml . Thanks team `devise-18n`!
* vendor a spanish devise file from a devise i18n gem
* Bumps #1648

add spanish devise translations

---

app/helpers/patients_helper.rb
app/views/patients/_patient_information.html.erb
test/helpers/patients_helper_test.rb

Insurance options has a bug because we're pushing value onto it if not present, so that deprecated values aren't auto-removed on save. We should probably be doing this in more places tbh and I might add it to other option methods. But this gets us out of the doghouse immediately.
To test:
* switch to spanish mode and go to a patient
* change insurance to `no se`
* reload page and observe it being `no se` still
* Change it to nil, reload, observe nil properly observed
* Change it to a custom (nonspanish) option, observe it again
* fix spanish bug around setting insurance options
(If there are changes to the views, please include a screenshot so we know what to look …

Fix insurance options spanish bug

---

app/controllers/users_controller.rb
app/views/devise/registrations/edit.html.erb
config/locales/en.yml
config/locales/es.yml
test/controllers/users_controller_test.rb

Not sure how I forgot the user page in the translation list, but shrug! Here it is.
* Translate the user page
* Bumps #1648 
Ready for spanish review @montanezp

User page in Spanish!

---

app/helpers/navbar_helper.rb

Remove a conditional to turn spanish on in production mode. Merge when it's showtime!
* remove a conditional to turn on spanish language mode
* Fixes #1382

Turn on spanish link in production

---

config/environments/development.rb

integrity checks were still going because I forgot how booleans.
* make boolean evaluate properly

Colin forgot how booleans work, so fix docker build

---

Gemfile
Gemfile.lock

It's Nokogiri season.
* bump nokogiri to >= 1.10.3 to squelch a CVE
no views or issues

upgrade nokogiri to squelch a vuln

---

app/helpers/change_log_helper.rb
app/views/patients/_new_patient.html.erb
app/views/patients/_patient_information.html.erb
app/views/patients/data_entry.html.erb
config/locales/en.yml
config/locales/es.yml

So two things here:
* This dumps model fields into i18n
* I wanted to see if they got automagically read by bootstrap_forms and turns out they do! So I changed some of the stuff in patient information over to be in the business of only setting keys in one place as much as possible.
* There are a few entries we infer (`Clinic` for example) which are not really Patient fields per se, so we'll have to handle those ever so slightly differently in a way that isn't clear to me here. But this handles 90% of it and reduces this down to a few simpler next steps, so we can probably merge as is and put a nail in the coffin
* Add patient attributes on mongoid i18n something …

Translate most changelog fields, use model keys for translations in patient information form items

---

.circleci/config.yml

interested in whether or not this is what's making our builds choke. No rule says dog can't play basketball.
* remove `store_test_results` step from CI
* Fixes #1491 ... OR DOES IT?

Try removing store test results step

---

app/views/devise/registrations/edit.html.erb
app/views/patients/update.js.erb

Bootstrap form seems to handle static elements a little differently, so we're changing them to disabled and readonly input fields.
* `static_control` => `text_field, disabled: true, readonly: true`
no view change
no issues

Fix system test that is sad about a change to static control

---

Gemfile.lock
package.json
yarn.lock

`yarn audit` was throwing some screamers, this resolves them. yarn audit is still sad though.
* bundle update webpacker
* some yarn audits
no issues

Squelch some yarn vulnerabilities, bump webpacker to latest point release

---

db/seeds.rb

Super small fix :-). I changed what looks like a typo in the seed file, which was breaking the CM Resources link in the navbar.

Fixing seeds so the CM resources link works

---

app/assets/javascripts/patients.coffee
app/controllers/practical_supports_controller.rb
app/views/patients/_menu.html.erb
app/views/patients/_practical_support.html.erb
app/views/practical_supports/_entries.html.erb
app/views/practical_supports/_new.html.erb
app/views/practical_supports/_show.html.erb
app/views/practical_supports/create.js.erb
app/views/practical_supports/destroy.js.erb
app/views/practical_supports/update.js.erb

Not shipping because there's some additional UI to do, but this sets up update and destroy in the UI. Still not quite primetime ready but materially closer.
* Sets up entry update and destroy (no tests yet)
* some UI cleanup and breaking things into more rest-y routes
* turn on the autosave!
The state of the world:
Still todo are tests and localization and exports at least, and doing a quick UI check with @mlindberg61 .
* Bumps #1493

Add ability to edit practical support forms

---

config/locales/en.yml
config/locales/es.yml

Per conversation in #1709 there's a redundancy in the tooltip. This strips that.
* Remove redundant or possibly irrelevant information about start date for the budget bar
no notable view changes
* Bumps #1698, sorta

Remove redundant budget bar tooltip text

---

app/views/patients/_practical_support.html.erb
app/views/practical_supports/_show.html.erb
app/views/practical_supports/create.js.erb
app/views/practical_supports/destroy.js.erb

I put this together kinda sloppy in terms of alignments/proper element id usage, so this adjusts them and empties out the right partials.
I think this is covered by existing system tests. Also want to note that after this, the partial will start showing up in sandbox for real.
* align everything along the rail
* properly empty out the entries partial if there are no entries
Now left aligned on both create and page load like so:
* Bumps #1493

Practical support: Correct spacing/alignment/refresh on create/update/destroy actions

---

app/views/patients/_abortion_information.html.erb
app/views/practical_supports/_entries.html.erb

#1723 noted that the verbiage was kinda confusing, so we clarify it to `Support needed` and `Point of contact`.
We also add an indicator to abortion information to make a note when a patient has practical support entries. This seems so straightforward and noncritical that I don't think we need to ajax changes in or test for it. Open to other opinions.
* change verbiage
* add indicator to abortion information when a patient has practical supports
* Bumps #1723

Change verbiage of practical support columns and add indicator

---

app/helpers/practical_supports_helper.rb
test/helpers/practical_supports_helper_test.rb

Had an open question about how to handle more than one active request out -- I think we're trying to actively discourage the possibility that it won't be clear who's quarterbacking a practical support supply effort, and that need supersedes what we lose on reporting here by not knowing 'we asked this fund but they went in a diff direction'.
* adds new wildcard options and patient as practical support source
* keeps current validation of only one source type the way it is now
* Bumps #1723

add other/wildcard options to support source and type options

---

app/assets/stylesheets/application.css.scss

I'm trying to live my truth in 2019 and squash deprecation warnings. Two of those for sass were happening on bootup about extending compound selectors. 
It turns out that the hover extend wasn't really doing anything and was deleteable; and the other one was just copying some other code over, so I ported it to a mixin.
* delete a compound selector that didn't do anything
* extract a mixin from another compound selector and use that
no view changes!
* Fixes #1662

Squash sass deprecation warnings -- remove one illegal extend, move the other to a mixin

---

app/controllers/patients_controller.rb
app/helpers/practical_supports_helper.rb
app/views/patients/_practical_support.html.erb
app/views/practical_supports/_edit.html.erb
app/views/practical_supports/_entries.html.erb
app/views/practical_supports/_new.html.erb
config/locales/en.yml
config/locales/es.yml
test/helpers/practical_supports_helper_test.rb
test/system/practical_support_behaviors_test.rb

This does the translation for practical support.
It involved a little bit of gut work in practical_support_helper; I remember this now, but the reason we had the complex checking system is because i18n keys-value pairs don't reduce to english values easily. So we do a little bit of of a dance, which I've rolled up into a private method here.
* adds i18n keys for practical support
* fixes up some helpers to account for different keys and values because of translation
Example of the view changes: 
@montanezp can you review the translations the same way we reviewed the old stuff? Take a look at the green stuff in es.yml and compare it to the corresponding language in …

Do i18n translations for practical support

---

app/models/patient.rb

BRAF found a bug with the budget bar that stems from our casting to date being in UTC instead of eastern. This enforces timezone on our budget bar filter.
Tests TK because it's a late code change
* filters on a time instead of a date in budget bar, to account for timezone
no view changes, no issue

Respect time zone in budget bar

---

docs/SETUP.md

I added a sentence to the instructions that clarifies how to use the terminal to clone the github repository.
* adds a sentence that tells the user to change the directory before entering the next command into the terminal.
* (etc)
* Fixes #X
* Bumps #Y

clarified instructions for using terminal

---

Gemfile.lock

Get the build passing by running bundle upgrade nokogiri.
* bump nokogiri to 1.10.4
no views, no issues

Upgrade nokogiri to squelch a CVE warning

---

Gemfile
Gemfile.lock

This library hasn't been bumped in five years and we don't use it, and it's not compat with rails 6, so off it goes.
* remove bootstrap_form-datepicker library
* Bumps #1589

Remove unused datepicker library

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/users/new.html.erb
config/locales/en.yml
config/locales/es.yml
db/seeds.rb
test/controllers/users_controller_test.rb
test/factories/user.rb

Previously users were created without roles by default. This makes a few changes to correct this:
- Newly created users have role CM
- Users are required to have a role
- Updated tests/factories
Fixes #1749

Requires roles for users. Adds default role of case manager to users#create

---

Gemfile
Gemfile.lock

Bump devise to squelch a vuln
* `bundle update devise`
no issues

upgrade devise to 4.7 to squelch a vuln

---

app/javascript/packs/application.js
app/javascript/src/fontawesome.js
app/views/dashboards/_search_form.html.erb
package.json
yarn.lock

Adds the fontawesome library to our app so we can start subbing out glyphicons in BS4 work. Am sorry to take a hacknight issue but this is starting to butt up against BS4 work.
* yarn add fontawesome something something
* add it to webpack
here it is on our searchbar:
* Fixes #1750

Add font-awesome library to make glyphicons available

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/pregnancies.scss
app/javascript/src/clinic_finder.js
app/views/clinicfinders/_search_form.html.erb
app/views/patients/_abortion_information.html.erb
app/views/patients/_menu.html.erb
app/views/patients/_menu_item.html.erb
app/views/patients/_patient_information.html.erb
app/views/patients/edit.html.erb

Restyles the abortion information partial. Got this pretty close as well!
Didn't have to commit any particular HTML/CSS to get there either.
Note that this contains a few commits from earlier in the process; please focus your attention on the files patients/_abortion_information and clinicfinders/_search_form.
* refactor abortion information partial to use BS4
olde: 
new: 
* Bumps #1632

BS4: Remix abortion info partial

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/pregnancies.scss
app/views/patients/_menu.html.erb
app/views/patients/_menu_item.html.erb
app/views/patients/_patient_information.html.erb
app/views/patients/edit.html.erb

WIP until bs4-2 gets prelim approved
This is converting and refactoring the BS4 partial. Wound up being a pretty complete rewrite but puts us in a good position going forward.
Very little custom CSS, but there's a little to sort out how we use labels on the right side of checkboxes rather than the left, and to space things properly.
* converts patient information partial to bs4
sandbox:
BS4 (I got it pretty close!):
* Bumps #1632

Convert patient information partial to BS4

---

app/helpers/practical_supports_helper.rb
app/views/patients/_practical_support.html.erb
app/views/practical_supports/_edit.html.erb
app/views/practical_supports/_entries.html.erb
app/views/practical_supports/_new.html.erb

Converts the practical support partials to bootstrap 4. Nothing too fancy but did have to redo the way we do rows a little bit.
* bootstrap-4-ify practical support
got this pretty close! recommend to focus on the files with practical_support in the name somewhere.
olde:
newe:
* Bumps #1632

Convert practical support partial to bootstrap 4

---

app/assets/stylesheets/application.css.scss
app/views/users/_search_form.html.erb
app/views/users/_users_table.html.erb
app/views/users/index.html.erb

Changes to the user account management table to make it BS4 compat. Had to do very little to this, but did make some readability edits.
(Just look at the users dir changes.)
* nothing fancy, just some gentle column refactoring.
olde:
new:
* Bumps #1632

Convert user account management table to BS4

---

app/views/users/edit.html.erb

Bump BS4 user edit page. Pretty easy! Pretty much identical.
Edits all in `app/views/users/edit.html.erb`
* BS4ify user edit page
olde:
new:
* Bumps #1632

BS4 updates to user edit page

---

app/assets/stylesheets/accountants.scss
app/views/accountants/_search_form.html.erb
app/views/accountants/_table_content.html.erb
app/views/accountants/_table_content_row.html.erb
app/views/accountants/index.html.erb
app/views/configs/_config.html.erb

Bump  config and accountants pages. Had to add some custom styling to get accountants to play nice but it worked!
Stop me if you've heard this one before but just note changes to accountants and configs dirs, and accountants.scss (which had to get bumped to play nice with new kaminari styles, I think).
* bump configs styling (slightly)
* bump accountants page styling (less slightly)
olde:
new (edit is a placeholder until we get glyphicons back, and the modal is the fulfiillment page which isn't done yet):
* Bumps #1632

BS4 upgrade for Config and Accountants page

---

.gitignore
app/assets/stylesheets/application.css.scss
app/views/dashboards/_budget_bar.html.erb
app/views/patients/_abortion_information.html.erb
app/views/patients/_call_log.html.erb
app/views/patients/_change_log.html.erb
app/views/patients/_notes.html.erb
app/views/patients/_patient_information.html.erb
app/views/patients/_practical_support.html.erb

Bootstrap has a nice inline spacing utility. Instead of creating our utility classes, we can leverage them from BS4. 
I just targeted unique ids and classes that were used once.
Anyways utility CSS is another coffee table discussion because it enforces a structure whilst being highly flexible. The current app has custom utility functions which can use a refactor. But it's definitely worth looking into.
https://getbootstrap.com/docs/4.0/utilities/spacing/
* Setups spacing 
```
1: ($spacer * .25), //.125 rem
2: ($spacer * .5), //.25 rem
3: $spacer, //.5 rem
4: ($spacer * 1.5), //.75rem
5: ($spacer * 2), //1rem
6: ($spacer * 3) //1.5rem
```
It relates to the following …

Setup spacing utility in bootstrap

---

app/assets/stylesheets/dashboards.scss
app/helpers/dashboards_helper.rb
app/helpers/notes_helper.rb
app/helpers/tables_helper.rb
app/views/dashboards/_search_form.html.erb
app/views/dashboards/_table_content.html.erb

BS4ifys (and fontawesomeifies) patient dashboard.
* BS4ify dashboard tables
* readd fontawesome icons in place of glyphicons
Very slight difference in the icon -- the new targets are very slightly bigger. The reorder handle is a little darker too, and the spacing is a little different, but it comes together nicely.
olde:
newe:
* Bumps #1632

BS4ify CM dashboard table content

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/patients.scss
app/views/patients/_pledge.html.erb

BS4ify the pledge modal. Mostly this means turning cols into rows, form_for into form_with, and hacking in a little bit of css that our multimodal vendor library was expecting.
When this is over (possibly when we start adding js components) we should work hard to figure out if we can ditch that library. Lots of magic going on, and that magic assumes bs3 which makes it hard to work on.
CI failures are expected because feature branch.
* bs4ify the pledge flow
olde:
new: this isn't super pretty. You'll notice that cancel doesn't float correctly. I think that's probably okay as we'd have to get into the vendor library and rewire things a little bit to get that to work …

BS4ify submit button

---

app/assets/stylesheets/events.scss
app/helpers/events_helper.rb
app/models/event.rb
app/views/events/_events.html.erb
test/helpers/events_helper_test.rb
test/models/event_test.rb

Convert the events log on the main dashboard to BS4. Nothing terribly interesting.
Note that CI fails intentionally here because we're merging this into the feature branch.
* bs4ify event log
* use fontawesome icons instead of glyphicons (rip)
old:
new -- the font size is a little increased and the thumbs ups are white now to make them easier to see:
* Bumps #1632

BS4ify events log

---

app/assets/stylesheets/application.css.scss

The modal in BS4 slims down to a max width of 500px at the highest breakpoint, which is kinda tiny. I'm setting it to 60% instead so that it doesn't get super cramped up in, for example, the accountants view, new call modal, or submit pledge modal.
like other BS4 PRs, CI fails intentionally because we're smashing this into a feature branch `bs4-2`, so don't be put off by that when reviewing.
* `max-width: 60%` on `.dialog-modal`
olde:
new:
* Bumps #1632

BS4: Widen the default modal

---

app/views/layouts/_footer.html.erb
app/views/layouts/application.html.erb

Going thru app and realized I forgot to convert the footer, so here it is. Includes some additional cleanup along the way.
Note that this is going into a feature branch and we're not worried about tests/builds failing.
* BS4ify the footer
olde:
new (slightly thicker phone glyphs is the only real diff):
* Bumps #1632

BS4ify app footer

---

app/views/patients/_fulfillment.html.erb
app/views/patients/_menu.html.erb
app/views/patients/_practical_support.html.erb

This BS4ifies patient fulfillment partial. No particular ugly stuff but I did have to delete an extra div that snuck in somehow to get the partial to render right.
(CI failures intentional because this is going into a feature branch.)
* BS4ify fulfillment partial
olde:
new, basically identical:
* Bumps #1632

BS4 fulfillment partial

---

app/assets/stylesheets/pregnancies.scss
app/views/accountants/_table_content_row.html.erb
app/views/clinicfinders/_search_form.html.erb
app/views/layouts/application.html.erb

Sub in the remaining fontawesome icons for the glyphicons. rip glyphicons.
Along the way, I have learned some valuable lessons about doing col-s in bootstrap 4, so subbed those in, and removed some extraneous comments.
* remove remaining glyphicons
* Bumps #1632

BS4 - Replace remaining glyphicons

---

app/assets/stylesheets/lines.scss
app/views/devise/sessions/new.html.erb
app/views/lines/new.html.erb

I think this is the last of it! Just the line selection and login page.
* bump login page
* bump line selection page
olde:
new (bigger google button, outlined password button on login page; some slight realignment on line selection):
* Bumps #1632

BS4 convert login page and line selection

---

app/javascript/src/clinics.js
app/views/patients/_abortion_information.html.erb
app/views/patients/_fulfillment.html.erb
app/views/patients/_menu_pledge_button.html.erb
app/views/patients/_patient_dashboard.html.erb
app/views/patients/_patient_information.html.erb
app/views/patients/_pledge.html.erb
test/integration_helper.rb
test/system/drag_and_drop_test.rb
test/system/event_log_interaction_test.rb
test/system/tooltips_test.rb
test/system/update_patient_info_test.rb
test/system/user_searches_test.rb

This might be all of them! Mostly this is changes related to `form_with` instead of `form_for`, or adjustments to account for because BS4 is sliiiightly less snappy on some stuff than BS3 was.
I had to comment out the drag and drop test - while the drag and drop functionality still works, something about the `drag_to` isn't reordering them. I think this is because drag_to puts things in the exact center, and because of that it doesn't know whether to go up or down and just does nothing instead. This was real annoying but we should just file it as a debt ticket in my opinion.
* small fixes and adjustments to get system tests to pass
* comment out drag and drop test
no …

BS4 system tests II: the legend continues

---

docker-compose.yml
scripts/start_rails.sh
scripts/start_webpack_dev.sh

On a fresh `docker-compose up --build` the app fails to load due to the unavailability of webpack and assets.
* add webpacker as a service
* moved the entry point commands to their own scripts for easier modification
* included the pid server removal in the script
* Fixes #1741

added the webpacker service to dockerization

---

.github/workflows/dcaf-build-workflow.yml
app/views/patients/data_entry.html.erb

Fixed some sneaky keys.
Changed our build version to `2.6.x`, so that the build will go green whenever github actions ruby catches up to our aggressive version bumping :smile: 
(ignore the :heavy_check_mark: on the one commit, my fork'd version sometimes only runs CircleCI)

Quick check to see if I can green the build?

---

app/models/patient.rb
test/models/patient_test.rb

The `has_special_circumstance` method was always returning true to boolean safety checks against ints.
```
irb(main):001:0> !!0
=> true
irb(main):002:0> !!1
=> true
irb(main):003:0> !!false
=> false
irb(main):004:0> !!true
=> true
```
* switched from `0` and `1` to `true` and `false`
* added a test
* Fixes #1827

Has Special Circumstance Always Returns True

---

app/assets/stylesheets/application.css.scss

Darker foreground, more accessibility, (aka remembering how git forks work at all)
*  darker grey text
*  looking super compliant here.
* Fixes       #1754

darken contrast foreground on navbar

---

app/views/patients/data_entry.html.erb

This fixes a minor bug that I noticed on the data entry page where the fund name was not provided for the i18n key.
Before:
After:

Adds fund name for i18n key

---

app/helpers/practical_supports_helper.rb
app/views/patients/_practical_support.html.erb

De-emphasized the DCAF guidance link 
* Changed styling of link from h2 to h5
* Separated header from the link so that it's located below header
* Added bottom margin to link 
It relates to the following issue:
* Fixes #1821

Improved styling of the DCAF guidance link

---

Gemfile
Gemfile.lock

Squash a loofah security complaint by bumping to 2.3.1
* loofah to >= 2.3.1
no issues

bump loofah to squash a security complaint

---

app/services/readme.md
app/services/uri_service.rb
test/services/uri_service_test.rb

Adds a resilient URI service utility that can force the scheme to https
adds utility and test
* Connects #1826 (fix coming in #1843)

Add URI https-ification service

---

app/views/patients/update.js.erb

Hello! I added a little bit of code in update.js.erb to dynamically update the tooltip content rendered in _patient_dashboard.html.erb. 
* Without having to refresh the page, the helper text content in the tooltip (which shows up when you hover over the '?' next to a patient's status text) updates accordingly when the status itself changes (the change usually happens when a CM has entered the patient's  appointment date, or a pledge has been sent). 
* Fixes #1825

Status helper text updates when patient status updates (#1825)

---

config/environments/development.rb

Removing this line allows the yarn integrity check to always be true (set at the top of the file).  Newer docker builds have no issues with this removal.  Possibly fixed from webpacker docker service.
* Removed docker env check for yarn `check_yarn_integrity`
* Fixes #1667

Remove Docker Yarn Integrity Check

---

app/views/patients/_pledge.html.erb

`form_with` is ajax by default. This is not an ajax endpoint, so it would be generated and then nothing would happen. 
don't worry about test failures because feature branch.
* make this endpoint ajaxy
no view change, really, but the download works!
* Fixes #1822

Fix pledge generation by making it synchronous

---

app/assets/stylesheets/application.css.scss

Anchor and button tag focus states were a little different for some reason, and now they're not. Circle of life.
Don't worry about the test failures.
* set focus styling on anchor tags -- we're overriding some stuff but not all, now we are
New focus state looks like:
* Fixes #1823

Fix add new user button miscolorization

---

app/helpers/practical_supports_helper.rb
test/helpers/practical_supports_helper_test.rb

Unit test caught a potential issue if a practical support config is not set. This fixes that and adjusts another unit test to match reality.
* add early return to avoid URLGeneration error
* fix unit test to match new output without `small` html tags
no changes
* Bumps #1632

BS4: Early return if there's no URL to generate on practical support helper

---

app/views/patients/update.js.erb
test/system/data_entry_test.rb

System tests picked up some failures in the flash message and data entry tests. This gets everything green again, I hope.
* BS4 changed the way tooltips get refreshed, though not by much, so adapted @harumhelmy 's status refreshing code a little bit (s/o to my dog stack overflow)
* one of the element renames got weird; this was iso'd to just system tests
* Fixes #1632

BS4 system test failures: bs4ify tooltip bump; fix system test misspelling

---

app/assets/stylesheets/application.css.scss

Links for btn-primary MOSTLY follow the standard, but for some reason on sandbox this isn't flying and the text color follows the anchor blue, which is unreadable on our purple background.
This forces text color white on btn-primary. Which hopefully resolves this in sandbox -- I can't recreate in staging.
* btn-primary now has color: white;
* Fixes #1632

force white text on btn-primary

---

app/assets/stylesheets/application.css.scss
app/views/accountants/_search_form.html.erb
app/views/lines/new.html.erb
app/views/patients/_menu.html.erb

Removes a few things we don't need to use anymore now that we're in full on BS4.
The new rails hotness is `bootstrap_form_with`, so we're converting some of these over. The bootstrap_form_for stuff is more complicated to port and there's more of it, so we can do that in its own ticket which I'll write up in a sec.
* remove section tag and styling
* convert bootstrap_form_tag to bootstrap_form_with url:
* Fixes #1787

Remove section tag and bootstrap_form_tag

---

Gemfile
Gemfile.lock

Upgrade nokogiri to squelch a vuln.
* nokogiri to 1.10.5
no views
no issues

update nokogiri to squelch a vuln

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/lines.scss
app/assets/stylesheets/pregnancies.scss
app/javascript/src/clinic_finder.js
app/views/clinicfinders/_search_form.html.erb
app/views/patients/_patient_dashboard.html.erb
app/views/users/index.html.erb

In the spirit of cleaning up messes I made, this PR uses mx-* and d-none in places where we were using `margin-x` or `hidden`. Much nicer! Credit to @tingaloo for this insight, and lets us kill off a decent chunk of handrolled css.
* use bootstrap-4-y `mx-*` over custom margin declarations except in like one spot
* use bootstrap-4-y `d-none` over custom hidden classes except in one spot
no view changes!
* Fixes #1788

Favor mx-* and d-none in frontend code

---

.gitignore

The default puma config in rails 6 gets mad if the pids directory doesn't exist. We can pull this change out into its own thing for simplicity.
* put `.keep` files in tmp directories we want to exist
* adjust gitignore so they show up
no issue but related to #1589

adjust gitignore so tmp directories always exist

---

.browserslistrc
Gemfile
Gemfile.lock
babel.config.js
bin/webpack
bin/webpack-dev-server
config/webpacker.yml
package.json
postcss.config.js
yarn.lock

This began life in the course of upgrading webpacker to beat the Art Deco CSS problem of fontawesome icons being huge, and is something we should do, but that we can also pull out of the Rails 6 upgrade.
This upgrades the gem, js library, and regenerates the files (although we keep the integrity checks).
@rudietuesdays hopefully this makes your CSS work easier? eh?
* upgrade webpacker

Upgrade webpacker to 4.2

---

config/mongoid.yml

Not sure this will work but when I shipped rails 6 to prod it got mad about this:
```
Mongo::Error::OperationFailure (Mongo::Error::OperationFailure: Transaction numbers are only allowed on storage engines that support document-level locking (20) This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string or use the retry_writes: false Ruby client option):
```
This seems to be because mlab doesn't support this; hopefully this is as simple as changing the database connection and not indicative of a bigger, prod-only problem!
* adds a mongoid connection option: `retry_writes: false`
It relates to the …

Tell our ruby mongodb connection to not support rewrites

---

Gemfile.lock

CircleCI doesn't seem to support bundler v1 in their buildpacks anymore. Guess how I found this out.
* ran `gem install bundler && bundle update --bundler` to install new bundler gem and rebundle
no views, no issues

set lockfile to use bundler 2 instead of bundler 1

---

Gemfile
Gemfile.lock

Fixed the startup error & hopefully stops the dev email spam! :smile: 
> Single arity template handlers are deprecated” error
* Bumps from 4.2.2, now `coffee-rails ~> `5.0.0`` & then ran `bundle install`
No views changes.
* Fixes #1885

Rails6 Cleanup: Bump coffee-rails to 5.0.0

---

app/views/dashboards/_activity_log.html.erb
app/views/dashboards/_overview.html.erb
config/initializers/render_async.rb

hotfix to make the budget bar show up again, because for some reason this isn't working in prod environments?

explicitly declare turbolinks in render_async calls

---

app/controllers/concerns/budget_bar_calculable.rb
app/helpers/budget_bar_helper.rb
app/helpers/dashboards_helper.rb
app/models/config.rb
test/models/config_test.rb

I rule and have completed some work on Case Manager that's ~ready for review!~
Made the max value of the BudgetBar configurable.
Old  (_number for demo purposes only_)
New (_number for demo purposes only_)
This pull request makes the following changes:  
* Fixes #1883

Configurable BudgetBar Max

---

app/views/dashboards/_activity_log.html.erb
app/views/dashboards/_overview.html.erb

really dunked on myself with this one.
* pass `data-turbolinks-track: reload` in the right spot, so it actually gets passed into `content_for` instead of just disappearing into the void
no views, no issues - this is a hotfix of something I broke in #1890

render_async: move data-turbolinks-track to html options

---

docs/SETUP.md

The link in SETUP.md to YOUR_FIRST_CONTRIBUTION.md wasn't resolving because it had an extra `docs/` in it, so I took that out. 
* Changed the link path

Change path to nice note instructions

---

.gitattributes
docs/SETUP.md

* Added instructions to get docker-compose working on windows
* Fixes #1904

Add instructions to get Docker-compose working on Windows

---

app/models/patient.rb
test/models/patient_test.rb

Heyoo, I updated the `self.pledged_status_summary` method  in `patient.rb` by adding an or query so that the budget bar shows hard pledges sent since the start of the week, as well as soft pledges made that week. Working on writing the test for it! 
* Fixes #1911

fixed budget bar

---

.circleci/config.yml
app/services/clinic_finder/modules/gestation_helper.rb

Paired with #1893 this eliminates an outstanding zeitwerk warning about how it's expecting a module to be defined.
Also add `rails zeitwerk:check` to CI, so we don't accidentally intro new problems, kinda similar to how we're enforcing a bunch of i18n stuff.
Note that this leaves an existing warning with ActionMailer previews, which I've opened an issue about at https://github.com/rails/rails/issues/38156 
* fix existing warning
* add zeitwerk:check to CI
bumps #1876

squelch zeitwerk warning about undefined module

---

app/views/users/edit.html.erb
app/views/users/new.html.erb
config/locales/en.yml
config/locales/es.yml

I added the suggested text about what each role does to the user edit and create pages. Corresponding text is missing for the Spanish localization file, though. 
* Fixes #1868

add information about roles to user edit/creation pages

---

app/views/layouts/_navigation_links.html.erb
test/system/navbar_links_test.rb

I removed the link to the reports from the admin navbar, and the corresponding tests. I kept the reports controller and tests.
* Fixes #1924

update nav_bar and corresponding tests

---

docs/user_guides/CASE_MANAGERS.md
docs/user_guides/GLOSSARY.md
docs/user_guides/README.md

We've needed accessible, neutral docs for a little while, so I'm checking some into github. This adds a CM guide; I'll soon add a data guide, accounting guide, an admin guide, and a sample shift doc, but wanted to stand this up and get it reviewed as soon as possible so we could share it with ext funds.
* Adds a user docs directory
* adds a glossary
* adds a quick walkthru on 
no issues

Add docs directory, glossary, and neutral case manager user guide

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/javascript/packs/application.js
app/javascript/src/turbolinks.js
app/views/configs/_config.html.erb
app/views/layouts/application.html.erb
app/views/patients/_new_patient.html.erb
app/views/users/edit.html.erb
package.json
test/controllers/calls_controller_test.rb
yarn.lock

We're trying to get out of the business of sprockets so we can go full webpack. To that effect, let's use the npm package to manage turbolinks rather than the gem.
* `yarn add turbolinks` plus some config
* remove it from gemfile
* a couple forms are using xhr where they should be using synchronous requests; bump those
* Bumps #1752 kinda

manage turbolinks in webpack

---

app/assets/stylesheets/users.scss
app/javascript/packs/application.scss
app/javascript/packs/styles.scss
app/javascript/styles/_colors.scss
app/javascript/styles/users.scss
app/views/layouts/application.html.erb
config/webpacker.yml

As noted, we want out of sprockets and into webpack - it's a technology more familiar to frontend people, and rails generally is going in that direction. It also opens up a lot of room for us to do cool stuff with js down the line, and move our bootstrap install into webpack.
The next step here is to port over as much of the individual stylesheets as we can, and then bootstrap. Hopefully this is less traumatic than the last time we made big changes to bootstrap.
To prove this works, head to the users index page and play around with the colors in `lines.scss` - change `$daria-gray` to `red` and see what happens. (You may have to `rm -rf node_modules/ && yarn` first)
* …

Make webpack able to load SCSS; port over users.scss as proof of concept

---

app/models/archived_patient.rb

These fields aren't populating - I think it's because `archived patient` is missing a few fields. This adds two of them that I noticed, textable and fund_pledged_at.
This is blocking a deploy so I'm going to smash it.
* add some fields that patient has to archivedpatient
no issues

add fund_pledged_at and textable to archived patients

---

app/models/concerns/exportable.rb

Eager load clinic to avoid an n+1 on CSV export. 
All the other stuff is embedded (which means it doesn't n+1, thankfully).
* eager load clinic
* Fixes #1957 (hopefully)

eager load clinic calls to avoid an n+1 on CSV export

---

docs/INTRO_BLURB.md

Wrote up this quick blurb as something we could easily share as a kind of handout - a 'my friend is interested in DARIA, what can I tell them about your project?' kinda blurb. Thought it would be useful to check into git in case we ever needed it again.
@KatSDC @lomky and @susanjw please review the copy if you don't mind!
* add blurb to docs
no views
no issues

add shareable intro blurb

---

.circleci/config.yml
.docker/Dockerfile
Gemfile
Gemfile.lock

Bump ruby version to 2.6.6. This will squelch a minor vuln that is failing builds.
In the process, the sqreen gem needs an update - one of its deps was failing.
* ruby 2.6.5 -> 2.6.6
* bundle update sqreen
no views
no issues

Bump ruby to 2.6.6

---

Gemfile
Gemfile.lock

jquery-rails has an id'd CVE that we need to deal with to get the build green again.
* pin `jquery-rails`
* `bundle i`
none

bump jquery-rails to squish a vulnerability

---

.docker/Dockerfile

Upgrades to the next LTS version of node (v12). 
* It runs the v12 setup, then installs it.
* It has a dependency on `ca-certificates`. Purging the ahab dependencies that include `ca-certificates` was causing it to remove nodejs as well.
There's no screenshot but locally I get:
```
docker-compose run --rm web node --version
Starting dcaf_case_management_db_1 ... done
v12.16.3
```
* Fixes https://github.com/DCAFEngineering/dcaf_case_management/issues/1952

Add steps to update to node 12

---

app/controllers/patients_controller.rb

This resolves the problem we had with streaming the patients export to a file. Here is my working understanding:
* Rails 6.0.2 took a slightly more aggressive tack about including the `ETag` header; this was not previously included and now it is
* browsers interpret that as caching and it overrules streaming for some reason that is not terribly clear to me
* on our version of rack, it sets a digest to `ETag` unless certain circumstances are met. One of those is an existing key for `ETag` or a key for `Last-Modified`. Take a look at https://github.com/rack/rack/blob/v2.2.2/lib/rack/etag.rb#L29 for the exact lines of code
* we cheat by setting a nil key for `ETag`, which for a reason that is an absolute mystery to …

strip etag header because it breaks streaming if set

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/call_lists.scss
app/assets/stylesheets/configs.scss
app/assets/stylesheets/dashboards.scss
app/assets/stylesheets/external_pledges.scss
app/assets/stylesheets/practical_supports.scss

In prep for moving SCSS to webpacker, clean up what we already have; delete some files with no entries and remove some style definitions that don't appear in our codebase any longer.
I suspect the search bar was just overtaken by a different style, and the navbar stuff is overtaken by bootstrap 4.
* delete empty sprockets scss files
* remove some styles that aren't used
no view changes, but here's the search bar on both a local and sandbox:
local:
sandbox:
* Bumps #1854

Remove unused CSS junk

---

lib/tasks/nightly_cleanup.rake

I added to the nightly_cleanup to delete sessions older than 30 days.
* I've only changed nightly_cleanup.rake
* Fixes #1975 
When testing the rake file, I get the following warning:

delete sessions older than 30 days in nightly_cleanup

---

app.json
docs/onboarding/SETTING_UP_A_NEW_INSTANCE.md

Too much of the new instance provisioning depends on what's in my head or having access to everything I do, so we're rewiring.
As part of this I'm removing the instructions for independent, non-DCAF pipeline setup. That's something we've been discouraging for awhile.
@xmunoz and co will take these for a spin this week, but I'll merge for now and if any changes are required they can pull request against that?
* bump setup instructions to assume much more minimal context
* bump app.json
* Fixes #1982

Improve provisioning instructions

---

app/controllers/accountants_controller.rb
test/controllers/accountants_controller_test.rb

We got a sentry error from the accountants panel - there's an edge case where data can get into such a state where `pledge_sent` is true but there's no `pledge_sent_at` value.
The accountants controller fails in that case because the `sort_by` is trying to compare nils with a real timezone. Mongoid does that a lot better, so we move it to an activerecord call instead.
* handle cases where pledge_sent_at is null for some reason
* add a test
no view change
* Fixes #1970

Swap accountants search to use activerecord calls because they handle nulls more gracefully

---

.github/PULL_REQUEST_TEMPLATE
docs/administering/NOTIFYING_LISTSERV.md

Since people sending the notification emails, doing deploys, etc will be fairly low context pretty soon, let's write up a guide. What I'm thinking is in the PR. I'd like to get buy in on this from @lomky and @harumhelmy .
* Add doc providing guidance on how to write the email
* Bump pull request template to remind reviewer to tag and retitle pull request if necessary
no views
no issues

add instructions so we can start making writing the notification emails easier

---

Gemfile
Gemfile.lock
app/helpers/patients_helper.rb
app/views/clinics/_clinic_form.html.erb
app/views/patients/_patient_information.html.erb
app/views/patients/data_entry.html.erb
test/helpers/patients_helper_test.rb
test/system/clinic_management_test.rb
test/system/data_entry_test.rb
test/system/update_patient_info_test.rb

Cloning over the fork PR #2005 to see if I can get the CircleCI to run on the main fork :angry: 
---
I wasn't sure how to test the data_entry edits (but the clinic and patient views work! see screenshots below) and I also couldn't get the tests to work, but I wrote some code based on what I saw in the files already, so hopefully it works? I haven't tested in Ruby before.
* I switched the state text field to a dropdown menu of state codes
* Switched tests to reflect the same select options
* Fixes #1733 
For reviewer:
* Adjust the title …

State fields are now selectable dropdowns instead of text strings

---

app/controllers/patients_controller.rb
app/models/patient.rb
app/views/patients/data_entry.html.erb
test/system/data_entry_test.rb

Adds the option to manually set the dates of the fund pledge and fulfillment when using the `/data_entry` point, allowing for pledges to be properly back dated when entering a back log, and stopping them from showing up on the budget bar!
* allow params `fund_pledged_at` and `pledge_sent_at` on the patients controller
* update the automatic behavior that sets those fields to gracefully accept a param and otherwise fallback to previous behavior
* Add fields to `/data_entry`
<details><summary>Sandbox testing</summary>
Manual Testing: confirm the behavior when creating on `data_entry` once in sandbox
works | fund_pledged_at | pledge_sent_at | budget bar
-- | -- | -- | …

Editable dates on data entry to allow for backdating

---

app/models/patient.rb
test/controllers/patients_controller_test.rb
test/models/patient_test.rb

Prevents `Patient#confirm_appointment_after_initial_call` from erroring out when `initial_call_date` is `nil` but `appointment_date` is present.
* handles when `initial_call_date` is `nil`
* adds tests to patient controller and model
^^ note error message regarding initial_call_date while appointment_date is present
* Fixes https://github.com/DCAFEngineering/dcaf_case_management/issues/1991
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as …

Fix initial call date validation bug 1991

---

.circleci/config.yml
docker-compose.yml

Once upon a time we would push to a docker remote every time we'd rebuild. We did this because in the very beginning this was faster than docker building every time! But then we (read: @DarthHater ) made us better at docker, and nobody's really setting up or refreshing this codebase with `docker pull` anymore. So let's take out this (very long) buildstep and save ourselves some time.
* remove docker remote refs from circleci build steps and from docker-compose
no issues
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is …

Remove refs to dockerhub from build steps and docker-compose

---

.circleci/config.yml

Seeing if we can't get coverage up and running
* add coverage to the circle config
* 
* Fixes #2024 
For reviewer:
* Tag this PR:

Enable coverage on circleCI

---

config/environments/production.rb

* Updates the mongodb logging level in prod from debug to info
Before:
```
[DEBUG] MONGODB | db:27017 req:1348 conn:1:2 sconn:3 | admin.endSessions | STARTED | {"endSessions"=>[{"id"=><BSON::Binary:0x47016580353280 type=uuid data=0xc707aeb153aa4491...>}], "$db"=>"admin"}
[DEBUG] MONGODB | db:27017 req:1348 | admin.endSessions | SUCCEEDED | 0.000s
[INFO ] Raven 3.0.0 configured not to capture errors: DSN not set
```
After:
```
[INFO ] Raven 3.0.0 configured not to capture errors: DSN not set
[INFO ] Raven 3.0.0 configured not to capture errors: DSN not set
```
* Fixes #2032 
For reviewer:
* Adjust the title to explain what it …

Changes mongodb logging from debug to info

---

config/locales/en.yml
config/locales/es.yml

Adds English and Spanish translation for the patient.attribute.clinic_id
* Fixes #1921 
For reviewer:
* Tag this PR:

Translation of clinic

---

app/assets/stylesheets/application.css.scss

I added the border color from @lomky 's suggestion in #2051 . 
Also looked into "No patients found" color contrast and looks like the text isn't isn't #777777 anymore. Not sure how, but now it is #212529:
* Add border color over-ride
new and improved button border!
* Completes #1704 (hopefully)
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that …

add border color to danger button

---

app/controllers/patients_controller.rb
app/models/patient.rb
app/views/patients/_patient_dashboard.html.erb
app/views/patients/data_entry.html.erb
config/locales/en.yml
config/locales/es.yml
db/seeds.rb
test/system/data_entry_test.rb
test/system/update_patient_info_test.rb

We rule and have completed some work on Case Manager that's ready for review!
Adds the Patient field 'Pronouns' along with the changes in views, controller, tests.
* Adds pronoun field to Patient Model
* Allows pronoun param in Patient Controller
* Added pronoun field to Patient Dashboard View
* Added pronoun field to Data Entry
* Added new field tests for the above views
* Added English & Spanish i18n translations
* Added pronouns to various dev seed data
Page |Before | After
-- | -- | --
Patient Dashboard | ![image](https://user-images.githubusercontent.com/6129479/92998500-0fa0ae00-f4e8-11ea-8e51-10c124750734.png) | …

Creates Pronoun Field for Patients

---

Gemfile.lock

[ai/autoprefixer-rails](https://github.com/ai/autoprefixer-rails/pull/177) is no longer being deprecated! Bump past those deprecation warnings.
For reviewer:
* Tag this PR:

Bumps autoprefixer-rails out of deprecation

---

Gemfile
Gemfile.lock
test/system/filter_medicaid_clinics_test.rb
test/system/filter_naf_clinics_test.rb
test/system/pledge_fulfillment_test.rb

Removes version pin on capybara, bringing it into the present. Makes some insignificant adjustments to get build to pass again.
* capybara to >= v3
* adjustments to accommodate for the breaking changes in capybara v3
* Fixes #2062
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that …

Upgrade capybara to >= 3

---

app/views/user_mailer/account_created.html.erb
app/views/user_mailer/account_created.text.erb

@verbingthenoun asked for this awhile ago - the new account creation welcome email is basically the same one we launched with, and doesn't really have a next step, so people need to have an additional touch with their volunteers. This tries to get ahead of that by including a URL to hit to log in.
The first commit sets things up to include 'reach out to your CM directors or volunteer lead' language, but the second commit includes the actual URL to go to (set as `SITE_URL` as an env var everywhere). 
I'd like @lomky 's opinion on sending the URL out in new account emails and @verbingthenoun 's opinion on the language here.
* bumps the new account email to include a …

Add login URL to account creation email

---

README.md
codecov.yml
test/test_helper.rb

bumps a badge in the readme
* refresh readme badge in circleci
* Bumps #2024 
For reviewer:
* Tag this PR:

point codecov badge on readme to main + fix codecov

---

.circleci/config.yml
.docker/Dockerfile
.gitignore
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/application_record.rb
config/application.rb
config/database.yml
config/initializers/devise.rb
db/migrate/20201119043849_install_pgcrypto.rb
db/migrate/20201120043849_create_versions.rb
db/schema.rb
docker-compose.yml
docs/SETUP.md
test/test_helper.rb

Start the process to roll out postgres by installing pg gems and constructing a migration.
This is pretty much the bare minimum we can do to postgresify, and is intended to separate out the devopsy stuff from actual app work. Everything in here is basically a noop - it adds a postgres instance and a table that is not set up to get used yet. So pretty safe, from a risk perspective.
I added a hobby postgres db to test this on in sandbox. I am not sure how to do the db:create / db:migrate as part of deployment, or if we _should_ do that. Likely when we roll this out for real it should be on grown-up paid dbs though.
* install and configure pg in code
* set up a table …

Add and configure postgres

---

Procfile
app.json

Heroku has a nice feature: in the procfile you can define a release action. We make that `rails db:migrate` here to exec any pending db migrations so the release phase doesn't fail.
We also bump app.json to be postgres instead of mongo. Appropriate since mlab is gone forever. This will only affect new instances.
* run `rails db:migrate` on deploy to heroku
* bump app.json to add pg
* Bumps #2072 
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix …

Execute db:migrate on release phase in heroku + app.json bump

---

app/assets/stylesheets/budget_bar.scss
app/javascript/packs/application.scss
app/javascript/styles/_variables.scss
app/javascript/styles/budget_bar.scss

This ports over the budget bar CSS into webpacker.
In the process, fixes a small css bug - the black text wasn't bubbling up and it was making it hard to read, at least on firefox. (See screenshots.)
* ports budget_bar styling to webpacker
* enforces black text to avoid the color clash with an `!important` directive
Local: 
Sandbox:
* Bumps #1859 
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend …

port budget bar scss to webpacker

---

app/javascript/packs/application.scss
app/javascript/styles/clinic_finder.scss

Move the clinic finders css over to webpacker and out of sprockets. No significant changes necessary to get this to work. I changed a color hexcode to standardize the scheme a bit.
* Port the clinic finder SCSS into webpack
No view changes, as  hex ccc and hex 525252 are similar enough to not be disruptive.
* Bumps #1854 
For reviewer:
* Tag this PR:
* …

Port clinic finder scss to webpack

---

app/assets/stylesheets/application.css.scss
app/javascript/packs/application.scss
app/javascript/styles/_variables.scss
app/javascript/styles/globals.scss

Make a dent in the application.scss file by porting over some of the top-level element styling like html/body/main.
There are a couple spots where this smashes into bootstrap global styles; I figure easiest strategy is to duplicate them for now in both places, mark them as duplicative, and then take them out when we finally remove bootstrap from sprockets. 
* move the global styles out of 
* dupe a few global styles that have to stick around for bootstrap reasons
View diff:
(Note that text styling for h1, general text, and link coloring is the same.)
* Bumps #1854 
For reviewer:
* Adjust the title to explain what it does for the …

port (most) globals to their own webpacker file

---

app.json

The application won't be able to connect to the database without setting this variable as part of the dyno creation process. There might be some other code changes needed to create the db, but I'll defer to you for that.

Explicitly add MONGODB_URI as required config var

---

README.md
docs/ADMINISTRATION_AND_MAINTENANCE_PLAN.md
docs/ADOPTING_DARIA.md
docs/HOW_LINES_WORK.md
docs/PRESS.md
docs/SECURITY_INTRO.md
docs/SETUP.md
docs/TECH_STACK_INTRO.md

Fixes broken links identified by https://github.com/tcort/markdown-link-check
* No issue number, just noticed some broken links as I was preparing to onboard a new fund.
For reviewer:
* Just make sure the links look good!

Fix broken links in documentation

---

app/models/call_list_entry.rb
app/models/concerns/call_listable.rb
lib/tasks/nightly_cleanup.rake
test/models/call_list_entry_test.rb
test/models/user_test.rb

Small unexpected bug around patients being in flight. I have no idea why this happened and why it wasn't handled by callbacks, but worth doing regardless.
* clean orphaned call list 
* add a safety check to pulling order call lists, to filter out anything detached on the spot
* Fixes #2125 
For reviewer:
* Tag this PR: …

handle cases when patients get detached from call list entries

---

.docker/Dockerfile

This unfreezes the Gemfile.lock and upgrades Ahab
* Unfreeze the Gemfile.lock
* Upgrade Ahab
For reviewer:
* Tag this PR:

Unfreeze Gemfile and upgrade Ahab

---

app/controllers/events_controller.rb
app/helpers/events_helper.rb
app/models/call.rb
app/models/event.rb
app/models/mongo_event.rb
app/models/patient.rb
db/migrate/20201212010730_create_events.rb
db/schema.rb
lib/tasks/migrate_to_pg.rake
test/factories/event.rb
test/helpers/events_helper_test.rb
test/models/event_test.rb

This ports over the Event model into Postgres, including a rake task to get things out of Mongo.
To verify:
* check out main and do a fresh `rails db:seed`, then log in and head to the CM dashboard. Nice lookin' events there down at the bottom. Take a screencap of the first few for reference
* Check out this branch and do `rails db:migrate` to move to the new branch. Reload the CM dashboard and confirm that the events disappear
* Run `rails migrate_to_pg:event` to port over data cleanly, then reload the CM dashboard and see your events show back up
* Log a call on a patient by clicking the phone icon and then Left voicemail. Doesn't matter which one. Reload the page and observe the new event showing up - this …

Port Event model over to postgres

---

Gemfile.lock

CI builds failing on the codecov step - let's see if bumping the lib fixes things
* `bundle update codecov`
no views
no issues
For reviewer:
* Tag this PR:

bump codecov gem to try and kill mysterious build failures

---

app/controllers/clinics_controller.rb
app/controllers/patients_controller.rb
app/controllers/users_controller.rb
test/models/audit_trail_test.rb

Pulling this out of the larger mongo -> pg work - Rails is deprecating update_attributes in favor of update per https://github.com/rails/rails/pull/31998 and this takes these out of our codebase in favor of `update`.
* replace `update_attributes` with just `update`
* stems from #2072 
For reviewer:
* Tag this PR: …

Swap in `update` for `update_attributes`

---

test/system/voicemail_preference_in_call_modal_test.rb

Realized that #2117 is likely the same issue as #2099, so added the same retry fix.
* retries flaky tests in voicemail preferences
* Fixes #X
* Bumps #Y
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that …

optional retry for flaky voicemail test

---

app/models/concerns/callable.rb
test/models/external_pledge_test.rb
test/models/patient_test.rb

Two iso'd and severable changed here from larger postgres work.
* `Patient#contacted_since` is no longer in the codebase and the method hasn't been touched in four years, which I'm guessing is when we moved everything to concerns. I can't think of a place where this is used so I think we can nuke it.
* simplifies `ExternalPledgeTest` around uniqueness in fund.
* remove an OBE `PatientTest` around line scoping.
* Bumps #2072  (loosely)
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is …

Remove an unused method + small unit test improvements

---

app/controllers/clinics_controller.rb
app/helpers/patients_helper.rb
app/javascript/src/clinics.js
test/helpers/patients_helper_test.rb

Small quality of life improvement here getting extracted from mongo/pg - rather than making an api call and mapping results on checkbox click, do it in view, assign as data attributes, and then read those data attributes on the fly.
* take out the calls to clinics index endpoint
* instead, load up medicaid/naf as data attributes on selects
* for good measure, make it so you can't select the INACTIVE option
no real view changes
* stems from #2072 
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is …

Load clinic medicaid/naf info on page load rather than through api call

---

app/views/configs/_config.html.erb

Rather than display config options as a list with weird arrays, now display them as selects.
* Displays options as a dropdown, not a text-list of items.
* For arrays (of the form `[display, internal]`) show only the first element. We don't care about internal representation here.
* Ignore `nil` elements (some fields allow empty values, but we don't need to show that here). 
For reference, this is what the new view code is:
```html
<div class="col" id="language_options_list">
<label>Current options are:</label>
<br>
<select>
<option>English</option>
<option>Spanish</option>
<option>French</option>
<option>Korean</option>
</select>
</div>
```
(before it was just each …

turned list of options into a select!

---

Gemfile
Gemfile.lock
package.json
yarn.lock

*  This is an attempt to resolve some of the dependabot alerts.
Unfortuantely webpacker 6 is still pre-release, and all of the alerts
are for transitive dependencies of webpacker. Still, a general upgrade
is always worthwhile.
For reviewer:
* If it builds green, it's probably fine.

Upgrade webpacker

---

.docker/Dockerfile
Gemfile
Gemfile.lock
docker-compose.yml
docs/SETUP.md

This happened: https://dev.to/cseeman/what-s-up-with-mimemagic-breaking-everything-he1 
and as a result the mimemagic version we were on got yanked. This moves to a version that exists. The version that exists unfortunately requires pulling in an external dependency, so we adjust the setup instructions too.
* `bundle update mimemagic`
* adjusts setup instructions / dockerfile to add an extra dependency
fixes #2154 along the way 
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in …

update mime gem to avoid a rails left-pad style mess

---

.docker/Dockerfile

`shared-mime-info` needs to be an APP dependency not BUILD, in dockerfile.
* Fixes #2158 
* Bumps #Y
For reviewer:
* Tag this PR:
* If it contains neither, …

move shared mime info

---

app/lib/paper_trail_version.rb
app/models/concerns/history_trackable.rb
app/models/concerns/paper_trailable.rb
test/application_system_test_case.rb
test/models/paper_trail_version_test.rb

We start here by subbing in PaperTrail, the versioning system, for Mongo's AuditTrail.
Tests require a few dependent objects (user and patient specifically) so I did not turn on the tests, but this is as good a place to start as any.
I don't think there's a good way to try this out or otherwise test drive it, so I would recommend reviewing just by looking at the code.
* Remove mongo AuditTrail
* Integrate PaperTrail in as much as we can without having papertrailable stuff yet
no view change
* Bumps #2072 
For reviewer:
* Tag this PR:
* …

PG: Substitute PaperTrail in for mongo AuditTrail

---

app/models/patient.rb
app/views/patients/_patient_information.html.erb
db/seeds.rb
test/models/patient_test.rb
test/system/update_patient_info_test.rb

Patient zipcode field is now a string; validation has been added to prevent issues.
* Changed zipcode datatype
* Added frontend + backend validation
* Added test to the patient model
* Fixes #2131 
For reviewer:
* Tag this PR:
* `dependencies` if it contains …

change zipcode to string + validate

---

app/views/layouts/application.html.erb

Adds a header for google site verification, so we can pass domain auth with goog.
* adds a header. nothing fancy tbh
no view change
* Bumps #2120 
For reviewer:
* Tag this PR:
* If it contains neither, …

add header for google site verification

---

app/controllers/patients_controller.rb
app/helpers/change_log_helper.rb
app/models/concerns/patient_searchable.rb
app/models/mongo_patient.rb
app/models/patient.rb
config/locales/en.yml
config/locales/es.yml
db/migrate/20210410151149_create_patients.rb
db/schema.rb
lib/tasks/migrate_to_pg.rake
test/factories/patient.rb
test/helpers/change_log_helper_test.rb
test/models/paper_trail_version_test.rb
test/models/patient/exportable_test.rb
test/models/patient/last_menstrual_period_measureable_test.rb
test/system/change_log_test.rb

I wrote part of this while I was sick, but was mostly copying code from #2123 so it should be cool. This ports over the patient model diffs, not including stuff that involves subobjects.
rails t and `rails db:drop db:create db:migrate` still work!
* port Patient model
* Bumps #2072 
For reviewer:
* Tag this PR: …

PG: port patient model

---

package.json
yarn.lock

* Title says it all
* Dependabot alert

Upgrade webpack-dev-server, which also upgrades sockjs

---

docs/administering/SETTING_UP_A_NEW_INSTANCE.md

@xmunoz ID'd a problem in docs when doing some testing - not clear what a scratch password on instance setup should be. This bumps docs to make that a bit more straightforward, and makes it a plug-and-chug snippet. Thanks much to @xmunoz for calling this out!
* improves the snippet to generate an alphanumeric
* Fixes #2175 
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or …

Improve new instance setup instructions around user generation

---

app/assets/javascripts/patients.coffee
app/controllers/patients_controller.rb
app/models/fulfillment.rb
app/models/mongo_fulfillment.rb
app/views/patients/_fulfillment.html.erb
db/migrate/20210410151149_create_patients.rb
db/migrate/20210415015227_create_fulfillment.rb
db/schema.rb
lib/tasks/migrate_to_pg.rake
test/factories/fulfillment.rb
test/models/fulfillment_test.rb
test/system/update_patient_info_test.rb

Port Fulfillment to pg. This should let us cleanly init patient objects again.
Try out the migration script:
```
git checkout pg-fulfillment && rails db:migrate
rails migrate_to_pg:clinic_user_patient
rails c
Fulfillment.where(fulfilled: true).count
```
* `Patient` model to pg
no view change
* Bumps #2072
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, …

PG: Port fulfillment model

---

app/controllers/configs_controller.rb
app/helpers/footer_helper.rb
app/helpers/navbar_helper.rb
app/helpers/practical_supports_helper.rb
app/models/config.rb
app/services/uri_service.rb
config/locales/en.yml
config/locales/es.yml
test/helpers/navbar_helper_test.rb
test/helpers/practical_supports_helper_test.rb
test/models/config_test.rb
test/services/uri_service_test.rb
test/system/updating_configs_test.rb

Config URLs were previously not being handled in a super reliable way. Only `fax service` had any validation whatsoever, using the `UriService` class. I have revamped the URL validation (to do it at config-save time, rather than page-render time) and added it to all URLs.
* Removes usage of `UriService` (can probably delete this file)
* Adds a validator in the Config model for all fields that are tagged as URLs, using the built-in Ruby URI class.
* Converts all URLs into `https://`, and tries to add schemes to schemeless URLs (i.e. you can enter `www.example.com`, which is _technically_ not a valid URL, and makes it `https://www.example.com`.
It relates to the …

Updated URL handling in Configs

---

app/controllers/calls_controller.rb
app/helpers/calls_helper.rb
app/lib/reporting/patient.rb
app/models/call.rb
app/models/concerns/callable.rb
app/models/concerns/exportable.rb
app/models/concerns/statusable.rb
app/models/mongo_call.rb
app/views/patients/_call_log.html.erb
config/locales/en.yml
config/locales/es.yml
db/migrate/20210426033002_create_calls.rb
db/schema.rb
db/seeds.rb
lib/tasks/create_fake_data.rake
lib/tasks/migrate_to_pg.rake
test/controllers/calls_controller_test.rb
test/factories/call.rb
test/lib/reporting/patient_test.rb
test/models/archived_patient_test.rb
test/models/call_test.rb
test/models/patient/statusable_test.rb
test/models/patient_test.rb
test/models/user_test.rb
test/system/table_content_test.rb

Port Call to pg. Should let us log calls again and contains a proof of concept for porting over an embeds many submodel. After this, we'll do CallList and be able to look at pages again finally.
Try it out:
```
git checkout pg-call && rails db:migrate
rails migrate_to_pg:clinic_user_patient
rails c
Call.count # 141
```
I think I might be mishandling 'couldnt_reach_patient' statuses but we can kick this up for rev regardless.
* port Call to pg
no view
* Bumps #2072 
For reviewer:
* …

Portl Call model to pg

---

app/controllers/application_controller.rb
app/controllers/call_lists_controller.rb
app/models/call_list_entry.rb
app/models/concerns/call_listable.rb
app/models/mongo_call_list_entry.rb
app/models/user.rb
app/views/devise/sessions/new.html.erb
db/migrate/20210502050214_create_call_list_entries.rb
db/schema.rb
lib/tasks/migrate_to_pg.rake
lib/tasks/nightly_cleanup.rake
test/controllers/call_lists_controller_test.rb
test/models/call_list_entry_test.rb

Merge over Call List stuff.
We are almost back to being able to load the call list - still need notes, but getting ever closer!
To test:
```
git checkout pg-calllist && rails db:migrate migrate_to_pg:clinic_user_patient
rails c
CallListEntry.count # => 6
```
* migrate call list entry model
* Bumps #2072
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend …

Migrate Call List Entry model

---

app/assets/stylesheets/application.css.scss
app/javascript/packs/application.scss
app/javascript/styles/footer.scss

Picking up this piece again! This moves footer styling out of sprockets and into webpack. Not too intensive.
* moves footer styling out of sprockets and into a webpack module
no view changes, but you can try it out by increasing `.logo`'s height to 900 or something and then seeing it make the footer images huge.
* Bumps #1854 
For reviewer:
* Tag this PR:
* …

Port footer SCSS to webpack

---

app/models/mongo_note.rb
app/models/note.rb
app/views/notes/_notes_table.html.erb
app/views/patients/_notes.html.erb
db/migrate/20210503043154_create_notes.rb
db/schema.rb
lib/tasks/migrate_to_pg.rake
test/controllers/notes_controller_test.rb
test/factories/note.rb
test/helpers/notes_helper_test.rb
test/models/note_test.rb

This is it! This is the one that lets us log in cleanly again. You can run `rails s` and log in, and do some basic call stuff like logging them, moving patients around in the call list, etc.
test the migration via:
```
git checkout pg-note && rails db:migrate migrate_to_pg:clinic_user_patient
rails c
Note.count # 17
```
or, you could load up the main page I guess, and see the notes section in the call list.
* Port Note model to pg
* Bumps #2072 
For reviewer:
* Tag …

Migrate Note to PG

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/patients.scss
app/javascript/packs/application.scss
app/javascript/styles/modals.scss
app/views/calls/_new_call.html.erb
app/views/dashboards/_modal.html.erb

Ports over styling around modals out of sprockets and into webpack.
* port over modal styling overrides into their own webpack module
* delete some unused or ineffective styling that doesn't actually take effect anymore (see comments) 
* Bumps #1854 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. …

Move modal styling into webpack

---

app/controllers/practical_supports_controller.rb
app/models/mongo_practical_support.rb
app/models/practical_support.rb
db/migrate/20210509191049_create_practical_supports.rb
db/schema.rb
lib/tasks/migrate_to_pg.rake
test/controllers/practical_supports_controller_test.rb
test/factories/practical_support.rb
test/models/practical_support_test.rb
test/system/practical_support_behaviors_test.rb

Ports practical support and associated logic to postgres.
There's no practical supports in the seedfile, so you'll need to create some manually, unfortunately:
```
echo "Patient.first.practical_supports.create source: 'Metallica Abortion Fund', support_type: 'Transportation', created_by: User.first" | rails c
echo "Patient.last.practical_supports.create source: 'Metallica Abortion Fund', support_type: 'Transportation', created_by: User.first" | rails c
git checkout pg-psup && rails db:migrate migrate_to_pg:clinic_user_patient
echo "PracticalSupport.count" # 2
```
* Port PracticalSupport model to pg
no …

Port practical support model to pg

---

.circleci/config.yml
Gemfile
Gemfile.lock
app/views/devise/shared/_links.html.erb

* upgrade omniauth-google-oauth2
* upgrade devise
* explicitly add new dependency: [omniauth-rails_csrf_protection](https://github.com/cookpad/omniauth-rails_csrf_protection) (reason: https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0#rails)
* Fixes #2141 
For reviewer:
* When this is ready, I will remove the `WIP` prefix from the PR title and assign reviewers.
* I will create user accounts for the reviewers on sandbox.
* I will deploy this branch to sandbox, temporarily hijacking the normal release flow for testing purposes.
* Reviewers will try to sign in with Google to confirm that the change works.

Upgrade omniauth-google-oauth2 to 0.8.1, fixes #2141

---

app/controllers/external_pledges_controller.rb
app/models/external_pledge.rb
app/models/mongo_external_pledge.rb
app/views/external_pledges/create.js.erb
app/views/patients/_abortion_information.html.erb
db/migrate/20210511010317_create_external_pledges.rb
db/schema.rb
lib/tasks/migrate_to_pg.rake
test/controllers/external_pledges_controller_test.rb
test/factories/external_pledge.rb
test/helpers/external_pledges_helper_test.rb
test/models/external_pledge_test.rb

Migrate the ExternalPledge model to postgres.
The patient edit page isn't _quite_ up to speed with this - looks like there are a few small changes we'll need to make in addition. I'll leave those for a separate PR to keep this one reasonably scoped.
To test:
```
git checkout pg-extp && rails db:migrate migrate_to_pg:clinic_user_patient
echo "ExternalPledge.count" | rails c # 2
```
* port ExternalPledge to postgres
* Bumps #2072 
For reviewer:
* Tag this PR:
* …

Migrate external pledge to pg

---

app/assets/stylesheets/application.css.scss
app/javascript/packs/application.scss
app/javascript/styles/_variables.scss
app/javascript/styles/forms.scss
app/javascript/styles/globals.scss
app/javascript/styles/patient_edit.scss
app/views/patients/_pledge.html.erb

Ports over the still relevant form scss from webpack; also removes a couple things from the bootstrap 3 era that aren't relevant anymore. (see inline notes)
* ports form-related scss to its own module, or the appropriate patient module
* deletes some old webpack 3 styling
* Bumps #1854 
For reviewer:
* Tag this PR: …

port over form related scss, delete some old bootstrap3 artifacts

---

app/models/archived_patient.rb
app/models/mongo_archived_patient.rb
db/migrate/20210524020019_create_archived_patients.rb
db/schema.rb
lib/tasks/migrate_to_pg.rake
test/factories/archived_patient.rb
test/models/archived_patient_test.rb

Port over ArchivedPatient model and the associated goods.
To test, you can just do the migration stuff:
```
git checkout pg-archived-pt && rails db:migrate migrate_to_pg:clinic_user_patient
```
Should yield the following:
```
4 Clinic migrated to pg
3 User migrated to pg
39 Patient migrated to pg
4 ArchivedPatient migrated to pg
39 Fulfillment migrated to pg
141 calls migrated to pg
0 practical_supports migrated to pg
2 external_pledges migrated to pg
43 Fulfillment migrated to pg
149 calls migrated to pg
0 practical_supports migrated to pg
2 external_pledges migrated to pg
6 CallListEntry migrated to pg
17 notes migrated to pg
```
After this, we're …

Port ArchivedPatient to pg

---

app/models/config.rb
app/models/patient.rb
test/models/config_test.rb
test/models/patient_test.rb

Adds config for custom patient-archive timelines.
* Adds new configs with bounds-checking
* Replaces constants in patient model with those custom values
*new configs*
* Fixes #2150 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package …

Add archive configs

---

app/helpers/patients_helper.rb
config/locales/en.yml
config/locales/es.yml
test/helpers/patients_helper_test.rb
test/system/filter_medicaid_clinics_test.rb
test/system/filter_naf_clinics_test.rb

* Adds clinic city, state to the drop-down in "Patient/edit" > "Abortion Information"
* Resolves #2188

Adds a clinic's city & state to the clinic dropdown

---

.rubocop.yml
Gemfile
Gemfile.lock

Minor changes to configs to allow `rubocop` to run locally.
After `bundle install`ing, run `rubocop [files...]` (or `docker-compose run --rm web rubocop [files...]`). With no arguments, checks everything, and there are a lot of suggestions! I think this will mostly be useful to look at *new* changes: you could use `git diff --name-only main` to get a list of ruby files changed on this branch, so
```
docker-compose run --rm web rubocop `git diff --name-only main *.rb`
```
I know we're not planning on doing a full re-lint of the codebase, but this might help, moving forward, to be able to keep things up to spec!
Open to comments/config changes/doc suggestions.
* …

Allow rubocop to run locally

---

app/controllers/accountants_controller.rb
app/controllers/configs_controller.rb
app/controllers/dashboards_controller.rb
app/controllers/patients_controller.rb
app/models/concerns/call_listable.rb
lib/tasks/migrate_to_pg.rake

* Mark a few places where n+1 joins are taking place - we used to get this for free from the mongodb document model and now we extremely don't. This is fine for now since we don't do that much traffic, but we should try and resolve after we get this into production. as noted this will be a good @elimbaum shaped ticket
* fix a few n+1 joins on the accountants page as a proof of concept
* fix patient ids on events - since they get numeric ids now, we need to bump them from the BSON IDs
* Bumps #2072 
For reviewer:
* Tag this PR:
* `feature` if …

Migrate events as part of pg; log places where n+1 queries will crop up for future work

---

db/seeds.rb

Fix up seedfile to be pg-friendly.
* fix seeds to run in postgres
Test by:
```
git checkout pg-seed
rails db:drop db:create db:migrate db:seed # should complete
rails c
Patient.find_by(name: 'Patient 0').created_by.name #  testuser2
Patient.find_by(name: 'Other Contact info - 1').created_by.name # testuser
```
* Bumps #2072 
For reviewer:
* Tag this PR:
* …

Adjust seedfile to postgres

---

app/controllers/dashboards_controller.rb
app/views/patients/update.js.erb

Final pg fixes before showtime, to address issues that got ID'd by user tests (thank you @lomky  for leading that effort!). A couple things got punted to post-postgres.
* fix the js that updates the 'This patient will be audited on' text
* check presence on patient search to disallow returning random results. this was current behavior and would just return 15 random records, but I agree that this isn't great and now's a good time to nip it in the bud
* Bumps #2072 
For reviewer:
* Tag this PR:
* `feature` if it contains a …

Final postgres fixes before showtime

---

app/views/users/search.js.erb

Made the user search nil response friendly. Based on Sentry alert:
```
Exception
NoMethodError: undefined method `any?' for nil:NilClass
app/views/users/search.js.erb:1:in `_app_views_users_search_js_erb__235396535284795989_968060'
<% if @results.any? %>
...
(133 additional frame(s) were not displayed)
ActionView::Template::Error: undefined method `any?' for nil:NilClass
```
* Cleaner `nil` handling for if you search for users with only whitespace
You can recreate the error:
- checkout main
- navigate to user management
- search for a space, boom, error
Checkout this branch and do it again - no error!
For reviewer: …

Fix user search bug causing errors if no results are found

---

Gemfile
Gemfile.lock

Since we don't do any mongoid queries anymore, we can strip the mongoid-kaminari gem and just leave regular kaminari.
* remove `mongoid-kaminari` gem
* Fixes #2237 
For reviewer:
* Tag this PR:
* If it …

remove kaminari-mongoid gem

---

Procfile
app.json
docker-compose.yml
test/test_helper.rb

Remove a couple of mongo refs from tests, release commands, and docker. (In part because I want to see if this builds independently.)
* Remove mongo refs from tests, release commands, and Docker
* Bumps #2072 
For reviewer:
* Tag this PR: …

remove mongo refs from tests, release commands, and docker

---

app/controllers/clinicfinders_controller.rb

I did a PG conversion! 🎉 
* down with `nin`, long live `.not`
This is one place where our tests don't fully exercise the code - I temporarily set my local env `GOOGLE_GEO_API_KEY` to the staging value and confirmed correct behavior.
* Fixes #2226 
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or …

Converts clinicfinder controller to postgres

---

app/assets/stylesheets/application.css.scss
app/javascript/packs/application.scss
app/javascript/styles/_variables.scss
app/javascript/styles/buttons.scss

Port button styling into webpack. Still gotta do a little additional tidying, but this means almost all our custom code is ported.
* Port button styling into webpack
screencaps posted inline
* Bumps #1859 
For reviewer:
* Tag this PR: …

Port button styling into webpack

---

app/models/patient.rb
test/system/data_entry_test.rb

* Make behavior consistent with `update_fund_pledge_at`
* Fixes #2019 
For reviewer:
* Tag this PR:

Fix - Updating update_pledge_sent_by_sent_at  save for consistency

---

.docker/Dockerfile
test/application_system_test_case.rb

This PR installs firefox inside the docker container, allowing system tests to be run locally.
I attempted to install Chrome, to match CircleCI, but ran into a bunch of issues with running it headlessly. FIrefox works out of the box.
⚠️ **Warning!** I was able to run individual system tests with no issues, but running the entire suite hung my computer terribly (adjusted load averages ~4). This was on a 3.3GHz 8-core machine with 8GB RAM that I was only using for DARIA work. YMMV.
* installs firefox
* uses firefox for system tests if running in docker.
* this should not break existing functionality, specifically, running system tests on bare metal
(If there are …

Allow system tests to run in local docker

---

Gemfile
Gemfile.lock

Got a warning that this was not compat with papertrail at version 10, so upgrading to see if that squelches the issue. Also, might as well keep our libs fresh!
* bundle update paper_trail
* bumps #2251 
For reviewer:
* Tag this PR:
* `dependencies` if it contains …

bump papertrail gem to v12

---

.circleci/config.yml

CI started failing because of some work on the debian repository side that's way out of our purview; apt-get update brings things up to speed.
* add an `apt-get update` to our circle.yml config
no issues
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package …

CI fix - get build green by running an apt-get update

---

app/lib/paper_trail_version.rb
db/migrate/20210618205056_remove_mongo_id_columns.rb
db/schema.rb

Don't merge until EOM, but this drops the mongo id tables, thereby nuking our last vestige of mongo.
* remove mongo_id columns
* Bumps #2072 
For reviewer:
* Tag this PR:
* If it …

remove mongo_id from tables

---

app/models/concerns/urgency.rb
test/models/patient_test.rb
test/system/submit_pledge_test.rb

A few funds have reported that postgres caused a slight change in how urgency works, and that they can no longer mark patients with sent pledges urgent. That was original intent, but funds are used to the not-quite-right version, so this PR implements the not-quite-right version. (I think the source of this is callbacks working slightly differently in activerecord than in mongoid, but exact details aren't that important, I don't think.)
* remove pledge_sent from unmark-urgency criteria
* Fixes #2262
For reviewer:
* Tag this PR: …

Allow patients with sent pledges to be marked urgent again

---

.github/dependabot.yml
Gemfile
Gemfile.lock

* Adds default reviewers to dependabot PRs
* Update jquery-rails so CI passes

Add dependabot config to autoassign reviewers

---

Gemfile
Gemfile.lock

Dependabot tried to bump bootstrap; upgrading bootstrap is very very hard; we'll pin it for now to make it clear that we don't want to do this.
* pin bootstrap gem below 5
no views
no issues
For reviewer:
* Tag this PR:
* If it contains …

pin bootstrap gem to < 5

---

app/views/dashboards/search.js.erb
config/locales/en.yml
config/locales/es.yml
test/system/record_lookup_test.rb

* Adding "quick add" button for search when there are results.
(with results)
(without results)
* Bumps #2173 
For reviewer:
* Tag this PR:

Adding "quick add" button for search when there are results.

---

db/migrate/20210725025609_add_index_to_config_key.rb
db/schema.rb
test/models/config_test.rb

1) Requires uniqueness of configkey at the db level
2) adds spec
It relates to the following issue #s:
#2227

Enforce config key uniqueness to avoid weird errors when changing fund configs in the Config panel

---

test/controllers/users_controller_test.rb

This hack-fixes a problem ID'd by @xmunoz - the create user controller test occasionally fails for no real reason, about one out of every four times. This is cheating a little, but it's a pattern we've adopted in a few other spots - by having the test class extend MiniTest::OptionalRetry, we'll retry failed tests in that class again up to 3 times before calling it a wash officially. Since this is a problem that seems to be primarily limited to CI (and possibly test parallelization), and we've never once gotten a sentry error about it, I think the hacky/brute forcey method is probably fine here.
* drop in the auto-retry module to deal with this flaky test
no view …

autoretry failures on the flaky create user test

---

app/helpers/welcome_message_helper.rb

* I added a nice message to `welcome_message_helper.rb`
* Bumps #884 
For reviewer:
* Tag this PR:

Nice message from lperson

---

app/helpers/tooltips_helper.rb
app/models/concerns/urgency.rb
app/models/config.rb
config/locales/en.yml
config/locales/es.yml
docs/user_guides/CASE_MANAGERS.md
test/models/config_test.rb
test/models/patient_test.rb

* Adds the Urgent Reset config, default to 6
* Uses the config instead of hard-coded 6
* Adds tests
* docs
* config alt text
* Urgent `?` tool tip
* Fixes #2338 
* Fixes #2322 
For reviewer:
* Tag this PR: …

Configurable Urgent Reset Window Config

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
config/initializers/filter_parameter_logging.rb
config/initializers/sentry.rb

Following the migration guide at https://docs.sentry.io/platforms/ruby/migration/ , bump sentry-raven into sentry-ruby, the new sdk. See a couple inline notes.
* swap `sentry-raven` out for `sentry-ruby`/`sentry-rails` and bundle i
* a few place changes per the upgrade guide
* Fixes #2342
* Fixes #2293 
For reviewer:
* Tag this PR:
* …

bump sentry-raven into sentry-ruby

---

README.md

* Removed the CircleCI badge
* Added a Github Actions badge ([ref](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge))
* Fixed CodeCov's URL for our new org name
* Removed Microbadger - [they shutdown](https://web.archive.org/web/20210214204934/https://microbadger.com/shutdown)
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend …

Fix the CI Readme Badges

---

README.md

One last not-github reference to s/DCAFEngineering/DARIAEngineering/
Searched the codebase for any others. All remaining should redirect cleanly.
* Fixes #X
* Bumps #Y
For reviewer:
* Tag this PR:

Fix missed DCAFEngineering

---

Gemfile
Gemfile.lock

Pretty much what it says on the label - we had a build on heroku fail because rexml is no longer a standard dependency in ruby 3.
(Have verified that this solves the deploy failure!)
* explicitly add rexml gem
no views
no issues - hotfix
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile …

re-add rexml, which is needed for bootsnap to fire up

---

Gemfile.lock
babel.config.js
package.json
yarn.lock

build is sad currently and it's webpack related; hopefully flattening and resetting things up fixes it up.
* `bundle update webpacker && rails webpacker:install` and then some selective plucking from the diffs
no issues
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update …

Update webpacker gem so build passes again

---

.github/workflows/test_dev_env.yml

We should always preserve the coverage artifacts. The screenshot artifacts, however, should only get stored when a job fails. Follow up from #2436

Conditionally run artifact storage steps in test job

---

app.json
app/views/patients/_pledge.html.erb
test/system/event_log_interaction_test.rb
test/system/submit_pledge_test.rb

We store this on the model now, so we should use it, eh?
(Note that 'default' in the test is a deliberate choice, coming soon!)
* use model attribute instead of env var for displaying pledge generator
* Fixes #2439
For reviewer:
* Tag this PR: …

Use model attribute rather than env var for pledge generation

---

app.json
config/environments/production.rb
config/initializers/content_security_policy.rb

for multitenant, we need to be able to point the asset loader at a particular url; this lets us do that via environment variable, with a fallback to current behavior.
(This is because otherwise in a multitenant environment it'll try to point it at a domain that isn't set up.)
* lets us dynamically set up asset urls for multitenant envs
* Bumps #1817 
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, …

declare asset site url specifically via env var

---

app/views/patients/_abortion_information.html.erb
app/views/patients/_fulfillment.html.erb
app/views/patients/_patient_dashboard.html.erb
app/views/patients/_patient_information.html.erb
app/views/patients/_pledge.html.erb

In certain cases, when I load a patient edit page I'm getting forms that POST to the patient route rather than PATCH (which causes failures). This is because method is set to a CSRF token, for some reason I cannot fathom - maybe a rails_bootstrap_form behavior or something? See:
Here's what it should look like (note the proper hidden field `_method` value):
I have no idea why this is doing this, but explicitly declaring method seems to resolve for me in firefox.
* explicitly declare method=patch on patient edit page forms
no issues
For reviewer:
* Tag this PR:
* …

Explicitly declare form methods on patient edit page because for some reason they're trying to POST sometimes

---

app/controllers/application_controller.rb

Hopefully one of the last bits of multitenant - this redirects to new urls if an env var is set. Plan is to temporarily keep the urls up for a month or two while people get used to the new one.
To test, `export REDIRECT_DESTINATION='https://www.google.com' and then try loading the app, and see yourself redirected.
* add REDIRECT_DESTINATION env var that will send people to new domains when they're set up
* Bumps #1817
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that …

redirect an env var is set, to point legacy systems to new urls

---

db/seeds.rb

* Adds a couple practical supports to patients created while seeding the test database for improved dev experience.
* Fixes #[2193 ](https://github.com/DARIAEngineering/dcaf_case_management/issues/2193)
To test:
* Run `docker-compose run --rm web rails db:create db:migrate db:seed` to seed/re-seed your db.
* Then open a Rails console and run `PracticalSupport.all`. You should get back a non-empty array of practical supports.

add practical supports to db seed data

---

.github/workflows/test_dev_env.yml

We stopped codecoving when we moved to github actions in #2361 - this (hopefully) restores it.
* add codecov step to CI
no views
* Fixes #2401 
For reviewer:
* Tag this PR:
* If it contains neither, no …

re-add codecov step to ci

---

db/seeds.rb

couple of changes to make sandbox generic
* Remove references to DCAF in seedfile
* bumps #1817 
For reviewer:
* Tag this PR:

remove refs to DCAF in seedfile

---

app/views/devise/mailer/reset_password_instructions.html.erb

minor bug when testing password reset in new env, with an easy fix - add subdomain arg to reset url
* add subdomain arg to password reset url
no view changes, )though the password reset screen is ugmo)
* Bumps #1817 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such …

add subdomain to password reset url

---

app/models/archived_patient.rb
test/models/archived_patient_test.rb

a little embarrassing to not see this before, but that's what working too much gets you. This takes the object-ref-swap approach we have in here now and applies it to fulfillment as well. It is _super_ weird that tests didn't catch this.
to try it out from a fresh seed:
```
ActsAsTenant.current_tenant = Fund.first
Patient.count # 39
ArchivedPatient.count # 0
ArchivedPatient.archive_eligible_patients!
Patient.count # 37
ArchivedPatient.count # 2
```
* copy over fulfillment obj when archiving
* Fixes #2423
For reviewer:
* Tag …

Fix patient archiving - swap ref on the the fulfillment obj like we do the others

---

app/models/concerns/exportable.rb

Lines is a model now; we didn't fix it in the export though, so it's showing up as the obj. This fixes that and displays the name instead.
* treat Line like a model rather than  a db field in export, so it properly displays
no view change
* Fixes #2458 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is …

display line name rather than line, since this is a model now

---

.github/workflows/test_dev_env.yml

CI is [failing](https://github.com/DARIAEngineering/dcaf_case_management/runs/4771259669?check_suite_focus=true) on main, and this should fix why.

Prepend bundle exec to ruby-audit run by CI

---

db/seeds.rb

For just about forever I've been meaning to add @lwaldsc 's scenarios into the seedfile. It's time. I'll be doing this incrementally I think since it is slightly time consuming.
* add two scenarios from the realistic patient mocks scenarios
* Bumps #814 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or …

add two of @lwaldsc scenarios

---

config/initializers/new_framework_defaults_6_1.rb

Set the ssl redirect 308 status code configuration.
[here's the rails PR about this config - pretty safe for our purposes](https://github.com/rails/rails/issues/39654)
* that thing
* Bumps #2462 
For reviewer:
* Tag this PR: …

Road to rails 7: turn on 308 redirect status

---

.github/workflows/test_dev_env.yml
package.json
yarn.lock

Add yarn-audit back to CI, and squash a vuln that it identified
* add yarn-audit back to ci
* yarn up set-value
no vie wchanges
* Fixes #1665 
For reviewer:
* Tag this PR:
* If it contains neither, no …

Restore yarn audit

---

.github/workflows/test_dev_env.yml
README.md

no more codecov, this is too annoying to fix for what we get out of it
* remove codecov refs
no view changes 
* Fixes #2401 (by not fixing it)
For reviewer:
* Tag this PR:
* If it contains neither, no …

remove codecov references because I am mad at it

---

config/initializers/new_framework_defaults_6_1.rb

Turn on urlsafe_csrf_token setting in 6.1 default. Since we don't do any black magic with csrf tokens this winds up being clean.
* turn on the `urlsafe_csrf_token` setting in 6.1 default
* Bumps #2462 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such …

Road to rails 7: turn on urlsafe_csrf_tokens

---

docs/TECH_STACK_INTRO.md
docs/administering/DEPLOYMENT.md

Add a CI/deployment process explanation to the docs
* add a CI/deployment process explanation to the docs
no views
* Fixes #2363
For reviewer:
* Tag this PR:
* If it contains neither, no need to tag …

add deployment/ci explanation to docs

---

Gemfile
Gemfile.lock

Build on main is currently red. This is why:
```
ruby-advisory-db:
advisories:	545 advisories
last updated:	2022-02-21 11:49:31 -0800
commit:	31928e51e3886c99ee59ccbedc54072c7a96470f
Name: nokogiri
Version: 1.13.1
CVE: CVE-2021-30560
GHSA: GHSA-fq42-c5rg-92c2
Criticality: High
URL: https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-fq42-c5rg-92c2
Title: Update packaged libxml2 (2.9.12 → 2.9.13) and libxslt (1.1.34 → 1.1.35)
Solution: upgrade to >= 1.13.2
```
Fix the build by upgrading nokogiri.

Update nokogiri because of CVE-2021-30560

---

Gemfile
Gemfile.lock

Heroku builds are failing with:
```
/tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/helpers/rake_runner.rb:100:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
ensure you can run `$ bundle exec rake -P` against your app
and using the production group of your Gemfile.
rake aborted!
LoadError: cannot load such file -- matrix
```
turns out `matrix` got separated from the ruby stdlib but our heroku builds depend on it still, so re-adding it to our gemfile explicitly.
see https://github.com/gdelugre/origami/issues/81 for example
* add matrix gem to gemfile …

add matrix gem, which is required for builds and no longer in ruby stdlib

---

Gemfile
Gemfile.lock

another one of these - heroku build is failing to start based on this thing's absence
* add net-pop gem to gemfile
no issues
For reviewer:
* Tag this PR:

add net-pop to gemfile, since that's also out of ruby stdlib

---

Gemfile
Gemfile.lock

bundle-audit is mad about nokogiri! I bumped to the suggested version and everything looks to be loading clean for me.
* nokogiri >= 1.13.4
For reviewer:
* Tag this PR:

Bumps nokogiri past vulnerabilities

---

.github/workflows/test_dev_env.yml

Ruby 3.1.1 has some not-really-scary vulnerabilities that are failing builds, and we're waiting for 3.1.2 to get up to speed on heroku for right now, so ignoring these for now. Just a build change. 
* ignore a specific pair of vulns for a bit
no issues
For reviewer:
* Tag this PR: …

ignore known vulns while we wait for heroku to patch ruby

---

app/views/layouts/application.html.erb
config/webpack/environment.js

This takes advantage of webpack's chunking system to reduce the size of our builds. The short version is that it goes from a single import to this:
which utilizes code splitting as described here: https://webpack.js.org/guides/code-splitting/ (warning: your eyes are going to glaze over)
I think there's possibly some further optimization we could do here if we were committed to getting build times REALLY low, but I don't think we need to fret about that right now, so let's take the free basket.
* splits our js into chunks using webpacker's nice clean system
no view changes (I checked the main call list and did a few interactions and we're cool)
no issues
For reviewer: …

split js into webpacker chunks

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/views/calls/create.js.erb

We were only really using js-routes in one place, and it was to set behavior after logging calls. It added a `Route` top level obj to the js namespace. We don't _really_ need it since this is the only place we do conditional stuff based on page, as far as I know.
You can double-check this work by `git grep "Route"`.
big s/o to past us for heavy system tests that made figuring this out much easier than I thought it was going tobe!
* refactor to not need js-routes gem
* remove js-routes gem
no issues, but see https://github.com/DARIAEngineering/dcaf_case_management/pull/2392
For reviewer:
* Adjust the title to explain what it does for the notification …

remove js-routes gem

---

db/seeds.rb
test/controllers/external_pledges_controller_test.rb
test/helpers/calls_helper_test.rb
test/helpers/external_pledges_helper_test.rb
test/helpers/patients_helper_test.rb
test/helpers/practical_supports_helper_test.rb
test/models/archived_patient_test.rb
test/models/patient/statusable_test.rb
test/models/patient_test.rb
test/models/user_test.rb
test/omniauth_helper.rb
test/system/accountant_workflow_test.rb
test/system/clinic_management_test.rb
test/system/data_entry_test.rb
test/system/pledge_fulfillment_test.rb
test/system/practical_support_behaviors_test.rb
test/system/submit_pledge_test.rb
test/system/update_patient_info_test.rb
test/system/voicemail_preference_in_call_modal_test.rb
test/test_helper.rb

Most of our tests feature DCAF and a few of its peers as test fixtures. This replaces them with plausible but fake stubs.
* fake abortion funds in test suite
* Bumps #2552 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm …

Remove actual fund refs from test suite

---

app/lib/paper_trail_version.rb
app/models/archived_patient.rb
lib/tasks/nightly_cleanup.rake
test/models/archived_patient_test.rb
test/models/paper_trail_version_test.rb

Some housekeeping on `PaperTrail` audit objects.
* When a patient is archived, also destroy all associated `PaperTrail` versions
* During `nightly_cleanup`, delete any `PaperTrail` objects > 1 year old. 
* Fixes #1974
* Bumps #Y
For reviewer:
* Tag this PR:
* …

Cleanup Patient History

---

app/models/concerns/notetakeable.rb
app/views/dashboards/_table_content.html.erb
test/models/patient_test.rb

This adds a sortable Initial Call Date column to the call list, and drops last note (which hasn't worked right for awhile; part of our justification for dropping it is that nobody has complained in that time). Last note will still show up on the new call flow.
* Add initial call date to call list
* Remove last note from call list
* Fixes https://github.com/DARIAEngineering/dcaf_case_management/issues/2501
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some …

Rework call list to remove part of last note and include Initial Call Date instead

---

app/helpers/patients_helper.rb
app/models/concerns/exportable.rb
config/locales/en.yml
config/locales/es.yml
test/helpers/patients_helper_test.rb
test/models/patient/exportable_test.rb
test/system/updating_configs_test.rb

Add `Prefer not to answer` to a set of dropdrowns.
The only rough spot here is the integer fields - I'm doing a little bit of cheating here and assigning 'no answer' a -1, and then parsing that in the exportable model. Felt nicer than switching the datatype.
* Add `prefer not to answer` to several dropdowns
* Adjust exportable module to handle prefer not to answer values of -1
* Fixes #2503
* Fixes #2502
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some …

Add Prefer not to answer, zeroes to dropdowns

---

app/helpers/notes_helper.rb
app/javascript/styles/tables.scss
app/models/concerns/notetakeable.rb
app/views/dashboards/_table_content.html.erb
config/locales/en.yml
config/locales/es.yml
test/helpers/notes_helper_test.rb
test/models/patient_test.rb

Turns out a fund uses the Notes preview as a core part of their flow! Adding that back.
* Adds back the Notes column & related code removed in #2569 
* No longer offers the (nonfunctional) `+`
* Uses the unicode … instead of ...
* Deletes dead code from removing the `+`
* Shrinks Table font from 17px->16px
* Related to #2501 
For reviewer:
* Tag this PR:
* …

Adds back the Notes preview on table view

---

app/javascript/styles/flash.scss
app/views/layouts/_messages.html.erb
test/integration_helper.rb

This changes makes feedback flashes (user input save confirmation, errors) always show up, even if you scroll the page. Before, flashes were stuck at the top of the page, so if you were on a very tall page and making changes at the bottom, you might miss feedback.
* Makes flashes `position: fixed` rather than `absolute`
* Fixes centering of flashes
Example success:
Example error:
* Fixes #2429
* Bumps #Y
For reviewer:
* Tag this PR:
* `feature` if it …

scroll flashes; adjust css

---

test/models/patient_test.rb

* Test the `trim_shared_patients` method, which we had been skipping.
* Replaces #2583 (now using the new `shared` rather than `flagged` language)
* Fixes #2575 
* Bumps #Y
For reviewer:
* Tag this PR:
* …

add test for previously-skipped patient method

---

Gemfile
Gemfile.lock
Makefile
docs/SETUP.md

friendship ended with `rails s`; `bin/dev` is my new best friend
(also sets up the foreman gem which is required here)
* add foreman gem, to run bin/dev
* sets bin/dev instead of rails s where appropriate (in the makefile and bare metal spinup instructions)
* Fixes https://github.com/DARIAEngineering/dcaf_case_management/issues/2601
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend …

add foreman gem + use bin/dev instead of rails s

---

config/initializers/new_framework_defaults_7_0.rb

Automatically infer `inverse_of` for associations with a scope, whatever that means. Probably doesn't affect us much since we generally do not do scopes.
* turn on this new setting
* Bumps #2462 
For reviewer:
* Tag this PR: …

R7: turn on the inverse_of scope setting

---

config/initializers/new_framework_defaults_7_0.rb

Turn on the namespaced uuids setting. I don't think we use this anywhere.
* Turn on the new namespaced UUIDs setting
* Bumps #2462 
For reviewer:
* Tag this PR:
* If it contains neither, …

R7: turn on namespaced uuids

---

config/initializers/new_framework_defaults_7_0.rb

Turning on this setting makes rails test cases behave a little more server-y, supposedly. Shouldn't have a prod effect.
* turn on the new test setting default
* Bumps #2642
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm …

R7: try turning on executor around test case

---

config/initializers/new_framework_defaults_7_0.rb

Open redirects is a security risk, and this new setting will raise errors. This is a nice security enhancement!
* turn on the raise if empty redirect setting
* Bumps #2462 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm …

R7: turn on new setting to raise on open redirs

---

config/initializers/new_framework_defaults_7_0.rb

another security enhancement; these new default headers include a security improvement. (I think we're still tight on this particular front from the work we did several years ago, but a new sensible default never hurts.)
* turn on the new actiondispatch default headers
* Bumps #2462 
For reviewer:
* Tag this PR: …

R7: turn on default dispatch headers

---

config/initializers/new_framework_defaults_7_0.rb

Toggle on the key generator hash default class. This seems to primarily be for cookie generation and similar secret stuff, which we do relatively little of - probably just login stuff which expires after time anyway.
* turn on the new key generator hash class
* Bumps #2462
For reviewer:
* Tag this PR: …

R7 default: turn on key generator hash digest class default

---

.github/CONTRIBUTING
README.md
app.json
config/application.rb

final round of DCAF -> DARIAs before repo rename.
* git grep -i "dcaf" then change the stuff that isn't `dcaf_case_management`
* Bumps https://github.com/DARIAEngineering/dcaf_case_management/issues/2552
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, …

final round of safe DCAF -> DARIAs

---

config/initializers/new_framework_defaults_7_0.rb

ActionMailer is getting some timeouts by default, this change follows that standard.
* turn on actionmailer timeouts by default
* Bumps #2462 
For reviewer:
* Tag this PR:
* If it …

r7: follow default on actionmailer timeouts

---

config/initializers/new_framework_defaults_7_0.rb

Another secrets generation default class change - doesn't affect us much since we do so little of this.
* follow new rails 7 default for activesupport digest hashing
* Bumps #2462 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update …

R7: turn on new default for activesupport digest

---

config/initializers/new_framework_defaults_7_0.rb

Follow new defaults for params wrapping. You can read all about this at https://api.rubyonrails.org/v5.1.7/classes/ActionController/ParamsWrapper.html but I can't say I recommend it.
* turn on params wrapping default
* Bumps #2462
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that …

r7: enable parameter wrapping by default in controllers

---

.github/workflows/test_dev_env.yml
.yarnrc.yml
config/initializers/new_framework_defaults_7_0.rb
docker-compose.yml

we haven't quite cracked the code on this yet unfortunately, so breaking it into a shape that restores `docker-compose up` at the sacrifice of the CI step for a little while longer.
* bundling in its own processes in docker environments
reopens #2600 (sorry)
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or …

restick css/js bundling in their own pses

---

Gemfile
Gemfile.lock

* upgrades `rails-html-sanitizer`
* (etc)
* Fixes #X
* Bumps #Y
For reviewer:
* Tag this PR: …

upgrade html sanitizer for cve-2022-32209

---

app/models/concerns/exportable.rb
test/models/patient/exportable_test.rb

This fixes a bug where it was returning a list of the external pledges instead of summing up the value. 
previous code before what i think is an oops is:
sum = 0
all_pledges = external_pledges.all
all_pledges.each do |pledge|
sum += pledge.try :amount
end
sum
i think right now, given the fact we have amount on external_pledges, we can just lean on the sum function in activerecord. Added tests to account for what i think are the cases, since i think we just deal with USD. 
* Fixes #2514
For reviewer:

#2514 fix bug where it stopped reporting the sum of pledges

---

docs/SETUP.md

Docker is broken, we should at least indicate as much in our setup docs.
Alternatively, we could revert #2620, since this seems to be the root of the current breakage.

Update dev environment instructions

---

app/controllers/clinics_controller.rb
app/helpers/footer_helper.rb
app/helpers/pledges_helper.rb
app/services/pledge_form_generator.rb
app/views/clinics/_clinic_form.html.erb
app/views/patients/_pledge.html.erb
config/locales/en.yml
config/locales/es.yml
db/migrate/20220702015900_add_email_for_pledges_to_clinics.rb
db/schema.rb
db/seeds.rb
test/helpers/pledges_helper_test.rb
test/system/clinic_management_test.rb
test/system/submit_pledge_test.rb
test/system/update_patient_info_test.rb

* Adds an email field to clinics
* Makes that field editable in the clinic page
* Displays that email on the pledge screen
* If no email, displays the clinic's fax number. If no fax number, just displays the fund's fax service URL.
* Fixes #2528 
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as …

Add email to clinics; display of a clinic's email/fax number when sending a pledge

---

.github/workflows/test_dev_env.yml
docs/SETUP.md
package.json

Kicking the js and css commands until:
Pulling hot reloading into another issue.
* Fix JS container exiting: use the path to the esbuild command - $PATH doesnt know about it in container
* Fix the CI build: the JS fix was the issue here, uncommenting the workflow
* Bumps #2606 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or …

Fixing the JS container, CI, and dev env

---

.github/workflows/deploy_staging.yml

Right now, there is no way to test things on sandbox from a branch on Github. Sometimes, doing a sandbox deploy from a branch is required for stuff like #2694.

Allow staging deploys from branches

---

app/controllers/patients_controller.rb
test/controllers/patients_controller_test.rb

Prevents CM users (all non-admins, to be accurate) from changing fulfillment attributes.
* Uses strong params to ignore nested `fulfillment_attributes` when creating or updating patients, except for admin users.
* Adds tests on `PatientsController#create` and `#update` to make sure we don't regress.
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is …

Don't allow CMs to change fulfillment attributes

---

config/initializers/devise.rb

Signs user out on password change to prevent unauthorized account access when session/password is leaked.
* Flips devise's `config.sign_in_after_change_password` option to `false`. This causes user to be signed out on password change, invalidating the session and redirecting to the sign in page. A message is displayed: "Your account has been updated successfully, but since your password was changed, you need to sign in again.".
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as …

Reset session on password reset

---

config/initializers/rack-attack.rb
test/middleware/rack-attack_spec.rb

Sets dedicated rate limits on key authentication and password routes to protect against attacks or spamming. Also narrows window for checking the general ip rate limit.
* Add throttling rules for /users/auth routes and /users/password routes
* Check ip limit every 10 seconds instead of every 5 minutes. The 60rpm limit stays the same, it's just checked more often (10 requests / 10 seconds vs. 300 requests / 300 seconds).
* Clear rails cache between rack-attack tests so we don't have to worry about ips or emails conflicting across tests.
For reviewer:
* Tag this PR:
* `feature` if it …

Refine throttling on password and auth routes

---

app/models/config.rb
app/views/dashboards/index.html.erb

Attempts to satisfy #2688 
* Adds a `hide_budget_bar` config in `config.rb`
* Renames `validate_hide_practical_support` to `validate_yes_or_no`
* Skips `overview` partial in `app/views/dashboards/index.html.erb` if config value is 'yes'

Fixes "Add a config for not displaying the budget bar #2688"

---

test/models/config_test.rb
test/system/updating_configs_test.rb

fast follow from https://github.com/DARIAEngineering/dcaf_case_management/pull/2696
* add model and system test for hide budget bar functionality
* bumps https://github.com/DARIAEngineering/dcaf_case_management/issues/2688
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades …

add tests for hide budget bar functionality

---

.gitignore
scripts/generate-datastudio-pemkey.py

we're planning on doing some reporting from google datastudio, and connecting psql as a datasource requires generating a cert. This performs the appropriate handshakes etc.
* add a script and instructions to generate the cert
* Bumps #634 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is …

add a script to generate a cert to connect datastudio

---

Gemfile.lock

Upgrade nokogiri to get static scanner security check passing
wah wah: https://github.com/DARIAEngineering/dcaf_case_management/actions/runs/3292881797/jobs/5428763987

Upgrade nokogiri

---

app/models/archived_patient.rb
app/models/clinic.rb
app/models/event.rb
app/models/external_pledge.rb
app/models/fulfillment.rb
app/models/patient.rb

Adds validation on numeric fields to ensure negative amounts of money aren't allowed.
Adds validation to the following fields:
* fulfillments
* fund_payout
* patients
* fund_pledge
* naf_pledge
* patient_contribution
* procedure_cost
* archived_patients
* fund_pledge
* naf_pledge
* patient_contribution
* procedure_cost
* external_pledges
* amount
* events
* pledge_amount
For reviewer:
* Tag this PR: …

Add validation to ensure numeric fields are not negative

---

renovate.json

Docs: https://docs.renovatebot.com/configuration-options/#reviewers
This is so I get a notification and can action it in a timely way.

Auto-assign xmunoz as a reviewer to renovate bot PRs

---

app/models/concerns/exportable.rb
test/controllers/patients_controller_test.rb

Escape string fields containing formulas before exporting to prevent [CSV Injection](https://owasp.org/www-community/attacks/CSV_Injection).
* I opted for doing this directly in the export instead adding validation to the individual fields. This way there's no risk of forgetting this validation when a new field is added.
* I found formulas still executing with leading whitespace, so that's why it's included in the regex. Tested the regex with a number of examples with rubular. Included tab and carriage return because they were listed alongside the other formula characters in the OWASP documentation linked above.
* If we wanted to be even more aggressive, the CSV module has an option to force quotes on all fields. …

Sanitize strings before exporting csv

---

app/models/user.rb
db/seeds.rb
test/controllers/users_controller_test.rb

Add validation on "name" field for user model.
* Adds regex for validating name format
* Adds a test to ensure we're still allowing valid names with special characters like dashes and accent marks
* Adds a test for notable invalid cases: injecting a website name, accidentally supplying an email address in the name field
For reviewer:
* Tag this PR: …

Validate user name format

---

db/migrate/20221027160232_add_unique_index_to_tenant_tables.rb
db/schema.rb

Several fields in `acts_as_tenant` models had uniqueness constraints in the model, but not enforced at the db level. This change adds unique indexes for those fields at the db level to fix that.
Added for the following fields:
* `Clinic :name`
* `Line :name`
* `CallListEntry  :patient` (this one was also scoped to :user)
A few other fields in tenant models already had unique indexes in the db.
For reviewer:
* Tag this PR:
* `dependencies` if …

Add unique index to fields with uniqueness constraints in model

---

db/seeds.rb
test/helpers/footer_helper_test.rb
test/test_helper.rb

Changes fax service seed value to the url of a real fax service. I used a fax service url instead of petsfinder because there's no other text in the UI to identify it as the fax service value. I saw efax elsewhere in the code, and I figured using something other than petfinder makes it easier to connect the link in the UI back to its source location in the code when developing/debugging.
Screenshot of development version of site after change:
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to …

Change seed value for fax service

---

app/controllers/users_controller.rb
app/models/user.rb
config/initializers/devise.rb
db/migrate/20221102172033_add_session_validity_token_to_users.rb
db/schema.rb

Logout user when admin changes their email.
* Devise doesn't have options for configuring this out of the box, so this change implements the solution from [this stackoverflow answer](https://stackoverflow.com/a/29214116) instead. Adds a session validation token to the user table, and a method for removing the token on the user. Then calls the method when a user's email is updated to invalidate their session.
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, …

Logout user on email change

---

Gemfile
Gemfile.lock
app/models/user.rb
config/initializers/devise_security.rb
config/locales/devise.security_extension.en.yml
config/locales/devise.security_extension.es.yml
db/migrate/20221031171553_create_old_passwords.rb
db/migrate/20221031173736_add_unique_session_id_to_users.rb
db/schema.rb

Adds the [devise-security](https://github.com/devise-security/devise-security#session-limitable) devise extension and enables these modules:
* `:password_archivable` - saves used passwords in an old_passwords table for history checks (prevent reusing passwords)
* `:session_limitable` - ensures that there is only one session usable per account at once
The password functionality requires a new table `old_passwords`, and the session functionality requires a new field in the users table `unique_session_id`. The session field could be a bit confusing since it's separate from the existing `sessions` table, so I added a comment to the migration file adding it that should hopefully clarify why it's there for future …

Enable old password checking and session limiting

---

app/models/clinic.rb
app/models/config.rb
app/models/external_pledge.rb
app/models/fulfillment.rb
app/models/line.rb
app/models/note.rb
app/models/patient.rb
app/models/pledge_config.rb
app/models/practical_support.rb
app/models/user.rb
test/models/paper_trail_version_test.rb

Adds validation to various fields to protect against huge values being submitted.
* Adds basic max length validations on a number of fields
* Adds length checks on free-input config options
* Adds length checks on special circumstances
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update …

Validate field length on various fields

---

app/models/patient.rb

we validate these differently - -1 means 'prefer not to answer' for these fields
reported by a fund
* allow values of -1 for household_size_adults / household_size_children
no views
no issues
For reviewer:
* Tag this PR:
* If it contains …

household_size_adults/children can legit be -1

---

app/controllers/users/registrations_controller.rb
config/routes.rb

Adds the locked account check to the `/users/edit` and `/users` routes to prevent locked accounts from viewing or updating their user profile.
* used devise controller generator to generate registration controller.
* Added locked account check to newly generated controller
For reviewer:
* Tag this PR: …

Prevent locked accounts from accessing user profile

---

config/initializers/devise.rb

Similar to https://github.com/DARIAEngineering/dcaf_case_management/pull/2708 which signed out the user after a password _change_, this changes to not sign user in after password _reset_.
Flips devise's config.sign_in_after_reset_password option to false. Displays a message set by devise (changeable [here](https://github.com/DARIAEngineering/dcaf_case_management/blob/96277ff58f9e54395288bcb1548c565ae164b8ca/config/locales/devise.en.yml#L38)): "Your password has been changed successfully."
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is …

Do not sign in on password reset

---

app/controllers/concerns/budget_bar_calculable.rb
app/controllers/dashboards_controller.rb
app/helpers/budget_bar_helper.rb
app/models/config.rb
app/views/dashboards/_budget_bar.html.erb
config/locales/en.yml
config/locales/es.yml
test/helpers/budget_bar_helper_test.rb
test/system/data_entry_test.rb
test/system/updating_configs_test.rb

* adds statistics to budget bar (spent, remaining, percentages)
* refactors code to make adding more aggregate stats easier (and prevent code duplicate!)
* Fixes #2658 
For reviewer:
* Tag this PR:
* …

Budget bar statistics

---

.github/workflows/deploy_staging.yml

I think our healthcheck is probably failing because of some of those cloudflare firewall rules that I turned on :shrug:

Remove health-checking after staging deploy

---

app/helpers/external_pledges_helper.rb
app/helpers/patients_helper.rb
app/helpers/practical_supports_helper.rb
app/models/config.rb
test/helpers/external_pledges_helper_test.rb
test/helpers/patients_helper_test.rb
test/helpers/practical_supports_helper_test.rb
test/test_helper.rb

* adds a config to hide standard options for the requested fields
* adds tests
* Fixes #2717 
* Bumps #Y
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything …

Option to hide default options

---

app/controllers/clinics_controller.rb
app/models/clinic.rb
app/views/clinics/_clinic_form.html.erb
config/locales/en.yml
config/locales/es.yml

This loosens the email_for_pledges field to allow arbitrary text, to let people punch in multiple emails.
We're giving up email formatting in the frontend in exchange for not doing a lot of complicated multi-element form parsing, which is a pain in the behind. But I think arbitrary text is probably fine here.
* Allow arbitrary text input (max length 500) for Clinic#email_for_pledges
* gentle adjustments around that (i18n)
The change here is that this sorta thing is now allowed, and we aren't doing any enforcement on it besides length. I think that's probably fine, since we aren't actively emailing people out of this system and so it's not Required to be Right.
It …

Allow multiple emails in email_for_pledges

---

app/views/patients/_patient_dashboard.html.erb

"Remote: true" in the delete-patient-link in the patient dashboard was causing a problem with the redirects when the user confirmed they wanted to delete a patient. Removed it, and ta-da bug seems to be squashed?
* Removes "remote: true" option from the delete patient link.
* Fixes #1979 
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend …

Remove remote: true from patient delete form

---

app/models/patient.rb

This PR addresses issue #2761 by updating the patient model to return the line name instead of the line object in the phone match error. 
* return line name instead of line object
* Fixes #2761 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or …

Issue 2761: Update Patient Phone Match Error

---

app/models/concerns/exportable.rb
test/models/patient/exportable_test.rb

Adjust export to include practical support money. Default to $0 if not set.
* Add money for practical support entries in CSV export
no view changes, but here's how it shows up in a fresh seed:
```
Counselor - Advice - Unconfirmed - $0; Neighbor - Car rides - Unconfirmed - $0; Donation - Hotel - Unconfirmed - $100.00
```
* Fixes https://github.com/DARIAEngineering/dcaf_case_management/issues/2747
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such …

add currency to practical support in export

---

app/helpers/patients_helper.rb
app/models/config.rb
app/views/patients/_patient_information.html.erb
db/schema.rb
test/helpers/patients_helper_test.rb
test/system/updating_configs_test.rb
test/test_helper.rb

* adds a config for county field
* if config is defined, display a dropdown
* otherwise, display text field (existing behavior)
* Fixes #2771 
For reviewer:
* Tag this PR: …

county field dropdown

---

Gemfile.lock

Follow-up needed after #2836 was merged.

Update Gemfile.lock for ruby 3.2.1

---

Gemfile
Gemfile.lock
app/controllers/auth_factor_steps_controller.rb
app/controllers/auth_factors_controller.rb
app/controllers/multi_factor_authentication_controller.rb
app/controllers/users/sessions_controller.rb
app/lib/api_clients/twilio_verify_client.rb
app/lib/twilio_verify_client.rb
app/models/auth_factor.rb
app/models/user.rb
app/views/auth_factor_steps/confirmation.html.erb
app/views/auth_factor_steps/registration.html.erb
app/views/auth_factor_steps/verification.html.erb
app/views/devise/registrations/_auth_factors_list.html.erb
app/views/devise/registrations/edit.html.erb
app/views/multi_factor_authentication/factor_select.html.erb
app/views/multi_factor_authentication/verification.html.erb
config/locales/en.yml
config/locales/es.yml
config/routes.rb
db/migrate/20230113192110_create_auth_factors.rb
db/schema.rb
test/controllers/auth_factors_controller_test.rb
test/factories/auth_factor.rb
test/models/auth_factor_test.rb
test/system/auth_factor_registration_test.rb
test/system/mfa_login_test.rb
test/system/update_user_info_test.rb

Adds multi factor authentication with SMS using the Twilio Verify API.
* Adds a registration form to register SMS as a 2nd factor.
* Adds a Multi Factor Authentication settings card to the User Profile that links to the registration form and lists registered factors.
* Adds a Multi Factor Authentication step to login for users with it enabled.
More detailed outline [in the issue](https://github.com/DARIAEngineering/dcaf_case_management/issues/2003#issuecomment-1379662445). That comment describes a flow including additional channel types beyond SMS. This PR is basically the same but with SMS only.
* …

Add Multi Factor Authentication with SMS

---

config/locales/es.yml

Spanish translation strings for MFA feature

---

Gemfile
Gemfile.lock

#2760 is a little snarled up, so doing this on its own.
The breaking changes from https://github.com/paper-trail-gem/paper_trail/blob/master/CHANGELOG.md:
```
https://github.com/paper-trail-gem/paper_trail/pull/1399 - Same change re: YAML.safe_load as in 13.0.0, but this time for Rails 6.0 and 6.1.
This change only affects users whose versions table has object or object_changes columns of type text, and who use the YAML serializer. People who use the JSON serializer, or those with json(b) columns, are unaffected.
Please see [doc/pt_13_yaml_safe_load.md](https://github.com/paper-trail-gem/paper_trail/blob/master/doc/pt_13_yaml_safe_load.md) for details.
https://github.com/paper-trail-gem/paper_trail/pull/1406 - …
```

Upgrade to papertrail 14 (safe, the breaking changes are to yaml)

---

app/models/config.rb
app/models/patient.rb
config/initializers/time_with_zone.rb
test/initializers/time_with_zone_test.rb
test/models/config_test.rb
test/models/patient_test.rb

Added the ability for users to configure the time zone for their fund. I chose to use shorter strings than those required by ActiveSupport to limit typo errors and then do some simple mapping on the backend.
Extended the `ActiveSupport::TimeWithZone` class (similar to how we extend `Date` and `Time`). We couldn't add to the existing extension methods b/c `Date` and `Time` are not time zone aware. They're still used if we have instances of those classes but most of our dates (like `created_at`) are actually `TimeWithZone`.
Used the new config to make `Patient.pledged_status_summary` time zone aware.
* Add `config_key` for time zone and add cleaners and validations for …

Issue 2804: Config for timezone display

---

app/models/note.rb
config/application.rb
config/environments/test.rb
lib/tasks/encrypt_notes.rake

This PR uses ActiveRecord encryption to encrypt note full_text at rest.
* configure app to support ActiveRecord encryption
* encrypt note full_text
* add rake task to run post-deploy to encrypt all existing notes
* Fixes #2586
For reviewer:
* Tag this PR: …

Issue 2586: encrypt note content

---

app/controllers/patients_controller.rb
app/controllers/practical_supports_controller.rb
app/javascript/styles/buttons.scss
app/models/practical_support.rb
app/views/practical_supports/_edit.html.erb
app/views/practical_supports/_entries.html.erb
app/views/practical_supports/_new.html.erb
config/locales/en.yml
config/locales/es.yml
db/migrate/20230327181226_add_support_date_to_practical_support.rb
db/schema.rb
db/seeds.rb
test/controllers/practical_supports_controller_test.rb
test/factories/practical_support.rb
test/models/practical_support_test.rb

Complex abortions can be a multi-day process, and patients may need rides etc on multiple days. We should adjust our practical support flow to allow this case.
* Remove support type uniqueness constraint
* Add support_date to practical support model
* Update practical support UI to allow editing support_date
* Fixes #2882 
Open questions
* I didn't add any validations for support_date. I didn't think it made sense to require presence b/c there will be a whole bunch of existing records without a date. Let me know if you want any validation checking that the date is in the future or something like that.
* Let me know if you prefer something different for the UI changes.
* I'm not great at Spanish, I think …

Practical support: add support_date field

---

renovate.json

Tell renovate to group our changes together
* all minor and patch, together
**Testing**
You can validate the config via the [renovate-config-validator](https://docs.renovatebot.com/getting-started/installing-onboarding/#repository-re-configuration) script, but I don't know how to ask it to validate the batching 🤷🏼 
* Fixes #3049 
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug …

Set up renovate batched dependencies

---

app/models/event.rb
lib/tasks/encrypt_event_columns.rake
lib/tasks/encrypt_notes.rake

This PR encrypts sensitive event data at-rest.
* Encrypts sensitive event columns
* Adds post-deploy rake task to encrypt existing event data
* run `rails event:encrypt_sensitive_columns` after you deploy this branch
* if you run a select query on the events table in production, you should see both `cm_name` and `patient_name` are encrypted
* Removes note encryption task that has already been run in production (this is just some clean up)
* Bumps #413 
For reviewer:
* Adjust the title to explain what it does for the notification email …

Issue 413: Encrypt sensitive data in the event table

---

app/models/clinic.rb
config/application.rb
lib/tasks/encrypt_clinic_columns.rake

This PR encrypts sensitive clinic data at-rest.
* Configures deterministic encryption to support cases where that's required (like when we want to have uniqueness validation)
* You'll want to set an env var in production for `ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY` prior to running the post-deploy rake task
* Encrypts sensitive clinic columns
* Adds post-deploy rake task to encrypt existing clinic data
* run `rails clinic:encrypt_sensitive_columns` after you deploy this branch
* if you run a select query on the clinics table in production, you should see both a bunch of the columns are encrypted
* Bumps #413 
For reviewer:
* …

Issue 413: Encrypt sensitive data in the clinics table

---

renovate.json

Reverts DARIAEngineering/dcaf_case_management#3056
Unfortunately, renovate does not handle batched dependency updates well. See #3079. I think when it tries to rebase, all of the other dependency updates get lost. Revert this for now.

Revert "Set up renovate batched dependencies"

---

.github/dependabot.yml
renovate.json

We tried and failed to use renovate's bundled version bumps. It would still be very nice to have the grouped updates, and dependabot has long ago caught upto supporting our version of yarn, so swapping back gets us the grouped updates.
* Removes Renovate
* Adds dependabot
* Avoids the one-know-bad case we'll handle in #3078 
For reviewer:
* Tag this PR: …

Move to dependabot

---

.github/dependabot.yml

I misformatted the exclude pattern in #3086. Also adds distinct names for the two groups.
For reviewer:
* Tag this PR:

Fix dependabot excludes

---

Gemfile
Gemfile.lock

Bumps papertrail one minor version to squash this message:
> PaperTrail 15.0.0 is not compatible with ActiveRecord 7.1.1. We allow PT
contributors to install incompatible versions of ActiveRecord, and this
warning can be silenced with an environment variable, but this is a bad
idea for normal use. Please install a compatible version of ActiveRecord
instead (>= 6.1, < 7.1). Please see the discussion in paper_trail/compatibility.rb
for details.
We are currently on rails 7.1.1, which [should be supported](https://github.com/paper-trail-gem/paper_trail/blob/master/Appraisals) in this verison of papertrail.

Upgrade papertrail to support newer versions of AR

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
config/environments/test.rb

Not my greatest idea, but this end-runs around some changes to how AAT handles state in integration-y tests by hardsetting it in controller. I tried a lot of other stuff that didn't work (and learned a lot about integration tests spawning threads in the process, unfortunately) and I think this is probably the way to go.
The nut of this is that when you do something like this very common integration test or system test thing:
```
visit root_path
fill_in ...
click_button ...
```
it's doing the visit in its own process or fork or thread or whatever which doesn't have access to `Thread.current ` in the test, or `ActsAsTenant` in the test, and so it thinks no tenant is set and it eats mud. It DOES have access to db, …

Upgrade acts_as_tenant

---

.docker/Dockerfile
.github/workflows/test_dev_env.yml
package.json
yarn.lock

- Update node installation script to eliminate deprecation warning
- Upgrade to the latest node 18 version in preparation for #3122 
- Remove npm version spec from package.json since we use yarn for package resolution
- Update yarn.lock

Fixes #3121

---

app/views/lines/new.html.erb

This is not in an open issue, just something that slightly annoyed me as I was testing out a PR on my local development environment. On the first screen after login, you must select a line to work on.
If you click just outside the text box for the label, it doesn't select the radio button. If you then click "Get started" without properly selecting a radio button, you get an error.
What this PR adds: Pre-select the first radio button in the lines list. It should prevent this unpleasant UX situation, which I found myself in because of working quickly.

Default select the first line in a list

---

.github/workflows/test_dev_env.yml
Makefile
docs/GOOGLE_SIGN_ON_SETUP.md
docs/SETUP.md

v1 is now deprecated on the default github actions runners https://github.com/actions/runner-images/issues/9557
All subsequent PRs are likely to have failing CI until this is merged to main.
Also, update docs.
https://docs.docker.com/compose/migrate/

Upgrade docker compose to v2

---

app/controllers/patients_controller.rb
app/helpers/patients_helper.rb
app/models/archived_patient.rb
app/models/concerns/exportable.rb
app/models/config.rb
app/models/patient.rb
app/views/configs/_config.html.erb
app/views/patients/_abortion_information.html.erb
app/views/patients/data_entry.html.erb
config/locales/en.yml
config/locales/es.yml
db/migrate/20240403225952_add_procedure_type_to_patient.rb
db/schema.rb
test/helpers/patients_helper_test.rb
test/system/updating_configs_test.rb
test/test_helper.rb

Adds a configurable, exportable, archivable field Procedure Type to Patient.
Also slightly tweaks the Config model so a field can have both help text _and_ a Current Options dropdown.
| Change | Screenshot |
|--|--|
| Config Option | ![Config page option](https://github.com/DARIAEngineering/dcaf_case_management/assets/6129479/38e6ab3d-b8d8-47db-9e22-7a1787f3e49b) | 
| Patient Abortion Information | ![Abortion Information - Clinic Section showing Procedure Type](https://github.com/DARIAEngineering/dcaf_case_management/assets/6129479/aceb7506-e925-4457-a9e2-656ca095e3d0) |
| Patient Abortion Information (not configured) | ![Abortion Information - Clinic Section hiding Procedure …

Add a Procedure Type to Patient

---

Gemfile
app/javascript/locales.json

This gem needs to be in dev since it's part of an initializer. my mistake for not snagging this!
*  moves the gem over
* reracks i18n
no issues
For reviewer:
* Tag this PR:

move i18n-js to general gems instead of dev gems

---

app/controllers/patients_controller.rb
app/models/concerns/attribute_displayable.rb
app/views/patients/_abortion_information.html.erb
config/locales/en.yml
config/locales/es.yml
db/migrate/20240630034228_add_appointment_time_to_patient.rb
db/schema.rb
docs/DATA_DICTIONARY.md
test/models/patient_test.rb
test/system/update_patient_info_test.rb

Adds a highly optional appointment time field to abortion information.
* Add an appointment time field
* Fixes #3221
For reviewer:
* Tag this PR:

Add Patient#appointment_time

---

app/views/patients/_patient_dashboard.html.erb
test/system/update_patient_info_test.rb

We had reports of users with data issues, and in testing it seems like something slipped through when we reactified that component. Reverting just that erb file until we can dig in more.
For reviewer:
* Tag this PR:

Revert Patient Dashboard to non-React

---

.github/workflows/test_dev_env.yml

this audit failure is making builds choke; making the deliberate choice to restore builds so we can keep it moving
* ignore a flag in npm audit
no issues
For reviewer:
* Tag this PR:
* If it contains neither, no need to tag …

ignore a bootstrap complaint to restore build passing

---

.github/workflows/test_dev_env.yml

npm is sad because of a bootstrap thing we aren't going to resolve for a bit
* ignore this bootstrap complaint
no views
no issues
For reviewer:
* Tag this PR:

get build to pass by ignoring npm thing

---

app/helpers/lines_helper.rb
test/helpers/lines_helper_test.rb

Secretly, you could switch lines by going to `lines/new` and going thru the flow again. Nobody ever asked about line switching. Until now, when it came up as a request from a new fund. So, the time has come.
The reason we don't do this with 1 line is because it doesn't do anything, but if we would prefer simplicity we could link anyway. I think probably fine to not link and keep the span; open to hearing otherwise.
* Link to the line switcher in the navbar if 2+ line
no view changes really
* Fixes #3268 
For reviewer:
* Tag this PR:
* …

In navbar, if 2+ lines add a link to the line switcher

---

.github/workflows/deploy_staging.yml

Staging is no longer being autodeployed from `main`. This is the error message:
```
/bin/sh: 1: heroku: not found
Created and wrote to ~/.netrc
Successfully logged into heroku
/bin/sh: 1: heroku: not found
```
This is because `heroku` no longer comes packaged with the default image of the [`ubuntu-latest`](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) Github-hosted runner (24.04). It was pre-installed on [22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) however, hence the breakage. They claim to have removed it for ["maintenance reasons"](https://github.com/actions/runner-images/issues/9848) 🙄 
This PR explicitly installs heroku …

Fix staging deploy github action

---

app/views/patients/_patient_dashboard.html.erb

Fixes #3233. Literally just adds the "disabled" attribute to a formfield that we don't want to be editable. I had some Docker issues (still not fixed, but I set up the app to run direct on my machine) so this is all I got to do tonight :)
For reviewer:
* Tag this PR:
* If it contains …

disable form field

---

app/models/archived_patient.rb
app/models/call.rb
app/models/config.rb
app/models/event.rb
app/models/user.rb

Looks like the approach of enums is changing in rails 8 to a positional style. Sure, why not. This adjusts the approach to use that positional style. 
* Adjusts enums to use a positional style instead of a keyword style
no view changes, but here's a proveit to confirm I got everything -- relying on the tests for the rest of it 
```
colin@Colins-Air-2 dcaf_case_management % git grep "enum" | grep "\.rb"                                  
app/models/archived_patient.rb:  enum :age_range, {
app/models/call.rb:  enum :status, {
app/models/config.rb:  enum :config_key, {
app/models/event.rb:  enum :event_type, {
app/models/user.rb:  enum :role, {
```
It relates to the …

switch model enums to use positional arguments

---

app/models/patient.rb
test/models/patient_test.rb

Some of the funds we work with are doing some retroactive pledging; in our data model, this conflicts a bit with a rule we enforce of appointment date being after initial call. This PR loosens that rule with a 60 day window - that felt like the point at which it might become an accident. We'll see if it requires further adjustment.
* allow appointment date to be up to 60 before initial call date
* Fixes #3138 
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a …

adjust initial call / appointment date period to diverge a little bit, for late callers 

---

.github/workflows/test_dev_env.yml

No PRs can be merged until this gets merged.
More details: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Upgrade to actions/upload-artifact@v4

---

app/models/config.rb
test/controllers/clinicfinders_controller_test.rb
test/helpers/clinicfinders_helper_test.rb
test/models/clinic_test.rb
test/models/config_test.rb
test/models/user_test.rb

We've had a number of unit tests failing in addition to the system tests, and a recent PR split out the unit tests and system tests to more easily identify what was failing. This brings things back to green by the following methods enumerated below. I'm slightly wary of changes to archive patient and so I intend to test on staging but should be fine.
* Fixes some bs test failures caused by openstruct not being available
* fixes `validate_number` such that it follows the new 'return error string on invalid` approach
* fixes `validate_url` such that it follows the new `return error string on invalid` approach
* fixes a few sub-validators to accommodate changes to …

Fix validators and unit test failures
