DARIAEngineering/dcaf_case_management

- README.md
> add circleci status badge

- app/models/case.rb
- app/models/clinic.rb
- app/models/notes.rb
- app/models/patient.rb
- app/models/pledge.rb
- app/models/user.rb
> Mongo Database Models for notes, pledges, cases, users, clinics, patients

- Gemfile
- Gemfile.lock
- Procfile
- README.md
- app/models/case.rb
- app/models/notes.rb
- app/models/pledge.rb
- config/unicorn.rb
Adds `unicorn` and configs, a `Procfile`, and fixes a few bugs in the models that were erroring out on app start.
Also, deploys an old version to http://casemanagerdemo.herokuapp.com/ !
> Heroku deploy

- app/assets/javascripts/application.js
Add bootstrap javascript into application.js to fix issue with sign in/sign out messages not disappearing when "x" is pressed
> add bootstrap javascript

- Gemfile
- Gemfile.lock
- app/models/case.rb
- app/models/notes.rb
> add mongoid-history gem

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/environments/test.rb
- test/factories/user.rb
- test/test_helper.rb
DB cleaner and starting on FactoryGirl factories.
> Starting on issue #45

- test/models/user_test.rb
Quick unit tests for user model. Nothing fancy, just an everything's okay alarm and a presence check for email and name, since I think those are the two main attributes we'll want to keep tabs on. 
There's a separate issue of user attribute tests (specifically, we have to whitelist individual parameters) which should come either in an integration test of the devise controller (not ideal) or an integration test (better). 
Fixes #61
> basic validation tests for user model

- app/controllers/patients_controller.rb
- app/models/patient.rb
- test/controllers/calls_controller_test.rb
- test/controllers/patients_controller_test.rb
- test/test_helper.rb
Using @ajohnson052 's controller unit tests for calls as a model, builds out controller tests for `Patients` controller. 
Fixes #68
> Patients controller tests

- app/controllers/users_controller.rb
- app/views/pregnancies/_call_list.html.erb
- app/views/pregnancies/_overview.html.erb
- app/views/pregnancies/_search_form.html.erb
- app/views/pregnancies/_search_results.html.erb
- app/views/pregnancies/_table_content.html.erb
- app/views/pregnancies/_urgent_pregnancies.html.erb
- app/views/pregnancies/index.html.erb
- app/views/pregnancies/search.js.erb
- app/views/users/add_pregnancy.js.erb
- app/views/users/remove_pregnancy.js.erb
Adds simple JQuery to populate/depopulate. 
Also moves a ton of stuff into partials. 
Fixes #106
> Jquery call list

- app/controllers/pregnancies_controller.rb
- app/models/patient.rb
- app/views/pregnancies/_table_content.html.erb
- config/routes.rb
- test/controllers/pregnancies_controller_test.rb
- test/integration/record_lookup_test.rb
- test/models/pregnancy_test.rb
Adds integration and unit tests for the search route, and does a little refactoring. 
Notable refactors/improvements: 
* Sets format of '/search' to JS only, to make the integration tests not cry
* Moves search controller action stuff to a Patient object method, and adds unit tests for same
Fixes #104 
Fixes #105
> Add Search route tests

- app/models/pregnancy.rb
- app/views/pregnancies/edit.html.erb
-Added links to left hand side
-Added patient information
still need to:
-add special circumstances checkbox
-style/format form to use bootstrap grid columns better
> Add Patient Information to Pregnancy edit form

- app/assets/stylesheets/application.css.scss
- app/views/layouts/application.html.erb
- app/views/pregnancies/_call_list.html.erb
- app/views/pregnancies/_overview.html.erb
- app/views/pregnancies/_search_form.html.erb
- app/views/pregnancies/_search_results.html.erb
- app/views/pregnancies/_urgent_pregnancies.html.erb
Plenty happened since #113 -- this resolves merge conflicts and springs up a few issues. 
I couldn't quite get the search form right, will just tag them as TODOs in the view and create as issues in the morning. 
Thanks again @drownedout @adinneen @mebates for making these changes! Looks absolutely fantastic.
> Resolve merge conflicts in #113

- app/assets/stylesheets/application.css.scss
- app/views/cases/index.html.erb
- app/views/layouts/application.html.erb
> Case Index Views

- app/views/pregnancies/_abortion_information.html.erb
- app/views/pregnancies/_menu.html.erb
- app/views/pregnancies/_patient_dashboard.html.erb
- app/views/pregnancies/_patient_information.html.erb
- app/views/pregnancies/edit.html.erb
Breaks the edit view into a series of partials with locals, for more straightforward and isolated editing as we get everything in agreement. 
@charleshuang80 what do you think? Any feedback? Slightly mods some of the variable names and slightly changes some sections/divs/classes/ids, but nothing too heavy.
> break edit form into partials

- app/views/pregnancies/_abortion_information.html.erb
- app/views/pregnancies/_menu.html.erb
- app/views/pregnancies/_patient_information.html.erb
- app/views/pregnancies/edit.html.erb
NOTE: Dependent on #140 
Makes a few adjustments to the abortion information partial to close out the sprint, so we can declare victory. 
Fixes #94
> Abortion info partial fix

- app/views/pregnancies/_abortion_information.html.erb
- app/views/pregnancies/_menu.html.erb
- app/views/pregnancies/_patient_information.html.erb
- app/views/pregnancies/edit.html.erb
That was easy. Makes a few slight changes off of @charleshuang80 's form construction to get things mostly in agreement with the InVision. 
Fixes #95
> Patient info partial fix

- app/controllers/pregnancies_controller.rb
- app/views/pregnancies/edit.html.erb
A few changes here: 
* Dries up PregnanciesController#Edit and PregnanciesController#Update with a find before_action method
* Adds strong params for update route, in the ugliest way possible
Doesn't actually get the update route working yet -- that's running into a datatype issue that we should resolve separately, but this doesn't break the edit route so it's good to merge. 
@charleshuang80 I'll let it marinate for part of Saturday so you can comment/suggest changes.
> Pregnancy update route

- Gemfile
- Gemfile.lock
- app/controllers/pregnancies_controller.rb
- app/models/patient.rb
- app/models/pregnancy.rb
- app/views/pregnancies/_abortion_information.html.erb
- app/views/pregnancies/_patient_dashboard.html.erb
- app/views/pregnancies/_patient_information.html.erb
- app/views/pregnancies/edit.html.erb
- test/controllers/pregnancies_controller_test.rb
- test/factories/clinic.rb
Short version: I beat on strong params and the form until they started to see things my way. Update works now!
Adds basic unit tests as well. 
Fixes #97
> Make update work

- app/controllers/calls_controller.rb
- app/controllers/users_controller.rb
- app/views/calls/_new_call.html.erb
- app/views/calls/create.js.erb
- app/views/pregnancies/index.js.erb
- test/controllers/calls_controller_test.rb
This fixes redirects upon making a call.
> Issue #153

- app/views/dashboards/_table_content.html.erb
- app/views/pregnancies/_abortion_information.html.erb
- app/views/pregnancies/_change_log.html.erb
- app/views/pregnancies/_menu.html.erb
- app/views/pregnancies/edit.html.erb
World's tiniest edit to #163 . Thanks much @rebeccaestes !
Fwd momentum on #150
> Rebeccaestes 150 changes partial

- test/controllers/pregnancies_controller_test.rb
Adds additional tests for the edit route to confirm that display stuff is working right. 
Fixes #99  (the rest of the way)
> Finish testing for pregnancies#edit

- app/models/audit_trail.rb
- app/views/dashboards/_table_content.html.erb
- app/views/pregnancies/_abortion_information.html.erb
- app/views/pregnancies/_call_log.html.erb
- app/views/pregnancies/_change_log.html.erb
- app/views/pregnancies/_menu.html.erb
- app/views/pregnancies/_patient_information.html.erb
- app/views/pregnancies/edit.html.erb
- test/models/audit_trail_test.rb
Firing up the PR for awareness. 
Changes:
* creates Change Log partial consisting of stubbed patient history data
* slightly adjusts partials in pregnancy edit view
Still TK, either in this PR or another:
* making the change log partial not look horrible (convenience methods in the audit trail model?)
* stripping out blank fields and ids
* properly wire up users/ids to display in the table
Fixes #150
> Audit history view

- app/models/call.rb
- app/models/clinic.rb
- app/models/note.rb
- app/models/pledge.rb
- app/models/pregnancy.rb
> Model reorg

- test/factories/pledge.rb
- test/models/call_test.rb
- test/models/clinic_test.rb
- test/models/patient_test.rb
- test/models/pledge_test.rb
- test/models/pregnancy_test.rb
Does what it says on the label. 
Fixes #207
> Add userstamp / history / timestamp tests for core models

- app/assets/stylesheets/application.css.scss
- app/controllers/notes_controller.rb
- app/controllers/pregnancies_controller.rb
- app/views/pregnancies/_notes.html.erb
- app/views/pregnancies/edit.html.erb
- test/controllers/notes_controller_test.rb
This adds a notes form into the edit pregnancy page.
> Notes form

- README.md
- db/seeds.rb
After comments from @valeriecodes and @mchelen it's become clear to me that the readme is in desperate need of an overhaul. This is that overhaul! 
Readme now with 100% more:
* better setup instructions
* details about how the project is managed (sprints, milestones, issue structure, etc)
* volunteer appreciation wall toward the bottom
Also makes a slight change to the seedfile to dump creds for the test user. 
Very interested in @valeriecodes @mchelen @mebates @adinneen for feedback. I'll let this PR marinate until the next meeting so we can iterate on it a little bit, if we like. 
Fixes #222 
Fixes #210
> Let's fix up the readme!

- test/integration/note_creation_test.rb
* Adds a case note creation integration test 
* Fixes #209  
* Fixes #193 (redundant)
> Add note creation integration test

- .github/PULL_REQUEST_TEMPLATE
- app/controllers/notes_controller.rb
- app/models/pregnancy.rb
- test/controllers/users_controller_test.rb
- test/factories/user.rb
- test/integration/note_creation_test.rb
- test/integration/sign_up_test.rb
- test/models/call_test.rb
- test/models/clinic_test.rb
- test/models/note_test.rb
- test/models/patient_test.rb
- test/models/pledge_test.rb
* Runs rubocop, mostly
* A little other tidying in the tests
* Fixes #208
> Some repo tidying

- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/pregnancies/_abortion_information.html.erb
- app/views/pregnancies/_patient_dashboard.html.erb
- app/views/pregnancies/_patient_information.html.erb
* disables form autocomplete feature 
* Fixes #223
> Disable autocomplete

- app/controllers/patients_controller.rb
- app/helpers/last_menstrual_period_helper.rb
- app/models/call.rb
- app/models/clinic.rb
- app/models/note.rb
- app/models/patient.rb
- app/models/pledge.rb
- app/models/pregnancy.rb
- app/models/user.rb
- db/seeds.rb
- test/factories/patient.rb
- test/factories/pregnancy.rb
- test/integration/audit_trail_logging_test.rb
- test/models/call_test.rb
- test/models/note_test.rb
- test/models/patient_test.rb
- test/models/pregnancy_test.rb
- test/models/user_test.rb
* Puts model code in a standard format
* Adds basic 'will it build' test to models we're currently using
* Adds validations to a couple places
* Changes a bunch of Date.todays to Time.zone.nows, after a slew of tests failed at exactly 8:01pm
* Fixes #45 
* Fixes #183
> Make models more hospitable and tested

- app/helpers/dashboards_helper.rb
- app/views/dashboards/_overview.html.erb
- test/helpers/dashboards_helper_test.rb
* Creates a helper method in `dashboards_helper` to display the current 'week range' in the dashboard overview. 
* Generates a test for the method, which is currently passing
* Fixes #256
> Fix static date in Dashboard overview with dynamic date range helper method

- app/models/pregnancy.rb
- app/models/user.rb
- app/views/dashboards/_table_content.html.erb
- test/controllers/users_controller_test.rb
- test/factories/pledge.rb
* many to many -ifies user and pregnancy
* fix controller test
* makes pledge factory valid
* Fixes #228
> Allow multiple users to have a pregnancy on their call list #228

- .github/ISSUE_TEMPLATE
- .github/PULL_REQUEST_TEMPLATE
* Bolds the stock text in the issue template
* Adds a placeholder for full text description in the pull request template
* Fixes #294
> Bold issue template text; add stock text to pull request template

- app/views/dashboards/_search_form.html.erb
- app/views/dashboards/search.js.erb
- app/views/pregnancies/_new_pregnancy.html.erb
- test/integration/new_patient_creation_test.rb
* Adds an integration test for new patient creation
* Makes some slight changes to the views, so we don't have duplicate `search_results` ids (oops)
* Fixes #69
> Add integration test to verify New patient creation

- app/assets/javascripts/application.js
- app/assets/stylesheets/pregnancies.scss
- app/views/pregnancies/_abortion_information.html.erb
- app/views/pregnancies/_menu.html.erb
- app/views/pregnancies/_patient_dashboard.html.erb
- app/views/pregnancies/_patient_information.html.erb
- app/views/pregnancies/_pledge.html.erb
- app/views/pregnancies/edit.html.erb
- test/integration/update_patient_info_test.rb
* Adds an integration test for updating patient information
* Adjusts a few element IDs for consistency's sake
* Fixes #100 
💯 !
> Add integration test for updating patient info

- app/views/pregnancies/_new_pregnancy.html.erb
- app/views/pregnancies/_patient_dashboard.html.erb
Changed name form labels on the pregnancy dashboard and new client view
Fixes #268
> added first and last name labels

- app/assets/stylesheets/pregnancies.scss
- app/views/pregnancies/_new_pregnancy.html.erb
- app/views/pregnancies/_patient_dashboard.html.erb
New Pregnancies now has the second LMP field, both places where LMP is now have hidden labels over the day field.
> added LMP field to new pregnancies, and hid placeholder label

- README.md
* Adds an alternative method of installing phantomjs, if homebrew is being a jerk
* Fixes #331, fixes #332
> update phantomjs instructions

- app/views/layouts/application.html.erb
- public/robots.txt
* Turns on the robots.txt disallow
* Adds the `noindex nofollow` meta tag to the layout
Probably adding something to the response headers is overkill for now.
Your thoughts @stvnrlly ?
* Fixes #329
> no robots pls

- README.md
Adds a readme section about project needs for team dev and how we operate, and stubs some other roles for volunteers on the project.
* Bumps #9
> add for developrs section, finally

- Gemfile.lock
- app/assets/stylesheets/pregnancies.scss
- app/views/pregnancies/_abortion_information.html.erb
- app/views/pregnancies/_menu.html.erb
- app/views/pregnancies/_notes.html.erb
- app/views/pregnancies/_patient_dashboard.html.erb
- app/views/pregnancies/_patient_information.html.erb
- app/views/pregnancies/edit.html.erb
* Moves the title over for Patient Info form, Abortion Info form, and Notes
* changes a few `.col` classes from `md` to `sm`
* changes the Submit Pledge and Save buttons slightly
* Fixes #304
> Patient Info Forms into Grid

- Gemfile.lock
- app/views/pregnancies/_abortion_information.html.erb
- app/views/pregnancies/_call_log.html.erb
- app/views/pregnancies/_menu.html.erb
- app/views/pregnancies/_notes.html.erb
- app/views/pregnancies/_patient_dashboard.html.erb
- app/views/pregnancies/_patient_information.html.erb
- app/views/pregnancies/edit.html.erb
Minor edits to @charleshuang80 's fabulous work in #347 .
* (Basically just @charleshuang80 's fixes with a few style edits) 
* Fixes #304
> Patient Info Forms into Grid ctd

- README.md
Does what it says on the label.
* Fixes #362
> alter readme to include ruby install instructions

- README.md
- app/views/layouts/_navigation.html.erb
- circle.yml
I've set up a pipeline in heroku, renamed our heroku app to `dcaf-cmapp-staging`, and rigged it to be promotable to a production version which I'll link to a DCAF domain url. This PR just makes some readme edits to reflect new URLs, but I also wanted to flag that this was a thing via a PR. 
Remotes / circleci continuous deployment / etc also updated here. 
* Fixes #348
> Readme adjustments for pipeline changes

- Gemfile
- Gemfile.lock
- newrelic.yml
Adds newrelic and configs.
* Fixes #409
> Add newrelic

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css.scss
- app/views/pregnancies/_new_pregnancy.html.erb
- app/views/pregnancies/_patient_information.html.erb
Added a checkbox to the patient_information partial and had a go at trying to replace the checkboxes with bootstrap toggle
* Adds checkbox to patient_information 
* Mocks up potential code for replacing bootstrap checkboxes with bootstrap toggles on the patient information and search pages.
* Fixes #365
> Add Checkbox and attempt at bootstrap toggle 

- Gemfile.lock
- app/views/dashboards/_overview.html.erb
Comments out the budget bar placeholder to avoid confusion during test drive.
* Fixes #432
> Comment out budget bar until after it's real

- test/integration/audit_trail_logging_test.rb
- test/integration/call_list_test.rb
- test/integration/logging_calls_test.rb
- test/integration/update_patient_info_test.rb
I am commenting out some of the bad tests I wrote for a little while, so it stops arbitrarily failing CI.
:(
> comment out garbage tests

- config/environments/production.rb
- config/initializers/devise.rb
Everything was/is in fact in env vars, but I'm removing a couple things anyway. 
* tidies up a couple env vars
* Fixes #411
> Remove a few things that look like secrets but aren't

- app/controllers/application_controller.rb
Prevent headers from being set.
* Adds an application controller action to prevent page caching of all controllers except devise
* Fixes #416
> No caching

- app/controllers/application_controller.rb
We're doing this in routing, but might as well do it in the app controller too.
* Adds `authenticate_user!` before hook to app controller
* Fixes #386
> Authenticate in controller

- app/controllers/pregnancies_controller.rb
- app/views/pregnancies/_notes.html.erb
Took a bit of an axe to the notes partial to shoehorn two different forms in. But it matches the designs now!
* Adds urgents checkbox to notes partial
* Whitelists `urgent_flag` in the controller
* Fixes #194
> Add urgents checkbox to notes partial in pregnancy edit view

- app/views/pregnancies/_abortion_information.html.erb~
- app/views/pregnancies/_menu.html.erb
- app/views/pregnancies/_patient_information.html.erb~
- test/integration/show_pregnancy_information_test.rb~
> Changed pregnancy edit view tab order

- app/assets/javascripts/application.js
Semi-colons to close the functions.
> Fixed JQuery bug

- app/assets/stylesheets/pregnancies.scss
- increase menu & submit button font size
- change active menu background color
i couldn't find the css being used for `.nav-pills > li.active > a` so i had to use `!important`
- add glyphicon
implemented with only css, could also be done with an html `<span>` 
fixes #303
> Pregnancy menu styling

- app/models/pregnancy.rb
- app/views/calls/_new_call.html.erb
- app/views/pregnancies/_new_pregnancy.html.erb
Defaults `voicemail_ok` to false; adds it to the new call partial; cleans up the new call partial a little bit. 
* Fixes #484
> Default `voicemail_ok?` to false

- app/models/patient.rb
- app/models/pregnancy.rb
- app/views/pregnancies/_abortion_information.html.erb
- app/views/pregnancies/_patient_information.html.erb
- app/views/pregnancies/_pledge.html.erb
* Fleshes out secondary contact fields; adds secondary_relationship attr
* Adds stubbed pledge fields to pregnancy model; similarly adds fields in form
* Fixes #480 
* Fixes #450 
…ormation, per issue #480
> modified the Abortion Information partial view to include funding information

- app/helpers/last_menstrual_period_helper.rb
- app/models/patient.rb
- app/models/pregnancy.rb
- app/views/pregnancies/_patient_dashboard.html.erb
- test/helpers/last_menstrual_period_helper_test.rb
- test/models/pregnancy_test.rb
* Enforces date format for `appointment_date`
* Adds an LMP display on `appointment_date`
* Adds tests for new stuff
* Fixes #132
> Validate appointment date and add LMP display for appointment date

- app/controllers/pregnancies_controller.rb
- app/models/patient.rb
- app/views/pregnancies/_patient_information.html.erb
- test/controllers/dashboards_controller_test.rb
- test/controllers/pregnancies_controller_test.rb
- test/integration/record_lookup_test.rb
- test/integration/show_pregnancy_information_test.rb
- test/integration/update_patient_info_test.rb
- test/models/audit_trail_test.rb
- test/models/patient_test.rb
- test/models/pregnancy_test.rb
Jumps off Deb's work and alters model fields per #402
* Changes 'secondary' this and that to `other_`
* fixes slew of tests
* Fixes #402
> More secondary

- app/assets/javascripts/application.js
- app/assets/javascripts/pledges.coffee
- app/controllers/pledges_controller.rb
- app/controllers/pregnancies_controller.rb
- app/models/pregnancy.rb
- app/views/pregnancies/_pledge.html.erb
- app/views/pregnancies/edit.html.erb
Runs with @charleshuang80 's modal work.
I think this is the last notable PR we have before mvp. 💯 
* Wires up modal
* Adjusts status
* Fixes #264 
* Fixes #261
> Wire up pledge modal

- .github/PULL_REQUEST_TEMPLATE
* Adds a note to the pull request template asking for screenshots if there are any view changes
* Fixes #79
> add note about asking for screenshot to PR template

- Dockerfile
* Removes xfvb and dependencies from dockerfile so we can `docker-compose build` faster
* Bumps #491
> Simplify dockerfile

- app/models/pregnancy.rb
- test/models/pregnancy_test.rb
* Adds a validation method to confirm that appointment date is after initial call, and tests
* Fixes #514
> Validate appointment date

- README.md
Bumps readme with current team structure, next project milestone, links to slack.
* Fixes #9
> Nontech readme

- app/assets/stylesheets/application.css.scss
- app/helpers/welcome_message_helper.rb
- app/views/devise/sessions/new.html.erb
- test/helpers/welcome_message_helper_test.rb
File under 'stupid/nice thing': Adds a random welcome message on the login page with either (randomly) a cat picture via placekitten, a thank you, or a dcaf slogan. Easily extensible in case we want to add more cat pictures or other nice phrases.
Plus tests, because I am a spaz.
* Fixes #82
> Nice message on login

- app/views/pregnancies/_menu.html.erb
- app/views/pregnancies/_pledge.html.erb
- test/integration/submit_pledge_test.rb
Creates an integration test for sending a pledge.
* Adds an integration test for sending a pledge
* Adds a few ids to buttons in the modal to make them play nice with capybara
* Fixes #262
> Submit pledge integration test

- README.md
- config/initializers/filter_parameter_logging.rb
I have completed some work on Case Manager that's ready for review!
* updates the setup instructions to get the page working on a Cloud9 workspace
* Fixes #534
> Update Cloud9 Setup Instructions

- README.md
- config/initializers/filter_parameter_logging.rb
I completed some work on Case Manager that's ready for review!
* Adds ", :search" to the list of filtered parameters fields in system logs
* Fixes #529
> Filter :search parameter from system logs

- db/seeds.rb
@mchelen wisely pointed out that
This pull request makes the following changes to the seedfile:
* Adds a second user, creates everything with the second user
* Adds two patients to call list and one to completed calls
* Adds a note, for good measure
Spits out the following after login:
@mchelen look good to you? 
* Fixes #543
> Rehab seedfile

- README.md
I rule and have completed some work on Case Manager that's ready for review
Improves Cloud9 set up instructions
Fixes #534
> Update Cloud9 Instructions (again)

- app/views/pregnancies/_notes.html.erb
Big thanks to @mchelen for working on this one!
* fix nesting in notes form
* Fixes #486
> fix nesting in notes forms

- app/models/user.rb
- test/factories/user.rb
- test/integration/sign_up_test.rb
- test/models/user_test.rb
I rule and have completed some work on Case Manager that's ready for review! 
@colinxfleming this is breaking some tests, can you take a look at those?
This 
* Adds a validation to require the user use a complex password including 10 characters min, special character, number and can't use password or dcaf.
Addresses #389
> Adding Complex Password Requirement

- app/controllers/dashboards_controller.rb
- app/models/audit_trail.rb
- app/models/pregnancy.rb
- test/models/audit_trail_test.rb
- test/models/pregnancy_test.rb
Minor edits to some outstanding work by @charleshuang80 in #590 -- time out urgent pregnancies after five days
* Fixes #119
> Time out urgent pregnancies edits

- lib/tasks/nightly_cleanup.rake
Adds a rake task `nightly_cleanup` which cleans up urgent pregnancies and user call lists
* Fixes #581
> Rake cleanup

- app/controllers/pregnancies_controller.rb
- app/models/pregnancy.rb
- app/views/pregnancies/_patient_information.html.erb
- test/integration/update_patient_info_test.rb
I tried to do this by just changing field type to array but I'm now wrangling with the form syntax, sticking labels on the checkboxes.
See for example code: http://stackoverflow.com/questions/21568957/using-checkboxes-to-submit-values-to-an-array
> 'Special circumstances' should be checkboxes #434

- app/views/calls/_new_call.html.erb
Resolves merge conflicts in #584 
Fixes #527
> Mchelen other contact

- app/models/patient.rb
- app/models/user.rb
- lib/tasks/nightly_cleanup.rake
Adjusts the `nightly_cleanup` methods to reflect patients being at the center of the app. 
* Fixes #118
> Fix nightly cleanup

- app/helpers/dashboards_helper.rb
- app/models/patient.rb
- app/views/calls/_new_call.html.erb
- app/views/patients/_call_log.html.erb
- test/helpers/dashboards_helper_test.rb
Picks up @jeffreyeaton76 's heroic work in #588 
* Fixes #526
> Display notes in call modal, add call option to call log on edit view

- app/assets/javascripts/application.js
* make sure the pledge modal next button works every time, without needing to reload
* Fixes #597
> fix pledge modal button by attaching event handlers to document

- app/models/patient.rb
- test/factories/patient.rb
- test/integration/logging_calls_test.rb
- test/models/patient_test.rb
- test/models/pregnancy_test.rb
I added model validations for patient uniqueness.
* Adds `uniqueness: true` to primary_phone validations
* Satisfies issue #620
> Add validation for uniqueness of primary_phone

- app/assets/stylesheets/application.css.scss
- app/views/layouts/_footer.html.erb
- app/views/layouts/application.html.erb
I did some work on DCAF that's ready for review!
I built out a footer partial and inserted it into the application layout.
One minor issue that I'd like someone else's eyes on - test/integration/update_patient_info has a flunking test (#should alter the information), but I see that it's been flagged... pretty sure it's the test (master branch is flunking the same test locally for me), so if someone else could examine before merge I'd appreciate it!
* Adds a footer partial to layouts/application
* Styles elements of the footer
Preview of the addition:
* Fixes #587
> 587 footer

- test/integration/mark_urgent_cases.rb
* Create integration test for marking someone urgent 
* Create integration test for marking someone urgent #471
> mark urgent cases integration test

- app/assets/stylesheets/application.css.scss
- app/views/patients/_new_patient.html.erb
Resolves merge conflicts / slight edits to #594  -- correcting phone and name box sizes on new patient partial.
Resolves #521
> Widen phone and name on new patient form (alley oop from 594)

- app/assets/stylesheets/application.css.scss
- app/views/pregnancies/_new_pregnancy.html.erb
Added new sizing to text box fields on new patient partial, form layout slightly changed.
please let me know if I need to fix anything and I will take care of it asap.
> Corrected Phone and name box sizes on New patient partial

- app/assets/javascripts/reports.coffee
- app/assets/stylesheets/reports.scss
- app/controllers/reports_controller.rb
- app/helpers/reports_helper.rb
- app/views/reports/index.html.erb
- config/routes.rb
- test/controllers/reports_controller_test.rb
This is an attempt at https://github.com/colinxfleming/dcaf_case_management/issues/640
I've generated a `Reports` controller with an empty index view.
I'm unsure if the routing is appropriate for this but as of now it maps to a named route called 'report'
@colinxfleming 
fixes #640
> generated reports controller with index view

- README.md
Adds a note welcoming hacktoberfest people, and adds a few people to the Wall of <3.
> Bump readme for hacktoberfest

- app/views/dashboards/_table_content.html.erb
When removing a patient from the call list we now ask for confirmation. If that is what the user wants through a pop up dialogue. It looks like this:
Fixes https://github.com/colinxfleming/dcaf_case_management/issues/656
@colinxfleming
> added confirmation dialog

- test/integration/drag_and_drop_test.rb
Attempt to seed and see data with poltergiest? I know nothing ~ Jon Snow
> Attempt to #572 drag and drop test

- app/controllers/accountants_controller.rb
- config/routes.rb
- test/controllers/accountants_controller_test.rb
Added `accountants_controller` with get: `index` and post: `search` methods
* new controller added `accountants_controller.rb`
* added simple test cases `accountants_controller_test.rb`
It relates to the following issue #s: #684
> added accountants ctrl with search and index methods

- app/helpers/dashboards_helper.rb
easy one line text change from VOICEMAIL OK, to VOICEMAIL OK, ID OK
@colinxfleming 
Fixes https://github.com/colinxfleming/dcaf_case_management/issues/674
> modified text to VOICEMAIL OK, ID OK.

- app/views/dashboards/search.js.erb
- app/views/patients/_new_patient.html.erb
- test/integration/new_patient_creation_test.rb
- test/integration/record_lookup_test.rb
Massages some of @kanth 's good work in #682. (I kinda screwed the pooch on this.)
* gets code in a place such that we'll be able to easily implement a design when a decision's made after release 2
No view changes at this time.
* nudges #675
> Add some patient partial template code

- lib/tasks/import.rake
Didn't want to lose @MiroFurtado 's forward thinking work in #483, but not sure what to do with it yet. So this moves it to a commented out rake task, and we can pick it up if we need to when we roll out to MD/VA, if this winds up being a good use of dev time. 
* Moves a theoretical future import task to a rake task
* Bumps #483
> Miro furtado excel

- db/patients.csv
- db/seeds.rb
From #475-- this implements the excel import. 
Updated seeds.rb script to allow importing data from a csv file.
Model csv file can be found at db/patients.csv
Usage for set up is "rake db:seed FILENAME" or just "rake db:seed" to use the previously implemented functionality.
> WIP - Excel import functionality

- .dockerignore
- Dockerfile
Addition of a dockerignore file, prevents unnecessary files from making it into the image 
* Addition of barebones Dockerignore file, just ignoring .git, .gitignore, README.md for now
> Docker ignore file

- app/models/pregnancy.rb
- test/integration/submit_pledge_test.rb
- test/models/pregnancy_test.rb
Code is not working.
I tried a couple of things:
* Conditional validations, which we talked about. Here's an example from Railscasts: http://railscasts.com/episodes/41-conditional-validations. If the condition is true, the validation on pledge_sent gets triggered, otherwise it gets bypassed.
* Using the same method with before_update.
I'm out of ideas (I think) for keeping the logic in the model instead of blocking the update in the controller. Do you see a problem in my code?
> attempts at PLEDGE VALIDATION: Validate Pregnancy#pledge_sent field in model #711

- README.md
I added directions for running tests to the Local Environment section of the README.
* Test instructions to the README
* Fixes #714
> Added test commands to README

- README.md
- circle.yml
- docker-compose.yml
Rigs up our CI system to update the docker image on a successful master deployment. 
Finishes off @mchelen and @DarthHater 's awesome work in #518 and elsewhere.
> Deploy new docker image to docker hub on successful change to master

- app/models/fulfillment.rb
- app/models/patient.rb
- test/factories/fulfillment.rb
- test/models/fulfillment_test.rb
Created the Fulfillment Object on the Patient - with tests!
* Fulfillment object created with first pass on fields
* Patient taught about the Fulfillment object
* Basic tests created.
* Fixes #732
> Fulfillment Object on Patient

- README.md
@mvaden 's readme suggestion was a good excuse to update our readme, since we've pretty much hit our structure stride. Bumps the readme to reflect current project organization reality, adds a few all stars to the hall of <3, and makes a few edits in favor of using normal person language. 
* Fixes #749
> README bump

- app/views/users/refresh_patients.js.erb
- config/initializers/lines.rb
- test/helpers/lines_helper_test.rb
- test/integration/dashboard_test.rb
- test/integration/record_call_test.rb
- test/integration/select_line_test.rb
- test/test_helper.rb
A few things here: 
* Comment out a few integration tests that don't play super well with javascript, or which fail randomly due to poltergeist or capybara weirdness
* Sort out lines initialization to something that won't choke on deployment
> Small fixes to get deploy working again; fix bug in views/users/update.js.erb

- app/helpers/patients_helper.rb
Resolves https://github.com/colinxfleming/dcaf_case_management/issues/680
Screenshot:
> [MERGE SUNDAY] Add "Other (add to notes)" option for insurance

- app/views/patients/_patient_information.html.erb
I updated "Fetal anomaly" to "Fetal diagnosis" and added check boxes for "Other medical issue" and "Undocumented".
* Updated the special circumstances check boxes per user feedback
* Fixes #631
> Add "Other medical issue" #631

- app/controllers/external_pledges_controller.rb
- app/views/external_pledges/_external_pledges_table.html.erb
- app/views/external_pledges/_new.html.erb
- app/views/external_pledges/create.js.erb
- app/views/patients/_abortion_information.html.erb
- test/controllers/external_pledges_controller_test.rb
Finishes off @DarthHater 's clutch work in #788 -- the same PR but with a slight div class adjustment. Works like a dream!
* fixes #778
> Initial work to get AJAX working on external pledges finisher

- app/controllers/external_pledges_controller.rb
- app/views/external_pledges/_external_pledges_table.html.erb
- app/views/external_pledges/_new.html.erb
- app/views/external_pledges/create.js.erb
- app/views/patients/_abortion_information.html.erb
- test/controllers/external_pledges_controller_test.rb
This moves the initial work to use AJAX so the page doesn't fully reload. 
* Controller mod (borrowed approach from notes)
* Made a partial out of the external pledges list
* Updating create.js.erb to reload partials
* Moved some logic into the abortion info layout
* Updated tests
* Fixes #778
> Initial work to get AJAX working on external pledges

- app/controllers/patients_controller.rb
- app/models/fulfillment.rb
- app/views/patients/_fulfillment.html.erb
- db/seeds.rb
- test/controllers/fulfillments_controller_test.rb
- test/integration/pledge_fulfillment_test.rb
- test/integration/update_patient_info_test.rb
Launches off @ashlynnpai 's outstanding work in #741 
Quick brain dump on some potential issues due to time constraints: 
* Would be ideal here to create the fulfillment at the time we need it, rather than creating an empty object that we won't use most of the time
* A showstopper: Integration test is dying; need to straighten out dates in the fulfillment view
@ashlynnpai and @lomky can you take a look? ( @ashlynnpai I'll hold on merging until I get your signoff, since you've done the bulk of the work on this and know the problem best)
> (READY FOR MERGE) Ashlynnpai fulfillment view

- app/views/layouts/_navigation.html.erb
- test/integration/routing_test.rb
* Adds a ternary if to the _navigation.html.erb to output the rails env value if it isn't production
* Fixes #792
> Quick ditty to show the environment

- app/views/patients/_new_patient.html.erb
Added simple form validators to the add new patient form. 
Phone number is required and must be 10 numbers
Name is required
* Fixes #784
> Add validations to Add Patient Form

- docs/SECURITY.md
Like I said I would, I wrote a work in progress whitepaper outlining some of our security, so we have it written down. It's not exhaustive but outlines the many steps we take. Intended audience is a) @lwaldsc  and @NerdyGirl537 , who will be selling this and b) other abortion funds, who need to see a tangible indicator that we take data security super seriously.
@lwaldsc and @NerdyGirl537 can you review and flag anything that's too tech-ese or doesn't make sense? I wrote it on the bus in a haze so I want to make sure it makes sense to people who aren't me, and that it's something that's useful to you as you talk to other funds etc. 
* adds security documentation
It …
> Document up our security procedures

- test/integration/data_entry_test.rb
Hotfix a conflict between the new data entry integration test and the changes to how we deal with patient income options.
> Fix data entry integration test

- test/integration/google_sso_test.rb
We have a wait for element in the google sso test, but it's not terribly clear as written. This makes it much clearer.
* Fixes #839
> same test, but with more clarity

- lib/tasks/quality.rake
Maybe resolves the quality task breaking the build?
* Fixes #832
> fix quality?

- .gitignore
- app/models/patient.rb
- test/models/patient_test.rb
Picks up the work of @DarthHater and @agkramer in #865 and #715!
* adds a stub report for patients contacted and first contacted in a week
* Fixes #712
> Patients contacted cleanup

- app/models/patient.rb
- npm-debug.log
- test/models/patient_test.rb
Let's start small here - submitting this pull request:
* adds name and comments for creating describe 'contacted_since method' in patient_test.rb
* adds name and comments for creating contacted_since(datetime) class method
* create patient contacted since class method
Fixes #712
> WIP Create patients contacted class method

- .gitignore
- app/models/patient.rb
- test/models/patient_test.rb
Builds on the cooking with coolio work by @agkramer in #715 
* So far just adding the feedback from @colinxfleming 
* Adds test in patient_test.rb
* Fixes #712
> Patients contacted

- app/models/patient.rb
- lib/tasks/set_identifiers.rake
- test/models/audit_trail_test.rb
- test/models/patient_test.rb
Finishes off @Kevin-Wei 's work in #821 
* Fixes #727
> Make identifier searchable pt 2

- test/integration/call_list_test.rb
- test/integration/create_user_test.rb
- test/integration/display_pledge_info_errors_test.rb
- test/integration/submit_pledge_test.rb
- test/integration/update_patient_info_test.rb
- test/models/patient_test.rb
WIP PR to fix pull request failures as they choke up our builds. I think most of these can be fixed with some good old waiting.
> WIP Fix some persistent integration test failures

- app/helpers/external_pledges_helper.rb
Adds clinic discount to list of external pledges
* Fixes #794
> Add clinic discount to types of external pledges

- test/integration/create_user_test.rb
- test/test_helper.rb
* mocks out a mailer
-> flaky tests
> Stub mailer in tests

- lib/tasks/seed_training.rake
Adds a fail condition and description to @cvaldivia19 's outstanding work in #876 !
* Fixes #800
> Add safety check and description to rake db:seed:training cmd

- lib/tasks/seed_training.rake
Not yet ready
Relates to issue #800
> wip changes for db:seed:training

- app/assets/stylesheets/reports.scss
- app/views/reports/_call_line.html.erb
- app/views/reports/_past_thirty_days.html.erb
- app/views/reports/_year_to_date.html.erb
- app/views/reports/index.html.erb
* Adds reports UX with hardcoded data and temporary budget bar
* fixes #659
> REPORTING: Build basic report view #659

- app/assets/javascripts/clinics.coffee
- app/assets/stylesheets/clinics.scss
- app/controllers/application_controller.rb
- app/controllers/clinics_controller.rb
- app/controllers/users_controller.rb
- app/models/clinic.rb
- app/models/patient.rb
- app/views/clinics/index.html.erb
- app/views/clinics/new.html.erb
- config/routes.rb
- db/seeds.rb
- test/controllers/clinics_controller_test.rb
- test/controllers/patients_controller_test.rb
- test/controllers/users_controller_test.rb
- test/factories/clinic.rb
- test/models/clinic_test.rb
As part of hackathon weekend, we're going to take a real stab at implementing @vtmeghan 's abortron. Part of that is getting clinic stuff in order -- this adds some basic CRUD stuff around clinics, completely iso'd from the rest of the app for now.
No integration test yet either, since there aren't designs for this yet.
* Stubby clinics index, create, new routes, so we can add clinics in a dev env
* Clinic is no longer an embedded object under patient
* Unit tests for new reality
* Bumps #642, #818, #146
> Basic clinic modeling

- app/helpers/welcome_message_helper.rb
I added a nice message for the log-in screen.
https://github.com/colinxfleming/dcaf_case_management/issues/884
> Add a nice message

- app/helpers/welcome_message_helper.rb
From San Francisco with love!
* Related to #884
> Add welcome message

- app/views/patients/_fulfillment.html.erb
Fixes https://github.com/colinxfleming/dcaf_case_management/issues/921
@colinxfleming
> Hide fulfillment partial on page load

- app/models/call.rb
- app/models/external_pledge.rb
- app/models/fulfillment.rb
- app/models/note.rb
- app/models/patient.rb
- app/models/pregnancy.rb
- test/models/note_test.rb
> Validate created_by_id instead of created_by

- Gemfile
- Gemfile.lock
Add early version of clinic finder gem for demoing
> Add clinic finder gem

- app/helpers/welcome_message_helper.rb
* additional welcome messages added
> Welcome messages added

- app/helpers/welcome_message_helper.rb
> Add missing commas to WelcomeMessageHelper

- Gemfile.lock
- app/controllers/clinic_finder_controller.rb
- app/views/clinic_finder/_results_table.html.erb
- app/views/clinic_finder/index.html.erb
- clinics.yml
- config/routes.rb
Basic integration with clinic_finder gem
> WIP - Scaffold for integrating clinic_finder gem

- app/helpers/last_menstrual_period_helper.rb
- test/helpers/last_menstrual_period_helper_test.rb
Also fixes tests for LastMenstrualPeriodHelper.
Fixes https://github.com/colinxfleming/dcaf_case_management/issues/931
@colinxfleming
> Stop incrementing LMP after appointment date has passed

- Dockerfile
Small mod to install test / dev dependencies 
* Mods Dockerfile to install test/dev dependencies 
* Fixes #901
> Install test dependencies

- app/assets/stylesheets/clinics.scss
- app/controllers/clinics_controller.rb
- app/views/clinics/_clinic_form.html
- app/views/clinics/edit.html.erb
- app/views/clinics/index.html.erb
- app/views/clinics/new.html.erb
- config/routes.rb
* Edit views for clinics
* Restructured clinic form to be used by both edit and add views
Added Edit link to Clinics index page
Added Edit View
* Fixes #146
> Add clinic editing functionality

- Dockerfile
- Gemfile
- Gemfile.lock
- circle.yml
- docs/SETUP.md
Updates to Ruby 2.4.1 to dance around the segfault
* Minimal changes to get to Ruby 2.4.1
> Update to Ruby 2.4.1

- Dockerfile
- circle.yml
- docs/SETUP.md
Version-locks phantomjs in CI and in docker to 2.1.x.
No significant issues or changes, though I guess it's a nudge at #903 in a way.
> Upgrade phantomJS in build

- app/assets/javascripts/patients.coffee
- app/controllers/patients_controller.rb
- app/views/patients/_pledge.html.erb
- test/controllers/patients_controller_test.rb
- test/integration/pledge_fulfillment_test.rb
- test/services/pledge_form_generator_test.rb
> fix tests to allow for new interface plus type changes

- docs/PRESS.md
Adds our Teen Vogue mention to the press doc @lomky put together.
> Add our mention from Teen Vogue

- app/views/patients/data_entry.html.erb
- test/integration/data_entry_test.rb
The clinics PR we just merged has some rails 5 issue that's breaking the data entry form. This is a WIP placeholder to fix master. 
Exact test is something like 'undefined method '>' for nilclass' on L274 of Patient model.
> Unbreak tests

- Dockerfile
Welp, I learned a lot about PhantomJS and Alpine today.
* Makes changes to Dockerfile to bring in a dockerized phantomjs (2.1.1 to boot)
* Fixes #1003
> Docker and phantom fun times

- README.md
- docs/PRESS.md
* Adds link to Bad with Money podcast to press docs.
> Add link to Bad with Money podcast

- docs/YOUR_FIRST_CONTRIBUTION.md
Looks like the link is case sensitive.
* (etc)
* Fixes #X
* Bumps #Y
> SETUP.md link not resolving

- app/controllers/clinics_controller.rb
Updated the clinics index controller to default to alphabetical view.
* Alphabetical listing of clinics
[Imgur](http://i.imgur.com/jvA62dT.png)
* Fixes #1007
> #1007: Order clinics alphabetically

- app/assets/javascripts/clinics.coffee
- app/assets/javascripts/patients.coffee
- app/controllers/clinics_controller.rb
- app/views/patients/_abortion_information.html.erb
- config/routes.rb
- db/seeds.rb
- test/controllers/clinics_controller_test.rb
Resolves merge conflicts in the PR that sets up 'check this box to show only NAF clinics' from the clinics dropdown. 
* Resolves a few merge conflicts in #986 
* Fixes #979
> Resolve merge conflicts in Add NAF filter for clinics

- test/integration/update_patient_info_test.rb
Add integration test for addBalance()
* semi-Fixes #1039
> Test: addBalance test

- app/helpers/dashboards_helper.rb
- app/views/dashboards/_table_content.html.erb
- circle.yml
- test/helpers/dashboards_helper_test.rb
Swaps out brakeman for brakeman pro in CI (thank you Justin and team brakeman)
* Swaps out brakeman pro in CI
* Fixes a warning (in progress, not a bad one)
* Fixes #1019
> Add brakeman pro to ci

- app/assets/stylesheets/clinics.scss
- app/views/clinics/index.html.erb
* (etc)
* Fixes #X
* Bumps #947
> in progress, style clinics index to accordion collapse

- docs/SETTING_UP_A_NEW_INSTANCE.md
WIP PR to document the steps in spinning up an instance for our friends up the road this weekend.
> WIP - document steps for New fund deployment

- app/helpers/budget_bar_helper.rb
- app/helpers/calls_helper.rb
- app/helpers/change_log_helper.rb
- app/helpers/dashboards_helper.rb
- app/helpers/external_pledges_helper.rb
- app/helpers/lines_helper.rb
- app/helpers/notes_helper.rb
- app/helpers/patients_helper.rb
- app/helpers/pledges_helper.rb
- app/helpers/users_helper.rb
Had some time on the plane but no internet, so I resolved some rubocop violations in helpers.
* Mostly adds top level documentation comments
* Prettified a couple of things (shorter lines, moved something to a text block)
No issue.
@valeriecodes github suggests you as a reviewer! Can you do me a solid and take a look?
> Lint helpers

- .rubocop.yml
- app/controllers/accountants_controller.rb
- app/controllers/clinicfinders_controller.rb
- app/controllers/clinics_controller.rb
- app/controllers/dashboards_controller.rb
- app/controllers/lines_controller.rb
- app/controllers/notes_controller.rb
- app/controllers/patients_controller.rb
- app/controllers/reports_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users_controller.rb
Had time on the plane, linted models.
* Top level doc comments for everything!
* A couple style changes/ whitespace eliminations/etc
No issue. 
@tingaloo can you eyeball this for me? Interested in particular on whether the top level documentation comments make sense. (We use rubocop for linting, it's basically the same as eslint.)
> Lint controllers

- app/models/concerns/exportable.rb
This PR makes the assumption that the first and last call are patient.calls are indeed the first and last.
* Exports call and fulfillment information
* Bumps #965
> Export remaining CSV fields

- app/views/patients/update.js.erb
On submit pledge, pledge fulfillment is now clickable.
* Bugfix
* Fixes #1120
> Pledge fulfillment now populating on submit pledge

- app/models/audit_trail.rb
- app/models/clinic.rb
- app/models/external_pledge.rb
- app/models/fulfillment.rb
- app/models/note.rb
- app/models/patient.rb
- app/models/user.rb
Had time on the plane so I resolved some rubocop violations in our models.
* Top level documentation for everything
* Some whitespace and line-too-long fixing
No issue.
@cfinucane  can you eyeball this for me? In particular I'm interested in whether or not the top level documentation comments make sense, and I think you're pretty well positioned to do that as someone who hasn't been swimming in this for the better part of a year 💯
> Lint models

- app/assets/stylesheets/application.css.scss
- app/views/dashboards/index.html.erb
* change the `index.html.erb` wrapper's class from "container" to "row"
* Fixes #1103
> align Call List table with Navbar title

- Gemfile
- Gemfile.lock
- app/views/reports/index.html.erb
Add nonces to render async to bypass CSP.
* Add nonces
* update render async gem
* Fixes #1140
> Add nonce to render async call WIP

- docs/SECURITY.md
* Bump security doc to reflect current reality
No issues.
@lwaldsc can you sign off? Thanks!
> Bump security doc

- app/helpers/welcome_message_helper.rb
* Adds a new Welcome Message
* #884
> Meag D onboarding msg

- app/assets/javascripts/clinics.coffee
- app/controllers/clinics_controller.rb
- app/models/clinic.rb
- app/views/clinics/_clinic_form.html.erb
- app/views/clinics/index.html.erb
- app/views/patients/_abortion_information.html.erb
- test/integration/filter_medicaid_clinics_test.rb
Per issue #1077, this update adds a field for whether a clinic accepts Medicaid coverage.
* Updated the clinic model with a boolean field as to whether the clinic provides medicaid
* Modified views for adding, updating and displaying clinics to show Medicaid option
* Added coffeescript methods for filtering option by clinics that accept Medicaid on the patient's abortion information tab
* Created an integration test for filtering the clinics by Medicaid provider on the abortion information tab
* Fixes #1077 
* Bumps #978
> updated clinic model, related views and integration test for Medicaid coverage

- docs/OUR_DATA_COLLECTION_PRACTICES.md
- docs/SECURITY.md
We had a conversation started by @lwaldsc  in slack stemming from another org asking for data collection best practices about whether it might be worth making a reference dump on how we've approached these problems for other groups doing social justice work using sensitive data.
Here's what I wrote on the plane before falling asleep. Obviously a work in progress. People should feel free to push straight to this branch to add their thoughts (after I flesh it out a little more and complete, like, sentences).
* Add doc about our data collection practices
No issues.
cc @lwaldsc @cfinucane @lomky @DarthHater , which I think is the core group of people who have been thinking about this a lot. Others should feel free to chime in!
> Add data collection practices document

- app/controllers/patients_controller.rb
Caught a bug, fixes date of check field error.
* Fixes #1199
> fix date of check

- Gemfile.lock
Bumps our sqreen gem to current version to get the gemnasium whine to go away.
* bumps `sqreen` gem to current version
No issues.
@rudietuesdays can you approve?
> Bump sqreen gem

- app/views/users/_users_table.html.erb
I added an if statement to check if the search results are nil in order to resolve the 500 error being thrown (which was actually a NoMethodError - undefined method `each' for nil:NilClass)
* app/views/users/_users_table.html.erb
* Fixes #1104
> Fixing issue 1104 Search Functionality on Admin Panel Not Working

- app/views/devise/sessions/new.html.erb
* Turns off autocomplete for login text fields as requested (https://github.com/DCAFEngineering/dcaf_case_management/issues/1196)
* Fixes #1196
> Turn off password and email autocomplete

- docs/HOW_LINES_WORK.md
Adds a doc explaining what lines are and how they work in the app. I hope!
* Adds `docs/HOW_LINES_WORK.md`
@lomky or @DarthHater can you review? Please def let me know if there's anything I can do to clarify anything in here, as I want to make sure this doesn't live mostly in my head.
* Fixes #1070
> Add doc explaining lines

- config/mongoid.yml
This was a sin of the past that I am now atoning for, so we can script new instance spinup per #1251 
@colinmcglynn for review
> use mongoid uris

- app/helpers/welcome_message_helper.rb
It will add a message of encouragement!
* "Outstading job! Keep up the hard work!"
* Bumps #884
> add a message of encouragement to welcome_messages array

- docs/SETUP.md
Updates docker instructions, since the current docker engine does the proxy work for you and ties itself to `localhost`.
* Bumps documentation
* Fixes #1173 
@meagdoh can you approve?
> Update docker instructions

- app/assets/stylesheets/pregnancies.scss
> Left align table headers

- app/controllers/application_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
Adds headers. Not sure how to test the content-type one or if adding that header on devise pages will cause issues (though I can't think why, but they did seem to be deliberately excluded before) so please check my work!
* Fixes #1198
* Fixes #1197
> Add response headers

- config/mongoid.yml
Reintros the variable URIs in the mongoid config. Sorry @mchelen and @chrisbarthol .
* Docker works again
* Fixes #1260
> Fixes docker DB connection

- docs/SETUP.md
this command is needed sometimes to get docker to start
> document command to remove leftover server pid

- test/models/audit_trail_test.rb
This is a repeat of #1284, but without the force push making CircleCI throw up (hopefully)
> Fixed timezone conflict failing tests in the pm

- app/helpers/welcome_message_helper.rb
Fixed Spelling errors on the welcome message array
* Bumps #884
> Fixed Spelling Error

- app/controllers/patients_controller.rb
- app/models/patient.rb
- test/controllers/patients_controller_test.rb
- test/models/patient_test.rb
Corrects logic to fix bug 1286.
> Fix #1286 (this time in the model)

- app/controllers/users_controller.rb
- test/integration/user_management_test.rb
Made a quick change to allow roles to be permitted on update.
* Fixes #1271
> Allow admins to change roles

- app/controllers/clinics_controller.rb
- app/views/clinics/_clinic_form.html.erb
- app/views/clinics/index.html.erb
- test/controllers/clinics_controller_test.rb
- test/system/clinic_management_test.rb
Atoning for not writing clinic tests when we rolled it out last year.
* Adds controller tests
* Adds a system test
* Makes a few DOM changes to ids to simplify the testing
* Fixes #1175
> Add Clinics system and controller testing

- app/models/audit_trail.rb
Removes pledge_sent_by, updated_by, and last_edited_by from changelog, as this information can be otherwise inferred.
* Fixes #1330
> Mkd fix change log

- db/seeds.rb
Rescued my super robust test patient from the original patient archive PR #1162 
* adds a couple of patients with fully exercised options. They have calls, notes, fulfillments, external pledges, the whole shebang. Maybe urgent, maybe resolved without fund.
- None
> Robust patient seed

- app/controllers/calls_controller.rb
- app/models/call.rb
- app/models/external_pledge.rb
- app/models/fulfillment.rb
- app/models/patient.rb
- db/seeds.rb
- test/controllers/calls_controller_test.rb
- test/controllers/external_pledges_controller_test.rb
- test/helpers/external_pledges_helper_test.rb
- test/lib/reporting/patient_test.rb
- test/models/call_test.rb
- test/models/external_pledge_test.rb
- test/models/fulfillment_test.rb
- test/models/patient_test.rb
- test/models/user_test.rb
- test/system/pledge_fulfillment_test.rb
- test/system/submit_pledge_test.rb
- test/system/update_patient_info_test.rb
Making the Patient subobjects polymorphic, feeds into #1362
> Sheeping the Subobjects

- app/views/dashboards/_search_form.html.erb
I changed the submit tag to a search glyphicon 
Before:
After:
> Replace 'search' text with search icon

- app/assets/javascripts/patients.coffee
- app/helpers/patients_helper.rb
- app/views/patients/_abortion_information.html.erb
I rule and have completed some (emphasis on some) work on Case Manager that's ready for review!
These are my initial changes around adding tooltips to other areas of the applications. Honestly the stuff I was doing to the table contents in the index.html.erb is complete gibberish at this point. The important stuff is happening in _abortion_information.html.erb
* Well there is a (?) next to the checkbox for Resolved without assistance from DCAF now, so that's a start!
* Fixes #1115
> WIP PR for Issue #1115

- Gemfile
- Gemfile.lock
Library update spring cleaning!
* Bundle update a bunch of stuff while I'm waiting for the caffeine to hit
No issues, no views.
> Update a bunch of production libraries

- app/assets/stylesheets/events.scss
Reverting back colors, taking suggestions on fixing it up.
* Fix weird grey oval.
* Fixes #1395
> Fixing activity log visuals

- README.md
- docs/SECURITY.md
Removes Gemnasium:
https://gemnasium.com/blog/gemnasium-is-acquired-by-gitlab/
* Removes badge
* Removes docs related to gemnasium
> Rip out Gemnasium

- app/assets/stylesheets/application.css.scss
- app/helpers/tooltips_helper.rb
- app/views/patients/_abortion_information.html.erb
- app/views/patients/_modal.html.erb
- app/views/patients/update.js.erb
- test/helpers/tooltips_helper_test.rb
There were a few neglected QA changes flagged by @eheintzelman in #1242 -- some of them have been fixed as separate tickets, but this fixes the remaining couple.
* tooltip for referred to fund
* standardize modal spacing
* update notification also closes
* Fixes #1242
> Implement QA review changes

- Gemfile
- Gemfile.lock
CVE, time to upgrade, etc
* bundle update nokogiri
No views or issues.
> Upgrade nokogiri to 1.8.4

- app/assets/javascripts/patients.coffee
Updates outstanding balance on change.
* Fixes #1430
> Update Calculator on field change

- Gemfile
- Gemfile.lock
- app/controllers/events_controller.rb
- app/models/event.rb
- app/views/events/_events.html.erb
- app/views/events/index.js.erb
Add kaminari paginating to call list. Call list now shows 25 at a time. Not sure if this a complete fix, but welcome to ideas.
* Fixes #1447
> Add pagination to call list

- app/models/concerns/exportable.rb
This PR adds exportable info to csv export!
I've manually tested it a fair bit so far, and will add automated tests when I do the full data test.
@colinxfleming do you know when we might next be updating DARIA? This PR would definitely help for Data Team stuff.
> expand exportable to include pledge data - first pass

- .circleci/config.yml
- Gemfile.lock
Not something we were extremely affected by or at risk of, but nonetheless.
* `bundle update selenium-webdriver` (the parent library)
No issues
> Patch rubyzip CVE

- Gemfile
- Gemfile.lock
`render_async` hit 1.0! Congratulations to them. Let's see if our tests still pass!!!
* `bundle update render_async`
no issues
> bundle update render_async

- Gemfile
- Gemfile.lock
`bundle update devise, geokit, bundler`
tech debt!
> Bump Devise, Geokit, Bundler

- Gemfile
- Gemfile.lock
TAKE II
Updated the following gems:
turbolinks
sdoc
nokogiri
rack-attack
secure-headers
puma
sdoc
secure-headers
sqreen
And the following deps as a result:
json
rack
rdoc
sq_mini_racer
> updating gems take II

- Gemfile
- Gemfile.lock
bundle update jquery-rails js-routes kaminari
tech debt!
> Update jquery-rails, js-routes, kaminari

- .circleci/config.yml
- .docker/Dockerfile
- .rubocop.yml
- Gemfile
- Gemfile.lock
- test/system/pledge_fulfillment_test.rb
ruby 2.5.1 => ~2.5.2~ 2.5.3
* in the circle config!
* in rubocop!
* in the app!
> squelch a pair of cves via a ruby upgrade

- test/helpers/users_helper_test.rb
> Add tests for display of disabled user statuses

- app/models/patient.rb
- app/views/patients/_patient_information.html.erb
Fixes related to this issue: #1498
> Add indicator to tell if someone's phone is textable #hacktoberfest

- Gemfile
- Gemfile.lock
- app/controllers/external_pledges_controller.rb
- app/controllers/notes_controller.rb
- app/views/layouts/application.html.erb
- config/initializers/csp.rb
- test/controllers/external_pledges_controller_test.rb
- test/controllers/notes_controller_test.rb
We were using gon on the old reports, but we aren't anymore, so this strips it in favor of render_async
tech debt!
(the old PR #1488 was a little overtaken by events, so respinning it up.)
> Remove gon gem

- app/helpers/welcome_message_helper.rb
- app/views/devise/sessions/new.html.erb
- config/locales/en.yml
- config/locales/es.yml
I rule and have ~completed~ started some work on Case Manager!
Started adjusting the login page and added some spanish welcome messages.
Tagging in @DarthHater for any devise-specific adjustments and @montanezp for reviewing my Spanish!
* Bumps #1382
> Translating the login page

- app/helpers/patients_helper.rb
- app/views/patients/_patient_information.html.erb
- config/locales/en.yml
- config/locales/es.yml
- test/helpers/patients_helper_test.rb
Working through the views in #1571 
* Base labels & strings translated
* Helper text
* Dropdowns
* Fixes #1571
* Bumps #1382
> Spanish Patient Part 1

- app/helpers/calls_helper.rb
- app/views/patients/_abortion_information.html.erb
- app/views/patients/_call_log.html.erb
- app/views/patients/_change_log.html.erb
- config/locales/en.yml
- config/locales/es.yml
* Abortion tab translation
* call log tab
* change log tab
* Not in this ticket: history tracks translation handling
* Bumps #1572 
* Finishes it if #1608 is already merged!
> Patiente parte 2

- Gemfile
- Gemfile.lock
Updated Bootstrap-sass for the vulnerability alert.
> Bootstrap sass Take 2!

- app/helpers/external_pledges_helper.rb
- app/views/external_pledges/_edit.html.erb
- app/views/external_pledges/_new.html.erb
- config/locales/en.yml
- config/locales/es.yml
- test/helpers/external_pledges_helper_test.rb
* External Pledges!
* Finishes #1582
> External Pledges Spanish Translation

- .circleci/config.yml
- app/views/clinicfinders/_search_form.html.erb
- config/locales/en.yml
- config/locales/es.yml
* Translates the clinic finder box
* Bumps #1572
> Clinic Locator Spanish Translation

- .circleci/config.yml
- app/javascript/packs/application.js
- docs/SETUP.md
- package.json
- yarn.lock
Run `yarn audit` in CI and bump the readmewith a section on installing and using yarn.
* `yarn audit` in CI
* readme bump
no views, no issues
> Set up yarn audit in CI

- app/models/fulfillment.rb
- app/views/accountants/_search_form.html.erb
- app/views/accountants/_table_content.html.erb
- app/views/accountants/_table_content_row.html.erb
- app/views/accountants/index.html.erb
- config/locales/en.yml
- config/locales/es.yml
Run the accountants workflow thru i18n.
* i18n-icize the accountants page
* Fixes #1583
> Translate accountants page

- app/helpers/clinicfinders_helper.rb
- app/views/clinicfinders/_result_table.html.erb
- app/views/clinicfinders/_search_form.html.erb
- app/views/clinicfinders/search.js.erb
- config/locales/en.yml
- config/locales/es.yml
- test/helpers/clinicfinders_helper_test.rb
Forgot to translate the partial for the clinicfinders result -- here it is. I'll get @montanezp to review the spanish tomorrow.
* Translate clinicfinders result partial
* Bumps #1633
> Port Spanish clinicfinder result table

- app/helpers/pledges_helper.rb
- app/models/concerns/last_menstrual_period_measureable.rb
- config/locales/en.yml
- config/locales/es.yml
Working with @montanez at hacknight to translate some remaining sneaky English and improve the Spanish we had to be more consistent. (Pledge is Promesa!)
* Bumps #1633
> Fixing Spanish with Paulina

- .docker/Dockerfile
- .docker/entrypoint.sh
- docker-compose.yml
This gets yarn working in docker-compose
* Adds npm
* Installs yarn via npm (this gets us a fresher version of yarn without writing a LOT of code to do it)
* Modifies the docker-compose command to run `yarn install` before `rails s` so that the integrity check works
* Fixes #1623
> Get yarn working in Alpine

- config/locales/en.yml
- config/locales/es.yml
- test/system/data_entry_test.rb
Cleaning up build failures previously disguised by our friendly' circle-fork-bug.
* i18n-tasks normalize
* Update fields on the Data Entry tests to match standardized field names
> Fixing the Build

- app/helpers/welcome_message_helper.rb
Adds encouraging message in French
1) Adds additional message to welcome_message_helper.rb welcome_messages
* Bumps #884
> Adds encouraging message in French

- config/locales/en.yml
- config/locales/es.yml
Ref https://github.com/DCAFEngineering/dcaf_case_management/issues/1657
I fixes some missing Spanish translations in the clinic finder.
* Fixes #1657
> Fix missing location and distance translations

- app/helpers/dashboards_helper.rb
- app/models/config.rb
- app/models/patient.rb
- config/locales/en.yml
- db/seeds.rb
- test/helpers/dashboards_helper_test.rb
- test/models/config_test.rb
- test/models/patient_test.rb
> Adds option to start budget week on non-Monday #1698

- app/controllers/practical_supports_controller.rb
- app/views/layouts/_flash_messages.js.erb
- app/views/patients/_menu.html.erb
- app/views/practical_supports/_entries.html.erb
- app/views/practical_supports/_new.html.erb
- test/models/practical_support_test.rb
- test/system/practical_support_behaviors_test.rb
Adds integration tests for creating, editing, and destroying practical supports using the UI.
* system tests for #1713 !
* Bumps #1493
> System tests for practical support

- .circleci/config.yml
- app/controllers/practical_supports_controller.rb
- app/models/config.rb
- app/views/patients/_menu.html.erb
- app/views/patients/edit.html.erb
- test/models/config_test.rb
- test/system/practical_support_behaviors_test.rb
Wiring it up was OOS but I went ahead and did it anyways. Self-tested, mini-test specs TK
Fixes #1719
> Adds configuration option to turn off practical support

- app/helpers/welcome_message_helper.rb
* Added a nice new note to the array of welcome messages in app/helpers/welcome_message_helper.rb
* <3 <3 <3 
* Fixes #X
* Bumps #Y
> added a new sweet welcome message!

- app/models/concerns/exportable.rb
* Adds practical support to exportable
Proof:
Fixes: #1721
> Adds practical support to exportable

- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/unlocks/new.html.erb
* adds view to squelch devise error message
> Adds error messages view to devise to squelch deprecation warnings #1721

- app/helpers/welcome_message_helper.rb
I wrote a nice note inbetween PRs!
> Portuguese welcome message!

- package.json
- yarn.lock
Removed critical vulnerabilities via selective dependencies.
These are slated to be fixed in a future webpacker [PR](https://github.com/rails/webpacker/issues/2181)
* package.json updates
* Fixes #1755
> Remove critical vulnerabilities

- .github/workflows/dcaf-build-workflow.yml
- config/mongoid.yml
- test/application_system_test_case.rb
This is the first lil bit to test out a build with GitHub Actions
* Initial `.github/workflows/dcaf-build-workflow.yml`
> Initial GitHub Actions workflow

- package.json
- yarn.lock
Upgrading set-value through yarn.
> Bump a dep version!

- app/assets/stylesheets/pregnancies.scss
- app/views/patients/_call_log.html.erb
- app/views/patients/_change_log.html.erb
- app/views/patients/_change_log_entry.html.erb
Pretty straightforward changes to convert the call log and changelog partials to BS4. You can limit review to just `_call_log` and `_change_log` and `_change_log_entry`.
* BS4ify changelog
* BS4ify call log
olde:
new:
* Bumps #1632
> BS4ify patient changelog and call log

- app/views/clinics/_clinic_form.html.erb
- app/views/clinics/index.html.erb
Bootstrap 4 upgrades to clinics pages (index, edit, new). Just need to eyeball files in views/clinics/*.
* BS4ify clinics/index, new, edit
olde:
new:
* Bumps #1632
> BS4ify clinic pages

- app/views/patients/data_entry.html.erb
BS4ify data entry partial. Basically identical, just had to swap some stuff to flexboxes. Recommend using whitespace view mode to see the substantial differences. Also just straight up copied the special circumstances fieldset.
In the course of this I noticed the form needed some sprucing for changes to the patient model that have happened since then, so see #1791 for those fields.
* BS4ify data entry view
old:
new:
* Bumps #1632
> BS4ify data entry form

- app/helpers/welcome_message_helper.rb
Just adding in an additional welcome message per Hacktoberfest fun 🎃 
part of https://github.com/DCAFEngineering/dcaf_case_management/issues/884
> Additional Welcome Message

- app/views/dashboards/_search_form.html.erb
- app/views/dashboards/search.js.erb
- app/views/patients/_new_patient.html.erb
BS4ify the new patient form. (Please note that the CI failures are intentional and we're merging this into a featurebranch.) 
The alignment goes out of sync, but I'm not extremely troubled by that. This form is a little clogged up regardless, but does space a bit nicer when you just give it over to the flexboxes.
No particular sins against programming in here.
* BS4 to the new patient form
olde:
new:
* Fixes #1632
> BS4ify the new patient partial

- app/helpers/welcome_message_helper.rb
Signed-off-by: Anderson Fernandes <fernandesanderson14@gmail.com>
* Add's a new message to the welcome message helper
It relates to the following issue #884
> Add new message

- test/factories/user.rb
* replaced static attribute with a block attribute on user factory
It relates to the following issue #1793
> Update deprecated factory

- Gemfile.lock
- package.json
- yarn.lock
> Update set-value and rubyzip

- README.md
- _design/accessibility_script.js
- db/seeds.rb
- docs/ADOPTING_DARIA.md
- docs/SETUP.md
- lib/tasks/seed_training.rake
- test/system/user_searches_test.rb
See link here for more info. This will negate the risk of sending emails to test.com.
https://www.iana.org/domains/reserved
PROS: security, compliance with web specs
CONS: will need to inform anyone who is likely to use the sandbox (add a flag above?)
> Replaces all instances of test.com with example.com in accordance with IANA RFCs 2606, 6761

- config/locales/en.yml
- config/locales/es.yml
- test/helpers/dashboards_helper_test.rb
- test/helpers/notes_helper_test.rb
- test/helpers/practical_supports_helper_test.rb
Small test fixes to get our test suite back in sync. Mostly just small place changes, but also deleting some tests that are now reflected in views.
Removed an i18n key in the process which we were never using.
* test fixes
* Bumps #1632
> BS4 - unit test fixes

- app/views/accountants/index.html.erb
- app/views/clinics/_clinic_form.html.erb
- app/views/dashboards/_search_form.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/patients/_practical_support.html.erb
- app/views/patients/data_entry.html.erb
- app/views/practical_supports/_entries.html.erb
- app/views/practical_supports/_new.html.erb
- test/integration_helper.rb
- test/system/authorization_test.rb
- test/system/call_list_test.rb
- test/system/data_entry_test.rb
- test/system/filter_medicaid_clinics_test.rb
- test/system/filter_naf_clinics_test.rb
- test/system/navbar_links_test.rb
- test/system/practical_support_behaviors_test.rb
- test/system/user_management_test.rb
System tests are shaking out to be two buckets: One is slight changes to ids or one-liner fixes, and the others are a little more complex - probably form surgery or some things that don't translate as well in BS4. This PR is the easy stuff.
* easy PR fixes - id swaps, links becoming buttons, make some forms synchronous
* Bumps #1632
> BS4 system tests part one - the easy part

- app/helpers/welcome_message_helper.rb
> Add new message.

- app/helpers/welcome_message_helper.rb
Added welcome message for ticket - #1814
> Added welcome message

- test/system/data_entry_test.rb
Adds system tests for new form fields
* Fixes #1828
> Add system specs for new fields

- README.md
Updating the README team leads (and shoutouts!) @colinxfleming lemme know if this is offbase!
* Fixes #1837
> First pass update README with team leads & shoutouts

- app/views/users/index.html.erb
rather than fight with pseudo elements like visited, just use a dang button
* Fixes #1632
> okay, use a btn instead of a styled link

- app/views/clinics/index.html.erb
- test/system/clinic_management_test.rb
my reign of terror against a:visited by switching these to buttons continues
* Fixes #1632
> Use a btn and not a link on add new clinics too

- docs/SETTING_UP_A_NEW_INSTANCE.md
@harumhelmy heroically went through a very old set of new instructions. This updates that to reflect what we actually did.
when reviewing please confirm that this makes sense and matches your memory! please request clarification on anything that isn't clear, as well.
* update new instance instructions to better reflect what we actually did
no issues
> Update new instance instructions

- app/helpers/welcome_message_helper.rb
I'm onboarding to the project and am adding a nice note for the case managers.
* Adds a new entry to `welcome_message_helper`
* Bumps #884
> Add a new entry to the welcome message helper

- app/helpers/welcome_message_helper.rb
Added a new message to welcome_message at onboarding with KAT!
* Fixes #X
* Bumps #884
> added new message to welcome_message_helper

- README.md
- docs/SETUP.md
bumping the readme to remove some OBE sections and update the directions. s/o to the person from december's hacknight who found out the hard way our mongo install docs were out of date.
> near year new readme

- app/helpers/welcome_message_helper.rb
Added a welcome message!
* #884
> Add a welcome message

- app/helpers/welcome_message_helper.rb
> adding support welcome support message

- app/helpers/welcome_message_helper.rb
> Added thank you message

- Gemfile
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/external_pledges/_edit.html.erb
- app/views/external_pledges/_new.html.erb
- app/views/patients/_notes.html.erb
- app/views/patients/_patient_dashboard.html.erb
- app/views/patients/_pledge.html.erb
- app/views/practical_supports/_edit.html.erb
- app/views/practical_supports/_new.html.erb
- app/views/users/new.html.erb
I changed remaining instances of bootstrap_form_for in the codebase to bootstrap_form_with, and confirmed that all tests are still passing! Went a bit overboard with separating the commits, heh. 
* Fixes #1861
> Replaced remaining instances of bootstrap_form_for with bootstrap_form_with

- .docker/Dockerfile
Tiny change to get dockerfile working again
* -y for Dockerfile apt-get upgrade
> add y to dockerfile

- docs/ADOPTING_DARIA.md
- docs/MIGRATING_YOUR_DATA.md
@NerdyGirl537 wrote up a great data entry guide as a google doc. I want to check it into github so we can have it available.
* Add data entry doc
no issues
> Add data migration doc

- app/assets/stylesheets/application.css.scss
removed the fade on hover function
* deleted the fade section of the flash section of the stylesheet
I tried to screenshot, but it doesn't last long enough! Did confirm that it works locally though.
* Fixes #1913 
* Bumps #Y
> remove fade

- app/views/layouts/_navigation_links.html.erb
- config/locales/en.yml
- config/locales/es.yml
- test/system/navbar_links_test.rb
hops off https://github.com/DCAFEngineering/dcaf_case_management/pull/1932 to fix a real minor test issue. (CI would have nabbed this, but CI's still busted for branches.)
* #1932 pretty much
* Fixes #1924
> update nav_bar and corresponding tests

- .circleci/config.yml
can't prove it won't work, I guess.
> try uploading ci test results to see if that prevents errors

- app/helpers/welcome_message_helper.rb
> Added new welcome message

- app/helpers/welcome_message_helper.rb
> add nice message to welcome_message_helper array

- app.json
We're now happy sentry customers, so rig this up on app init.
* add `SENTRY_DSN` key to app.json
no issues
> add sentry_dsn env var to app.json

- README.md
- docs/SETUP.md
* We have GitHubs branch protection, so no need for out setup step obscuring the upstream push url.
* Added @harumhelmy to our appreciation list!
* Noted Colin's on sabbatical for the rest of the year
For reviewer:
* Tag this PR:
* If it …
> Developer Docs Update - Setup & Kudos

- app/helpers/welcome_message_helper.rb
Added a positive message
* Bumps #884 
For reviewer:
> Add a new Welcome Message

- app/helpers/welcome_message_helper.rb
* Adds a welcome note for case managers
* #884
> Adding welcome note

- app/helpers/welcome_message_helper.rb
> added a welcome note

- app/helpers/welcome_message_helper.rb
I added a cute note for case managers with unicorns and sparkles
* adds a unicorn sparkle message for case managers
* Connects https://github.com/DCAFEngineering/dcaf_case_management/issues/884
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or …
> New nice note

- .circleci/config.yml
- README.md
- codecov.yml
- docs/ADMINISTRATION_AND_MAINTENANCE_PLAN.md
- docs/ADOPTING_DARIA.md
- docs/OUR_DATA_COLLECTION_PRACTICES.md
- docs/SETUP.md
- docs/onboarding/DARIA_WORKFLOW_TRYOUT.md
Find and repalce all references to our master branch with main
* Updates Circle CI config
* Update CodeCov
* Update docs
* Fixes #2021 
For reviewer:
* Tag this PR:
* If it contains neither, no need to …
> Find and repalce all references to our master branch with main

- README.md
> small tweak to test Circle integration

- package.json
- yarn.lock
Dependabot alerts!
* Bumps  "serialize-javascript", "dot-prop", "kind-of"
For reviewer:
* Tag this PR:
> dependabot alert updates

- app/helpers/welcome_message_helper.rb
Added a welcome message
* Bumps #884 
For reviewer:
* Tag this PR:
> Welcome message arjun

- .gitattributes
- app/helpers/patients_helper.rb
- test/helpers/patients_helper_test.rb
Fixed gestation period dropdown, and learned how to run unit tests!
* Changes 30 wk dropdown to 40 wk.
* Fixes #2038 
For reviewer:
* Tag this PR:
> update gestation dropdown

- package.json
- yarn.lock
* Bumps node-forge
For reviewer:
* Tag this PR:
> Bump to node-forge 0.10.0

- docs/SETUP.md
Hi all,
Adding info to our setup docs linking to the document I'm using to document Rails X Docker X Windows issues for this project and a handful of others.
I was originally going to put the document in the repo here, but other projects had interest too.
> Add Windows Docker info to SETUP.md

- app/helpers/welcome_message_helper.rb
This pull request adds a new greeting message to the message array! 
It relates to the following issue #884
For reviewer:
Add greeting message to message array.
> ADD new welcome msg

- app/helpers/welcome_message_helper.rb
Thanks for all the help at the Code for DC Virtual Project Night!
* add new welcome message in array 
* #884 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is …
> add welcome message issue #884

- README.md
Put Colin back on the README as active!
> Unsabbatical Colin!

- docs/PRESS.md
The Daily Beast said some nice stuff about our project in a (behind a paywall though). (Also note: We aren't uber for abortion, _although..._)
* Add the Daily Beast story to our press clippings
no issues
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package …
> Add a Daily Beast story to the press clippings list

- db/seeds.rb
Do some DRYing up and optimizing of the seedfile in advance of finishing up #814 . Shouldn't be any practical change to the output.
Have tested and it works pretty much the same - hopefully more readable now.
* run rubocop on the seedfile
* DRY up the seedfile
* Bumps #814
For reviewer:
* Tag this PR: …
> Refactor seedfile

- app/services/pledge_form_generator.rb
Slightly widen a component to prevent overflow on longer env vars.
no issues
godmoding
> For pledge form, expand bounding box width

- Gemfile
- docs/SETUP.md
Put it in dev/test instead of dev. whoops
For reviewer:
* Tag this PR:
> (Actually) Last Postgres Setup config!

- docs/administering/SETTING_UP_A_NEW_INSTANCE.md
> Add documentation for creating a mongodb cluster

- docs/administering/SETTING_UP_A_NEW_INSTANCE.md
* Improves instructions for creating a new app in Sqreen. The Sqreen admin UI has changed, and the old description is no longer accurate.
> Link directly to the Sqreen app creation page

- app/helpers/welcome_message_helper.rb
#884
- add a welcome message
* #884 
For reviewer:
* Tag this PR:
> Update welcome_message_helper.rb #884

- app/controllers/patients_controller.rb
- app/lib/paper_trail_version.rb
- app/models/clinic.rb
- app/models/concerns/callable.rb
- app/models/fulfillment.rb
- app/models/practical_support.rb
- test/controllers/patients_controller_test.rb
- test/models/call_list_entry_test.rb
- test/models/event_test.rb
- test/models/patient/exportable_test.rb
- test/models/patient_test.rb
- test/models/practical_support_test.rb
- test/models/user_test.rb
- test/system/event_log_interaction_test.rb
In the spirit of reducing the mental load from #2123, here are some of the diffs we can extract that don't feel
* spacing, comments, and other similar trivial changes from mongo -> pg work
* a few test improvements and hardenings that were necessary under pg
* stems from #2072 
For reviewer:
* Tag this PR:
* `dependencies` if it contains …
> Minor, extractable changes/diffs from mongo -> pg

- docs/AGREEMENTS.md
We can flesh these out a bit more later, but for right now they're needed for app verification.
* add an AGREEMENTS.md doc
* Bumps #2120 
For reviewer:
* Tag this PR:
* If it contains …
> Add some boilerplate agreements

- app/helpers/welcome_message_helper.rb
* welcome message
It relates to the following issue:
* https://github.com/DCAFEngineering/dcaf_case_management/issues/884
> welcome message

- app/views/layouts/_footer.html.erb
just a tiny change. I realized that the `mailto` link in the footer doesn't actually create a proper email link.
For reviewer:
* Tag this PR:
> fix mailto URL

- .circleci/config.yml
- .github/workflows/test_dev_env.yml
- Remove unneeded commented-out code
- Re-add zeitwork check, which fixes #2027
- Remove `yarn audit`, since this kind of functionality is already
integrated into Github Security alerts.
- Add CI for building the dev environment, which fixes #2091 
This last bullet will need to be merged before it can be tested :/
For reviewer:
* Just make sure CI is passing :)
> Clean up CI

- package.json
- yarn.lock
Bumps some dependencies (Thanks dependabot!)
For reviewer:
* Tag this PR:
> Dep bumps!

- app/helpers/welcome_message_helper.rb
issue #884
Added welcome message from Kory
> Kory Welcome Message

- Gemfile
- Gemfile.lock
- app/controllers/external_pledges_controller.rb
- app/lib/paper_trail_version.rb
- app/models/archived_patient.rb
- app/models/audit_trail.rb
- app/models/concerns/paper_trailable.rb
- app/models/concerns/urgency.rb
- app/models/user.rb
- config/environments/test.rb
- test/controllers/calls_controller_test.rb
- test/controllers/clinics_controller_test.rb
- test/controllers/external_pledges_controller_test.rb
- test/controllers/notes_controller_test.rb
- test/controllers/practical_supports_controller_test.rb
- test/helpers/notes_helper_test.rb
- test/lib/reporting/patient_test.rb
- test/models/archived_patient_test.rb
- test/models/audit_trail_test.rb
- test/models/call_test.rb
- test/models/external_pledge_test.rb
- test/models/note_test.rb
- test/models/paper_trail_version_test.rb
- test/models/practical_support_test.rb
- test/models/user_test.rb
- test/test_helper.rb
A couple of app changes, but mostly unit test fixes to get that back to green.
Sorry for the large file diff; I know anything over 15 files tends to make eyes glaze over. I've tried to leave comments where possible.
* some minor fixes to the app code - mistakes I made in translating things over from the original omnibus, or mistakes in rebasing
* improve the with_versioning helper to reduce its overhead
* `rails t` (but not the system tests) should return green now
Just for safety's sake you can verify stuff works by running the standard migration commands. I wouldn't fret about the exact numbers here:
```
git checkout main && rails db:drop db:create db:migrate …
```
> Get all unit tests working on pg + improve with_versioning

- app/models/user.rb
> comment out user email callbacks for a second

- app/models/user.rb
Reverts DCAFEngineering/dcaf_case_management#2233
Part of #2143
> Reenable emailling after PG migration

- Gemfile.lock
SORRY @lomky 
I forgot to re-bundle install after removing mongo-session-store.
* actually remove mongo session store
* Fixes #2236  (continued)
For reviewer:
* Tag this PR:
* If it contains neither, no …
> actually remove mongo session store

- app/helpers/welcome_message_helper.rb
Apologies, all. Clearly was too excited to get started. Correct pull request is here
> For real this time

- Gemfile
- Gemfile.lock
- app/controllers/dashboards_controller.rb
- app/controllers/patients_controller.rb
- app/models/concerns/call_listable.rb
- app/models/concerns/exportable.rb
- app/models/patient.rb
- config/environments/development.rb
- config/environments/test.rb
- test/test_helper.rb
This cropped up again in an inconvenient way, so going to make this my 'chip away at it' project this week.
* install bullet gem
* make bullet fail tests if it hits a problem
* fix the problems
* bumps #2225 
For reviewer:
* Tag this PR: …
> add bullet gem, fix some of our identified n+1 joins

- .github/workflows/test_dev_env.yml
missed a spot! We want to trigger builds on main too, since that's what triggers deploys to heroku.
> do builds on main

- docs/user_guides/CONFIGURING_DARIA.md
- docs/user_guides/README.md
Adds an admin guide for config management.
* what it says on the tin
* Bumps #1943
For reviewer:
* Tag this PR:
> Add admin guide for Config management

- docs/user_guides/CLINIC_INFORMATION.md
- docs/user_guides/README.md
adds a doc for how to CRUD clinics as an admin.
* add an admin guide for maintaining clinics
* Bumps #1943 
For reviewer:
* Tag this PR:
> Add admin guide for clinic maintenance

- docs/user_guides/README.md
- docs/user_guides/USER_ADMIN.md
adds a doc for how to CRUD users as an admin.
* add an admin guide for maintaining users
* Bumps #1943 
For reviewer:
* Tag this PR:
> Add admin guide for user maintenance

- Gemfile
- Gemfile.lock
- codecov.yml
- test/test_helper.rb
* Removing the codecov get, since we activated the CodeCov GithubAction
* TK: configuration?
For reviewer:
* Tag this PR:
> Reconfigure CodeCov

- app/models/config.rb
- test/models/config_test.rb
This PR extends the config validation system to allow multiple validators per field. It also validates that singleton values aren't lists.
* Adds a new `validate_singleton` validator
* Turns validators from single functions to lists of functions
* Adds a few tests (let me know if we should test every field, rather than just a few)
* Fixes #2194 
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that …
> multiple validations and singletons

- test/test_helper.rb
In #2348 we parallelized our system tests, but this broke things in Docker. :'( There may be a more clever to get the parallel tests working in docker, but since we'll probably only be running system tests locally for individual debugging, the time is less of a concern, and I think this quick fix is appropriate for the time being. This should _not_ affect non-docker (bare metal, CI) execution.
* adds a check for docker environment
* (etc)
* Fixes #X
* Bumps #Y …
> Don't parallelize system tests in docker

- .github/workflows/test_dev_env.yml
* Stores test coverage artifact
* Stores screenshot artifacts
* Fixes #2430 
For reviewer:
* Check CI and make sure you can download artifacts (e.g. https://github.com/DARIAEngineering/dcaf_case_management/actions/runs/1492613843#artifacts)
> Save test artifacts

- app/controllers/practical_supports_controller.rb
- app/models/practical_support.rb
- app/views/practical_supports/_edit.html.erb
- app/views/practical_supports/_entries.html.erb
- app/views/practical_supports/_new.html.erb
- db/migrate/20211118014015_add_amounts_to_practical_support.rb
- db/schema.rb
- test/controllers/practical_supports_controller_test.rb
- test/models/practical_support_test.rb
- test/system/practical_support_behaviors_test.rb
* (etc)
* Fixes #2415 
* Bumps #Y
For reviewer:
* Tag this PR: …
> add money to practical supports

- config/initializers/new_framework_defaults_6_1.rb
* (etc)
* Fixes #X
* Bumps #Y
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, …
> Rails 7 upgrade: Get on 6.1 defaults - easy stuff

- README.md
- docs/ADOPTING_DARIA.md
- docs/onboarding/DARIA_WORKFLOW_TRYOUT.md
- docs/onboarding/MIGRATING_YOUR_DATA.md
- docs/onboarding/README.md
- docs/user_guides/USER_ADMIN.md
SORRY @lwaldsc 
* update docs to point to new sandbox env (everything else stays the same)
no issues
For reviewer:
* Tag this PR:
> remove refs to old sandbox env

- docs/administering/ONBOARDING_A_NEW_FUND.md
As per our slack conversation thread.
> Add required 'site_domain' param to query

- app/helpers/welcome_message_helper.rb
* I added a welcome message!
* Bumps #884
> add encouraging message to welcome_messages array #884

- db/seeds.rb
* adds some more practical supports to seeds, now with money
* Fixes #2193
* Adds to #2447 
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm …
> add more practical supports

- .docker/Dockerfile
- .github/workflows/test_dev_env.yml
- docker-compose.yml
Also, take this opportunity to rename our github workflows to be more descriptive.
> Rename env variables and container image name from dcaf prefix to daria

- Gemfile.lock
squash a puma cve to get the build to pass again
* bundle update puma
no issues
For reviewer:
* Tag this PR:
> bundle update puma

- .docker/Dockerfile
> Bump base docker images to current debian stable, fix #2548

- .github/workflows/deploy_staging.yml
- .github/workflows/test_dev_env.yml
Already added my Heroku API key as a repo secret.
Here are the docs for the github action: https://github.com/marketplace/actions/deploy-to-heroku
Also, remove comment in other CI file that is now a lie.
> Deploy staging on push to main, fixes #2553

- config/initializers/rack-attack.rb
* updates the responder handler name
* Fixes #2512
* Bumps #Y
For reviewer:
* Tag this PR: …
> update rack attack responder

- .docker/Dockerfile
- README.md
- app/helpers/welcome_message_helper.rb
- civic.json
Remove a couple refs to DCAF that are OBE.
* remove certain DCAF refs from readme, civic.json, and dockerfile
* Bumps #2552
For reviewer:
* Tag this PR:
* If it contains neither, no need …
> remove some refs to DCAF, pt 1

- README.md
- docs/ADOPTING_DARIA.md
- docs/INTRO_BLURB.md
- docs/TECH_STACK_INTRO.md
Updates docs with the slack channel name
* Bumps #2552 
For reviewer:
* Tag this PR:
> Updates docs with the slack channel name

- app/helpers/welcome_message_helper.rb
- Add a welcome message to the welcome_message_helper.rb file
* Bumps #884 
For reviewer:
* Tag this PR:
> Add a lil nice message

- Gemfile.lock
Rack has an open CVE, so fix er up.
* `bundle update rack`
no issues
For reviewer:
* Tag this PR:
> update rack to squash a cve

- .docker/Dockerfile
- .github/workflows/test_dev_env.yml
- docker-compose.yml
- package.json
I have removed the css and js conatiners. Here is the error they were throwing:
```
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)
```
To re-add those containers: #2606
> Fix #2600: Turn on docker build

- app/controllers/patients_controller.rb
- app/helpers/tooltips_helper.rb
- app/models/archived_patient.rb
- app/models/concerns/exportable.rb
- app/views/patients/_abortion_information.html.erb
- config/locales/en.yml
- config/locales/es.yml
- db/migrate/20220727013523_add_solidarity_to_patient.rb
- db/schema.rb
- db/seeds.rb
- test/helpers/tooltips_helper_test.rb
- test/system/update_patient_info_test.rb
Does what it says on the tin!
* Adds solidarity boolean to patient model
* Updates view
* Adds to CSV export
* Fixes #2646 
* Bumps #Y
For reviewer:
* Tag this PR: …
> Add solidarity pledge

- docs/administering/ONBOARDING_A_NEW_FUND.md
Not very much changed, but bump setup instructions (mostly to remind us to ask some particular questions). I don't think anything else has changed since we last did one of these.
no views
no issues
For reviewer:
* Tag this PR:
> bump setup instructions for new fund

- docs/administering/ONBOARDING_A_NEW_FUND.md
two more onboarding questions I always ask and should document
no views
no issues
For reviewer:
* Tag this PR:
> couple more questions for onboarding

- Gemfile
- Gemfile.lock
Going to deploy this branch to sandbox to test
> Upgrade omniauth-google-oauth2 to fix #2693

- docs/administering/ONBOARDING_A_NEW_FUND.md
Replace references to Namecheap with Cloudflare, our new DNS provider.
> Update onboarding docs for setting up DNS

- config/environments/production.rb
Adds host header checks to prevent maliscious redirects.
* Adds host header check to production environment
For reviewer:
* Tag this PR:
> Add host header checks in production

- app/helpers/welcome_message_helper.rb
Adds a nice message to the collection in `app/helpers/welcome_message_helper.rb` as suggested in https://github.com/DARIAEngineering/dcaf_case_management/issues/884
* (etc)
* Fixes #X
* Bumps #Y
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug …
> Adds a nice message of encouragement to the collection.

- app/helpers/welcome_message_helper.rb
We (Kaitlin and Sean @syoungstone) added another welcome message option for the case managers who log in.
* Adds another welcome message.
* Bumps #884
> Add another welcome message option

- docker-compose.yml
To make it easier for interactive debugging in Docker, I added a couple flags so that we can attach to the running Docker container.
To debug, put a `byebug` wherever you want interactive debugging. Then you can attach to the web container with the following commands
```
docker ps
docker attach [name of web container from previous command]
```
* add stdin_open and tty to docker-compose.yml
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend …
> Debugging in Docker

- app/helpers/welcome_message_helper.rb
This PR adds another message for case managers for when they log in.
* Add another welcome message
* Bumps #884 
For reviewer:
* Tag this PR: …
> Add another nice message for case managers (Issue #884)

- docs/administering/OFFBOARDING_A_FUND.md
We learned this after off-boarding our first fund.
> Add note in docs about runtime of deletion script

- app/helpers/welcome_message_helper.rb
This is my first commit into the project. #884 
Adds another thank you string to the welcome helper
* Implements #884
> collado first commit

- docs/SECURITY.md
(stems from a conversation I'm having, plus we should spruce this doc up anyway)
> update the security doc

- docs/SECURITY.md
another quick bump to the security doc
> add database encryption practices to security data

- app/controllers/patients_controller.rb
- app/models/concerns/exportable.rb
- Update controller download handling to stream properly
- Remove unused eager loaded Notes (not used - 'count' is pulled with `size` from patient model)
* Fixes Fund reported issue
**NB: This issue was _not replicable_ in the tests or on console. Please checkout branch locally and confirm functionality before we merge, and then we should doublecheck on sandbox!**
For reviewer:
* Tag this PR:
* `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, …
> Fix anonymous CSV export

- app/helpers/welcome_message_helper.rb
> Fix spelling mistake in a welcome message

- README.md
- docs/SETUP.md
* Just some cleanup and removing defunct things!
For reviewer:
* Tag this PR:
> Modernize pass on README and SETUP docs

- app/helpers/welcome_message_helper.rb
- db/schema.rb
Added a Welcome Message to the welcome_message_helper array. See message below.
* "本当にありがございます。Thank you for everything, you are helping the world and we are behind you all the way!" (the first part is Japanese, saying "Thank you very much"
For reviewer:
* Tag this PR:
* `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile …
> Added a Welcome Message comment to the Hello World Issue.

- README.md
Minor change in wording of opening subheader in README.
> Minor change in first README subheader 

- .github/workflows/test_dev_env.yml
- app/javascript/src/hooks/__tests__/usei18n.test.js
- babel.config.js
- jest-setup.js
- package.json
- yarn.lock
I've been working on rewriting one of our autosave forms in React. I didn't want that PR to be too giant, so I split out the Jest configuration into its own PR.
This PR adds Jest and all the other React testing dependencies to be able to write unit tests for our React code.
I chose Jest + [Testing Library](https://testing-library.com/) b/c it's what I'm most familiar with and b/c I really like that Testing Library's API encourages writing accessible frontend code. At this point, Jest is the industry standard test running and I'm pretty sure Testing Library is the standard for React tests as its been in every project I've worked with over the last 4 years.
For reviewer:
* Adjust the title to explain what it does …
> Configure jest testing

- .github/workflows/test_dev_env.yml
nothing fancy here, just a stub to get ci to chill
* add a problem to npm audit ignore list
no views
no issues
For reviewer:
* Tag this PR:
> add another bootstrap problem to ignorelist

- Gemfile.lock
static scan failure
* bump nokogiri to a safe version
no issues
For reviewer:
* Tag this PR:
> bump nokogiri

- app/helpers/tooltips_helper.rb
- app/models/concerns/shareable.rb
- app/models/config.rb
- test/models/config_test.rb
Pulls in the work done in #2921. Thank you @Nubbify!
- Bumps #1559 
For reviewer:
* Tag this PR:
> Updated - Improve the configuration model

- app/models/config.rb
@xmunoz @colinxfleming Please doublecheck me on the key values in the `DEFAULT` calls.
> Very important typo
